/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {8, 1, 1};
static const casadi_int casadi_s5[3] = {16, 1, 1};
static const casadi_int casadi_s6[68] = 
  {19, 16, 0, 2, 3, 12, 21, 27,
  33, 37, 41, 42, 43, 44, 45, 46,
  47, 48, 49, 6, 7, 8, 6, 7,
  9, 10, 11, 12, 13, 14, 15, 6,
  7, 9, 10, 11, 12, 13, 14, 15,
  6, 7, 9, 10, 11, 12, 6, 7,
  9, 10, 11, 12, 9, 10, 11, 12,
  9, 10, 11, 12, 16, 17, 0, 1,
  2, 3, 4, 5};
static const casadi_int casadi_s7[3] = {16, 0, 1};

/* bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt:(i0[13],i1[6],i2[0],i3[],i4[8])->(o0[16],o1[19x16,49nz],o2[16x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45;
  a00=arg[4]? arg[4][0] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a00=(a00-a01);
  a01=casadi_sq(a00);
  a02=arg[4]? arg[4][1] : 0;
  a03=arg[0]? arg[0][1] : 0;
  a02=(a02-a03);
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=9.9999999999999995e-07;
  a01=(a01+a03);
  a01=sqrt(a01);
  a04=arg[4]? arg[4][3] : 0;
  a04=(a01-a04);
  if (res[0]!=0) res[0][0]=a04;
  a04=arg[0]? arg[0][2] : 0;
  a05=arg[4]? arg[4][4] : 0;
  a04=(a04-a05);
  if (res[0]!=0) res[0][1]=a04;
  a00=(a00/a01);
  a04=arg[4]? arg[4][6] : 0;
  a05=(a00*a04);
  a06=2.;
  a07=arg[0]? arg[0][4] : 0;
  a08=arg[0]? arg[0][5] : 0;
  a09=(a07*a08);
  a10=arg[0]? arg[0][6] : 0;
  a11=arg[0]? arg[0][3] : 0;
  a12=(a10*a11);
  a13=(a09+a12);
  a13=(a06*a13);
  a14=arg[0]? arg[0][7] : 0;
  a15=(a13*a14);
  a16=1.;
  a17=casadi_sq(a07);
  a18=casadi_sq(a10);
  a19=(a17+a18);
  a19=(a06*a19);
  a19=(a16-a19);
  a20=arg[0]? arg[0][8] : 0;
  a21=(a19*a20);
  a15=(a15+a21);
  a21=(a08*a10);
  a22=(a07*a11);
  a22=(a21-a22);
  a22=(a06*a22);
  a23=arg[0]? arg[0][9] : 0;
  a24=(a22*a23);
  a15=(a15+a24);
  a24=(a05*a15);
  a02=(a02/a01);
  a25=(a02*a04);
  a26=casadi_sq(a08);
  a18=(a26+a18);
  a18=(a06*a18);
  a18=(a16-a18);
  a27=(a18*a14);
  a09=(a09-a12);
  a09=(a06*a09);
  a12=(a09*a20);
  a27=(a27+a12);
  a12=(a07*a10);
  a28=(a08*a11);
  a12=(a12+a28);
  a12=(a06*a12);
  a28=(a12*a23);
  a27=(a27+a28);
  a28=(a25*a27);
  a24=(a24-a28);
  a28=arg[4]? arg[4][5] : 0;
  a24=(a24-a28);
  if (res[0]!=0) res[0][2]=a24;
  a24=(a00*a27);
  a28=(a02*a15);
  a24=(a24+a28);
  if (res[0]!=0) res[0][3]=a24;
  a24=casadi_sq(a18);
  a28=casadi_sq(a13);
  a24=(a24+a28);
  a24=(a24+a03);
  a24=sqrt(a24);
  a03=(a18/a24);
  a28=arg[4]? arg[4][7] : 0;
  a29=cos(a28);
  a30=(a29*a00);
  a28=sin(a28);
  a31=(a28*a02);
  a30=(a30-a31);
  a30=(a03-a30);
  if (res[0]!=0) res[0][4]=a30;
  a30=(a13/a24);
  a31=(a28*a00);
  a32=(a29*a02);
  a31=(a31+a32);
  a31=(a30-a31);
  if (res[0]!=0) res[0][5]=a31;
  a31=(a11*a07);
  a31=(a31+a21);
  a31=(a06*a31);
  a17=(a17+a26);
  a17=(a06*a17);
  a17=(a16-a17);
  a26=atan2(a31,a17);
  if (res[0]!=0) res[0][6]=a26;
  a26=(a11*a08);
  a21=(a10*a07);
  a26=(a26-a21);
  a26=(a06*a26);
  a21=asin(a26);
  if (res[0]!=0) res[0][7]=a21;
  a21=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][8]=a21;
  a21=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][9]=a21;
  a21=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][10]=a21;
  a21=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][11]=a21;
  a21=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][12]=a21;
  a21=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][13]=a21;
  a21=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][14]=a21;
  a21=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][15]=a21;
  a21=(-a00);
  if (res[1]!=0) res[1][0]=a21;
  a21=(-a02);
  if (res[1]!=0) res[1][1]=a21;
  if (res[1]!=0) res[1][2]=a16;
  a21=(a00/a01);
  a32=(a21*a00);
  a33=(1./a01);
  a32=(a32-a33);
  a34=(a04*a32);
  a34=(a15*a34);
  a01=(a02/a01);
  a35=(a01*a00);
  a36=(a04*a35);
  a36=(a27*a36);
  a34=(a34-a36);
  if (res[1]!=0) res[1][3]=a34;
  a21=(a21*a02);
  a34=(a04*a21);
  a34=(a15*a34);
  a01=(a01*a02);
  a01=(a01-a33);
  a04=(a04*a01);
  a04=(a27*a04);
  a34=(a34-a04);
  if (res[1]!=0) res[1][4]=a34;
  a34=(a06*a10);
  a04=(a14*a34);
  a33=(a06*a07);
  a36=(a23*a33);
  a04=(a04-a36);
  a37=(a05*a04);
  a38=(a06*a08);
  a39=(a23*a38);
  a40=(a20*a34);
  a40=(a39-a40);
  a41=(a25*a40);
  a37=(a37-a41);
  if (res[1]!=0) res[1][5]=a37;
  a37=(a14*a38);
  a07=(a07+a07);
  a07=(a06*a07);
  a41=(a20*a07);
  a37=(a37-a41);
  a11=(a06*a11);
  a41=(a23*a11);
  a37=(a37-a41);
  a42=(a05*a37);
  a43=(a20*a38);
  a23=(a23*a34);
  a43=(a43+a23);
  a44=(a25*a43);
  a42=(a42-a44);
  if (res[1]!=0) res[1][6]=a42;
  a42=(a14*a33);
  a42=(a42+a23);
  a23=(a05*a42);
  a44=(a20*a33);
  a08=(a08+a08);
  a08=(a06*a08);
  a45=(a14*a08);
  a44=(a44-a45);
  a44=(a44+a41);
  a41=(a25*a44);
  a23=(a23-a41);
  if (res[1]!=0) res[1][7]=a23;
  a23=(a14*a11);
  a10=(a10+a10);
  a06=(a06*a10);
  a10=(a20*a06);
  a23=(a23-a10);
  a23=(a23+a39);
  a39=(a05*a23);
  a14=(a14*a06);
  a20=(a20*a11);
  a14=(a14+a20);
  a36=(a36-a14);
  a14=(a25*a36);
  a39=(a39-a14);
  if (res[1]!=0) res[1][8]=a39;
  a39=(a05*a13);
  a14=(a25*a18);
  a39=(a39-a14);
  if (res[1]!=0) res[1][9]=a39;
  a39=(a05*a19);
  a14=(a25*a09);
  a39=(a39-a14);
  if (res[1]!=0) res[1][10]=a39;
  a05=(a05*a22);
  a25=(a25*a12);
  a05=(a05-a25);
  if (res[1]!=0) res[1][11]=a05;
  a05=(a27*a32);
  a25=(a15*a35);
  a05=(a05+a25);
  if (res[1]!=0) res[1][12]=a05;
  a27=(a27*a21);
  a15=(a15*a01);
  a27=(a27+a15);
  if (res[1]!=0) res[1][13]=a27;
  a40=(a00*a40);
  a04=(a02*a04);
  a40=(a40+a04);
  if (res[1]!=0) res[1][14]=a40;
  a43=(a00*a43);
  a37=(a02*a37);
  a43=(a43+a37);
  if (res[1]!=0) res[1][15]=a43;
  a44=(a00*a44);
  a42=(a02*a42);
  a44=(a44+a42);
  if (res[1]!=0) res[1][16]=a44;
  a36=(a00*a36);
  a23=(a02*a23);
  a36=(a36+a23);
  if (res[1]!=0) res[1][17]=a36;
  a36=(a00*a18);
  a23=(a02*a13);
  a36=(a36+a23);
  if (res[1]!=0) res[1][18]=a36;
  a09=(a00*a09);
  a19=(a02*a19);
  a09=(a09+a19);
  if (res[1]!=0) res[1][19]=a09;
  a00=(a00*a12);
  a02=(a02*a22);
  a00=(a00+a02);
  if (res[1]!=0) res[1][20]=a00;
  a00=(a29*a32);
  a02=(a28*a35);
  a00=(a00-a02);
  a00=(-a00);
  if (res[1]!=0) res[1][21]=a00;
  a00=(a29*a21);
  a02=(a28*a01);
  a00=(a00-a02);
  a00=(-a00);
  if (res[1]!=0) res[1][22]=a00;
  a03=(a03/a24);
  a13=(a13+a13);
  a00=(a13*a34);
  a02=(a24+a24);
  a00=(a00/a02);
  a22=(a03*a00);
  a22=(-a22);
  if (res[1]!=0) res[1][23]=a22;
  a22=(a13*a38);
  a22=(a22/a02);
  a12=(a03*a22);
  a12=(-a12);
  if (res[1]!=0) res[1][24]=a12;
  a12=(a08/a24);
  a09=(a13*a33);
  a18=(a18+a18);
  a19=(a18*a08);
  a09=(a09-a19);
  a09=(a09/a02);
  a19=(a03*a09);
  a12=(a12+a19);
  a12=(-a12);
  if (res[1]!=0) res[1][25]=a12;
  a12=(a06/a24);
  a13=(a13*a11);
  a18=(a18*a06);
  a13=(a13-a18);
  a13=(a13/a02);
  a03=(a03*a13);
  a12=(a12+a03);
  a12=(-a12);
  if (res[1]!=0) res[1][26]=a12;
  a32=(a28*a32);
  a35=(a29*a35);
  a32=(a32+a35);
  a32=(-a32);
  if (res[1]!=0) res[1][27]=a32;
  a28=(a28*a21);
  a29=(a29*a01);
  a28=(a28+a29);
  a28=(-a28);
  if (res[1]!=0) res[1][28]=a28;
  a28=(a34/a24);
  a30=(a30/a24);
  a00=(a30*a00);
  a28=(a28-a00);
  if (res[1]!=0) res[1][29]=a28;
  a28=(a38/a24);
  a22=(a30*a22);
  a28=(a28-a22);
  if (res[1]!=0) res[1][30]=a28;
  a28=(a33/a24);
  a09=(a30*a09);
  a28=(a28-a09);
  if (res[1]!=0) res[1][31]=a28;
  a24=(a11/a24);
  a30=(a30*a13);
  a24=(a24-a30);
  if (res[1]!=0) res[1][32]=a24;
  a24=casadi_sq(a31);
  a30=casadi_sq(a17);
  a24=(a24+a30);
  a17=(a17/a24);
  a30=(a17*a33);
  if (res[1]!=0) res[1][33]=a30;
  a30=(a17*a11);
  a31=(a31/a24);
  a07=(a31*a07);
  a30=(a30+a07);
  if (res[1]!=0) res[1][34]=a30;
  a30=(a17*a34);
  a31=(a31*a08);
  a30=(a30+a31);
  if (res[1]!=0) res[1][35]=a30;
  a17=(a17*a38);
  if (res[1]!=0) res[1][36]=a17;
  a26=casadi_sq(a26);
  a26=(a16-a26);
  a26=sqrt(a26);
  a38=(a38/a26);
  if (res[1]!=0) res[1][37]=a38;
  a34=(a34/a26);
  a34=(-a34);
  if (res[1]!=0) res[1][38]=a34;
  a11=(a11/a26);
  if (res[1]!=0) res[1][39]=a11;
  a33=(a33/a26);
  a33=(-a33);
  if (res[1]!=0) res[1][40]=a33;
  if (res[1]!=0) res[1][41]=a16;
  if (res[1]!=0) res[1][42]=a16;
  if (res[1]!=0) res[1][43]=a16;
  if (res[1]!=0) res[1][44]=a16;
  if (res[1]!=0) res[1][45]=a16;
  if (res[1]!=0) res[1][46]=a16;
  if (res[1]!=0) res[1][47]=a16;
  if (res[1]!=0) res[1][48]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_0_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
