/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_cylinder_orbit_mpc_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {10, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {8, 1, 1};
static const casadi_int casadi_s5[88] = 
  {13, 13, 0, 9, 18, 18, 27, 36,
  45, 54, 60, 66, 72, 72, 72, 72,
  0, 1, 3, 4, 5, 6, 7, 8,
  9, 0, 1, 3, 4, 5, 6, 7,
  8, 9, 0, 1, 3, 4, 5, 6,
  7, 8, 9, 0, 1, 3, 4, 5,
  6, 7, 8, 9, 0, 1, 3, 4,
  5, 6, 7, 8, 9, 0, 1, 3,
  4, 5, 6, 7, 8, 9, 0, 1,
  3, 4, 5, 6, 0, 1, 3, 4,
  5, 6, 0, 1, 3, 4, 5, 6};

/* bluerov_cylinder_orbit_mpc_cost_y_e_hess:(i0[13],i1[0],i2[0],i3[10],i4[],i5[8])->(o0[13x13,72nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  a00=1.;
  a01=2.;
  a02=arg[0]? arg[0][5] : 0;
  a03=casadi_sq(a02);
  a04=arg[0]? arg[0][6] : 0;
  a05=casadi_sq(a04);
  a06=(a03+a05);
  a06=(a01*a06);
  a06=(a00-a06);
  a07=arg[0]? arg[0][7] : 0;
  a08=(a06*a07);
  a09=arg[0]? arg[0][4] : 0;
  a10=(a09*a02);
  a11=arg[0]? arg[0][3] : 0;
  a12=(a04*a11);
  a13=(a10-a12);
  a13=(a01*a13);
  a14=arg[0]? arg[0][8] : 0;
  a15=(a13*a14);
  a08=(a08+a15);
  a15=(a09*a04);
  a16=(a02*a11);
  a15=(a15+a16);
  a15=(a01*a15);
  a16=arg[0]? arg[0][9] : 0;
  a17=(a15*a16);
  a08=(a08+a17);
  a17=arg[3]? arg[3][3] : 0;
  a18=(a08*a17);
  a19=arg[5]? arg[5][7] : 0;
  a20=sin(a19);
  a21=arg[3]? arg[3][5] : 0;
  a22=(a20*a21);
  a19=cos(a19);
  a23=arg[3]? arg[3][4] : 0;
  a24=(a19*a23);
  a22=(a22+a24);
  a18=(a18-a22);
  a22=arg[5]? arg[5][6] : 0;
  a10=(a10+a12);
  a10=(a01*a10);
  a12=(a10*a07);
  a24=casadi_sq(a09);
  a05=(a24+a05);
  a05=(a01*a05);
  a05=(a00-a05);
  a25=(a05*a14);
  a12=(a12+a25);
  a25=(a02*a04);
  a26=(a09*a11);
  a26=(a25-a26);
  a26=(a01*a26);
  a27=(a26*a16);
  a12=(a12+a27);
  a27=arg[3]? arg[3][2] : 0;
  a28=(a12*a27);
  a28=(a22*a28);
  a18=(a18+a28);
  a28=arg[5]? arg[5][0] : 0;
  a29=arg[0]? arg[0][0] : 0;
  a28=(a28-a29);
  a29=casadi_sq(a28);
  a30=arg[5]? arg[5][1] : 0;
  a31=arg[0]? arg[0][1] : 0;
  a30=(a30-a31);
  a31=casadi_sq(a30);
  a29=(a29+a31);
  a31=9.9999999999999995e-07;
  a29=(a29+a31);
  a29=sqrt(a29);
  a32=(a18/a29);
  a32=(a32/a29);
  a33=(a28/a29);
  a34=(a32*a33);
  a35=-2.;
  a36=arg[3]? arg[3][0] : 0;
  a37=(a30/a29);
  a38=(a37/a29);
  a20=(a20*a23);
  a19=(a19*a21);
  a20=(a20-a19);
  a12=(a12*a17);
  a20=(a20+a12);
  a08=(a08*a27);
  a08=(a22*a08);
  a20=(a20-a08);
  a08=(a38*a20);
  a12=(a33/a29);
  a19=(a12*a18);
  a08=(a08+a19);
  a36=(a36-a08);
  a08=(a29+a29);
  a36=(a36/a08);
  a35=(a35*a36);
  a28=(a28+a28);
  a36=(a36/a08);
  a19=(a33+a33);
  a19=(a36*a19);
  a39=(a38*a33);
  a40=(a39/a29);
  a41=(a38/a29);
  a42=(a41*a33);
  a40=(a40+a42);
  a40=(a20*a40);
  a42=(a12*a33);
  a43=(1./a29);
  a42=(a42-a43);
  a44=(a42/a29);
  a45=(a12/a29);
  a46=(a45*a33);
  a44=(a44+a46);
  a44=(a18*a44);
  a40=(a40+a44);
  a40=(a40/a08);
  a19=(a19-a40);
  a19=(a28*a19);
  a19=(a35+a19);
  a34=(a34+a19);
  a34=(-a34);
  if (res[0]!=0) res[0][0]=a34;
  a32=(a32*a37);
  a34=(a37+a37);
  a36=(a36*a34);
  a34=(a38*a37);
  a34=(a34-a43);
  a43=(a34/a29);
  a41=(a41*a37);
  a43=(a43+a41);
  a43=(a20*a43);
  a41=(a12*a37);
  a19=(a41/a29);
  a45=(a45*a37);
  a19=(a19+a45);
  a18=(a18*a19);
  a43=(a43+a18);
  a43=(a43/a08);
  a36=(a36-a43);
  a43=(a28*a36);
  a32=(a32+a43);
  a32=(-a32);
  if (res[0]!=0) res[0][1]=a32;
  a43=(a01*a02);
  a18=(a16*a43);
  a19=(a01*a04);
  a45=(a14*a19);
  a45=(a18-a45);
  a40=(a17*a45);
  a44=(a07*a19);
  a46=(a01*a09);
  a47=(a16*a46);
  a44=(a44-a47);
  a48=(a27*a44);
  a48=(a22*a48);
  a40=(a40+a48);
  a48=(a40/a29);
  a44=(a17*a44);
  a45=(a27*a45);
  a45=(a22*a45);
  a44=(a44-a45);
  a45=(a38*a44);
  a40=(a12*a40);
  a45=(a45+a40);
  a45=(a45/a08);
  a40=(a28*a45);
  a48=(a48-a40);
  a48=(-a48);
  if (res[0]!=0) res[0][2]=a48;
  a40=(a14*a43);
  a49=(a16*a19);
  a40=(a40+a49);
  a50=(a17*a40);
  a51=(a07*a43);
  a52=(a09+a09);
  a53=(a01*a52);
  a54=(a14*a53);
  a51=(a51-a54);
  a54=(a01*a11);
  a55=(a16*a54);
  a51=(a51-a55);
  a56=(a27*a51);
  a56=(a22*a56);
  a50=(a50+a56);
  a56=(a50/a29);
  a51=(a17*a51);
  a40=(a27*a40);
  a40=(a22*a40);
  a51=(a51-a40);
  a40=(a38*a51);
  a50=(a12*a50);
  a40=(a40+a50);
  a40=(a40/a08);
  a50=(a28*a40);
  a56=(a56-a50);
  a56=(-a56);
  if (res[0]!=0) res[0][3]=a56;
  a50=(a14*a46);
  a57=(a02+a02);
  a58=(a01*a57);
  a59=(a07*a58);
  a50=(a50-a59);
  a50=(a50+a55);
  a55=(a17*a50);
  a59=(a07*a46);
  a59=(a59+a49);
  a49=(a27*a59);
  a49=(a22*a49);
  a55=(a55+a49);
  a49=(a55/a29);
  a59=(a17*a59);
  a50=(a27*a50);
  a50=(a22*a50);
  a59=(a59-a50);
  a50=(a38*a59);
  a55=(a12*a55);
  a50=(a50+a55);
  a50=(a50/a08);
  a55=(a28*a50);
  a49=(a49-a55);
  a49=(-a49);
  if (res[0]!=0) res[0][4]=a49;
  a55=(a04+a04);
  a60=(a01*a55);
  a61=(a07*a60);
  a62=(a14*a54);
  a61=(a61+a62);
  a47=(a47-a61);
  a61=(a17*a47);
  a62=(a07*a54);
  a63=(a14*a60);
  a62=(a62-a63);
  a62=(a62+a18);
  a18=(a27*a62);
  a18=(a22*a18);
  a61=(a61+a18);
  a18=(a61/a29);
  a62=(a17*a62);
  a47=(a27*a47);
  a47=(a22*a47);
  a62=(a62-a47);
  a38=(a38*a62);
  a12=(a12*a61);
  a38=(a38+a12);
  a38=(a38/a08);
  a28=(a28*a38);
  a18=(a18-a28);
  a18=(-a18);
  if (res[0]!=0) res[0][5]=a18;
  a28=(a17*a42);
  a08=(a22*a39);
  a08=(a27*a08);
  a28=(a28-a08);
  a08=(a06*a28);
  a39=(a17*a39);
  a42=(a22*a42);
  a42=(a27*a42);
  a39=(a39+a42);
  a42=(a10*a39);
  a08=(a08+a42);
  if (res[0]!=0) res[0][6]=a08;
  a42=(a13*a28);
  a12=(a05*a39);
  a42=(a42+a12);
  if (res[0]!=0) res[0][7]=a42;
  a28=(a15*a28);
  a39=(a26*a39);
  a28=(a28+a39);
  if (res[0]!=0) res[0][8]=a28;
  if (res[0]!=0) res[0][9]=a32;
  a20=(a20/a29);
  a20=(a20/a29);
  a20=(a20*a37);
  a30=(a30+a30);
  a36=(a30*a36);
  a35=(a35+a36);
  a20=(a20+a35);
  a20=(-a20);
  if (res[0]!=0) res[0][10]=a20;
  a44=(a44/a29);
  a45=(a30*a45);
  a44=(a44-a45);
  a44=(-a44);
  if (res[0]!=0) res[0][11]=a44;
  a51=(a51/a29);
  a40=(a30*a40);
  a51=(a51-a40);
  a51=(-a51);
  if (res[0]!=0) res[0][12]=a51;
  a59=(a59/a29);
  a50=(a30*a50);
  a59=(a59-a50);
  a59=(-a59);
  if (res[0]!=0) res[0][13]=a59;
  a62=(a62/a29);
  a30=(a30*a38);
  a62=(a62-a30);
  a62=(-a62);
  if (res[0]!=0) res[0][14]=a62;
  a30=(a17*a41);
  a38=(a22*a34);
  a38=(a27*a38);
  a30=(a30-a38);
  a38=(a06*a30);
  a34=(a17*a34);
  a41=(a22*a41);
  a41=(a27*a41);
  a34=(a34+a41);
  a41=(a10*a34);
  a38=(a38+a41);
  if (res[0]!=0) res[0][15]=a38;
  a13=(a13*a30);
  a05=(a05*a34);
  a13=(a13+a05);
  if (res[0]!=0) res[0][16]=a13;
  a15=(a15*a30);
  a26=(a26*a34);
  a15=(a15+a26);
  if (res[0]!=0) res[0][17]=a15;
  if (res[0]!=0) res[0][18]=a48;
  if (res[0]!=0) res[0][19]=a44;
  a44=arg[3]? arg[3][7] : 0;
  a48=(a11*a02);
  a26=(a04*a09);
  a48=(a48-a26);
  a48=(a01*a48);
  a26=casadi_sq(a48);
  a26=(a00-a26);
  a26=sqrt(a26);
  a44=(a44/a26);
  a34=(a44/a26);
  a48=(a48+a48);
  a30=(a48*a43);
  a26=(a26+a26);
  a30=(a30/a26);
  a30=(a34*a30);
  a30=(a01*a30);
  a30=(a02*a30);
  a05=arg[3]? arg[3][6] : 0;
  a24=(a24+a03);
  a24=(a01*a24);
  a00=(a00-a24);
  a24=(a11*a09);
  a24=(a24+a25);
  a24=(a01*a24);
  a25=casadi_sq(a24);
  a03=casadi_sq(a00);
  a25=(a25+a03);
  a03=(a00/a25);
  a41=(a03/a25);
  a29=(a24+a24);
  a50=(a29*a46);
  a50=(a41*a50);
  a50=(a05*a50);
  a50=(a01*a50);
  a50=(a09*a50);
  a30=(a30-a50);
  a50=casadi_sq(a06);
  a40=casadi_sq(a10);
  a50=(a50+a40);
  a50=(a50+a31);
  a50=sqrt(a50);
  a31=(a21/a50);
  a40=(a31/a50);
  a45=(a10+a10);
  a20=(a45*a19);
  a35=(a50+a50);
  a20=(a20/a35);
  a36=(a40*a20);
  a10=(a10/a50);
  a10=(a10/a50);
  a32=(a10*a21);
  a39=(a06/a50);
  a39=(a39/a50);
  a12=(a39*a23);
  a32=(a32+a12);
  a32=(a32/a35);
  a12=(a19+a19);
  a12=(a32*a12);
  a61=(a19/a50);
  a47=(a10*a20);
  a61=(a61-a47);
  a61=(a61/a50);
  a47=(a10/a50);
  a63=(a47*a20);
  a61=(a61-a63);
  a61=(a21*a61);
  a63=(a39*a20);
  a63=(a63/a50);
  a64=(a39/a50);
  a65=(a64*a20);
  a63=(a63+a65);
  a63=(a23*a63);
  a61=(a61-a63);
  a61=(a61/a35);
  a63=(a32/a35);
  a20=(a20+a20);
  a20=(a63*a20);
  a61=(a61-a20);
  a61=(a45*a61);
  a12=(a12+a61);
  a36=(a36+a12);
  a36=(a01*a36);
  a36=(a04*a36);
  a30=(a30-a36);
  if (res[0]!=0) res[0][20]=a30;
  a03=(a03*a05);
  a03=(a01*a03);
  a30=(a53/a25);
  a36=(a29*a54);
  a00=(a00+a00);
  a12=(a00*a53);
  a36=(a36-a12);
  a12=(a41*a36);
  a30=(a30+a12);
  a30=(a05*a30);
  a30=(a01*a30);
  a12=(a09*a30);
  a12=(a03-a12);
  a61=(a48*a19);
  a61=(a61/a26);
  a61=(a34*a61);
  a61=(a01*a61);
  a20=(a02*a61);
  a12=(a12-a20);
  a20=(a37*a17);
  a65=(a33*a22);
  a65=(a65*a27);
  a20=(a20+a65);
  a65=(a16*a20);
  a65=(a01*a65);
  a12=(a12-a65);
  a66=(a45*a43);
  a66=(a66/a35);
  a67=(a40*a66);
  a68=(a43+a43);
  a68=(a32*a68);
  a69=(a43/a50);
  a70=(a10*a66);
  a69=(a69-a70);
  a69=(a69/a50);
  a70=(a47*a66);
  a69=(a69-a70);
  a69=(a21*a69);
  a70=(a39*a66);
  a70=(a70/a50);
  a71=(a64*a66);
  a70=(a70+a71);
  a70=(a23*a70);
  a69=(a69-a70);
  a69=(a69/a35);
  a66=(a66+a66);
  a66=(a63*a66);
  a69=(a69-a66);
  a69=(a45*a69);
  a68=(a68+a69);
  a67=(a67+a68);
  a67=(a01*a67);
  a68=(a04*a67);
  a12=(a12-a68);
  if (res[0]!=0) res[0][21]=a12;
  a44=(a01*a44);
  a68=(a48*a54);
  a68=(a68/a26);
  a68=(a34*a68);
  a68=(a01*a68);
  a69=(a02*a68);
  a69=(a44+a69);
  a66=(a58/a25);
  a70=(a29*a19);
  a00=(a00*a58);
  a70=(a70-a00);
  a00=(a41*a70);
  a66=(a66+a00);
  a66=(a05*a66);
  a66=(a01*a66);
  a00=(a09*a66);
  a69=(a69-a00);
  a33=(a33*a17);
  a37=(a37*a22);
  a37=(a37*a27);
  a33=(a33-a37);
  a16=(a16*a33);
  a16=(a01*a16);
  a69=(a69+a16);
  a37=(a45*a46);
  a06=(a06+a06);
  a27=(a06*a58);
  a37=(a37-a27);
  a37=(a37/a35);
  a27=(a40*a37);
  a22=(a46+a46);
  a22=(a32*a22);
  a17=(a46/a50);
  a00=(a10*a37);
  a17=(a17-a00);
  a17=(a17/a50);
  a00=(a47*a37);
  a17=(a17-a00);
  a17=(a21*a17);
  a00=(a58/a50);
  a71=(a39*a37);
  a00=(a00+a71);
  a00=(a00/a50);
  a71=(a64*a37);
  a00=(a00+a71);
  a00=(a23*a00);
  a17=(a17-a00);
  a17=(a17/a35);
  a00=(a37+a37);
  a00=(a63*a00);
  a17=(a17-a00);
  a00=(a45*a17);
  a22=(a22+a00);
  a27=(a27+a22);
  a27=(a01*a27);
  a22=(a04*a27);
  a69=(a69-a22);
  if (res[0]!=0) res[0][22]=a69;
  a22=(a45*a32);
  a31=(a31-a22);
  a22=(a07*a20);
  a31=(a31+a22);
  a31=(a01*a31);
  a22=(a45*a54);
  a00=(a06*a60);
  a22=(a22-a00);
  a22=(a22/a35);
  a40=(a40*a22);
  a00=(a54+a54);
  a00=(a32*a00);
  a71=(a54/a50);
  a10=(a10*a22);
  a71=(a71-a10);
  a71=(a71/a50);
  a47=(a47*a22);
  a71=(a71-a47);
  a21=(a21*a71);
  a71=(a60/a50);
  a39=(a39*a22);
  a71=(a71+a39);
  a71=(a71/a50);
  a64=(a64*a22);
  a71=(a71+a64);
  a71=(a23*a71);
  a21=(a21-a71);
  a21=(a21/a35);
  a35=(a22+a22);
  a63=(a63*a35);
  a21=(a21-a63);
  a45=(a45*a21);
  a00=(a00+a45);
  a40=(a40+a00);
  a40=(a01*a40);
  a00=(a04*a40);
  a00=(a31-a00);
  a48=(a48*a46);
  a48=(a48/a26);
  a34=(a34*a48);
  a34=(a01*a34);
  a48=(a02*a34);
  a29=(a29*a43);
  a41=(a41*a29);
  a41=(a05*a41);
  a41=(a01*a41);
  a26=(a09*a41);
  a48=(a48+a26);
  a26=(a14*a33);
  a26=(a01*a26);
  a48=(a48+a26);
  a00=(a00-a48);
  if (res[0]!=0) res[0][23]=a00;
  a48=(a20*a19);
  if (res[0]!=0) res[0][24]=a48;
  a45=(a33*a19);
  a63=(-a45);
  if (res[0]!=0) res[0][25]=a63;
  a35=(a33*a43);
  a71=(a20*a46);
  a64=(a35-a71);
  if (res[0]!=0) res[0][26]=a64;
  if (res[0]!=0) res[0][27]=a56;
  if (res[0]!=0) res[0][28]=a51;
  if (res[0]!=0) res[0][29]=a12;
  a24=(a24/a25);
  a12=(a24*a05);
  a12=(a01*a12);
  a12=(a01*a12);
  a51=(a54/a25);
  a24=(a24/a25);
  a36=(a24*a36);
  a51=(a51-a36);
  a51=(a05*a51);
  a51=(a01*a51);
  a51=(a52*a51);
  a51=(a12+a51);
  a61=(a04*a61);
  a51=(a51+a61);
  a30=(a11*a30);
  a51=(a51-a30);
  a14=(a14*a20);
  a14=(a01*a14);
  a14=(a01*a14);
  a51=(a51-a14);
  a67=(a02*a67);
  a51=(a51-a67);
  if (res[0]!=0) res[0][30]=a51;
  a19=(a19/a25);
  a70=(a24*a70);
  a19=(a19-a70);
  a19=(a05*a19);
  a19=(a01*a19);
  a70=(a52*a19);
  a51=(a04*a68);
  a70=(a70-a51);
  a51=(a11*a66);
  a70=(a70-a51);
  a70=(a70+a26);
  a26=(a02*a27);
  a31=(a31-a26);
  a70=(a70+a31);
  if (res[0]!=0) res[0][31]=a70;
  a25=(a43/a25);
  a24=(a24*a29);
  a25=(a25-a24);
  a05=(a05*a25);
  a05=(a01*a05);
  a52=(a52*a05);
  a25=(a04*a34);
  a44=(a44-a25);
  a52=(a52-a44);
  a44=(a11*a41);
  a52=(a52-a44);
  a52=(a52+a16);
  a16=(a02*a40);
  a52=(a52-a16);
  if (res[0]!=0) res[0][32]=a52;
  a43=(a20*a43);
  if (res[0]!=0) res[0][33]=a43;
  a53=(a20*a53);
  a35=(a35-a53);
  if (res[0]!=0) res[0][34]=a35;
  a53=(a20*a54);
  a45=(a45-a53);
  if (res[0]!=0) res[0][35]=a45;
  if (res[0]!=0) res[0][36]=a49;
  if (res[0]!=0) res[0][37]=a59;
  if (res[0]!=0) res[0][38]=a69;
  if (res[0]!=0) res[0][39]=a70;
  a68=(a11*a68);
  a19=(a57*a19);
  a12=(a12+a19);
  a68=(a68+a12);
  a66=(a04*a66);
  a68=(a68-a66);
  a23=(a23/a50);
  a66=(a06*a32);
  a66=(a23-a66);
  a07=(a07*a33);
  a66=(a66+a07);
  a66=(a01*a66);
  a66=(a01*a66);
  a23=(a23/a50);
  a37=(a23*a37);
  a17=(a06*a17);
  a50=(a58+a58);
  a50=(a32*a50);
  a17=(a17-a50);
  a37=(a37+a17);
  a37=(a01*a37);
  a37=(a57*a37);
  a37=(a66-a37);
  a68=(a68-a37);
  a27=(a09*a27);
  a68=(a68-a27);
  if (res[0]!=0) res[0][40]=a68;
  a05=(a57*a05);
  a68=(a11*a34);
  a05=(a05-a68);
  a04=(a04*a41);
  a03=(a03-a04);
  a05=(a05+a03);
  a23=(a23*a22);
  a06=(a06*a21);
  a21=(a60+a60);
  a32=(a32*a21);
  a06=(a06-a32);
  a23=(a23+a06);
  a01=(a01*a23);
  a57=(a57*a01);
  a05=(a05+a57);
  a05=(a05+a65);
  a65=(a09*a40);
  a05=(a05-a65);
  if (res[0]!=0) res[0][41]=a05;
  a58=(a33*a58);
  a71=(a71-a58);
  if (res[0]!=0) res[0][42]=a71;
  a46=(a33*a46);
  if (res[0]!=0) res[0][43]=a46;
  a54=(a33*a54);
  a58=(a54+a48);
  if (res[0]!=0) res[0][44]=a58;
  if (res[0]!=0) res[0][45]=a18;
  if (res[0]!=0) res[0][46]=a62;
  if (res[0]!=0) res[0][47]=a00;
  if (res[0]!=0) res[0][48]=a52;
  if (res[0]!=0) res[0][49]=a05;
  a09=(a09*a34);
  a02=(a02*a41);
  a09=(a09-a02);
  a55=(a55*a01);
  a66=(a66-a55);
  a09=(a09-a66);
  a09=(a09-a14);
  a11=(a11*a40);
  a09=(a09-a11);
  if (res[0]!=0) res[0][50]=a09;
  a33=(a33*a60);
  a53=(a53-a33);
  if (res[0]!=0) res[0][51]=a53;
  a20=(a20*a60);
  a54=(a54+a20);
  a54=(-a54);
  if (res[0]!=0) res[0][52]=a54;
  a20=(a46+a43);
  if (res[0]!=0) res[0][53]=a20;
  if (res[0]!=0) res[0][54]=a08;
  if (res[0]!=0) res[0][55]=a38;
  if (res[0]!=0) res[0][56]=a48;
  if (res[0]!=0) res[0][57]=a43;
  if (res[0]!=0) res[0][58]=a71;
  if (res[0]!=0) res[0][59]=a53;
  if (res[0]!=0) res[0][60]=a42;
  if (res[0]!=0) res[0][61]=a13;
  if (res[0]!=0) res[0][62]=a63;
  if (res[0]!=0) res[0][63]=a35;
  if (res[0]!=0) res[0][64]=a46;
  if (res[0]!=0) res[0][65]=a54;
  if (res[0]!=0) res[0][66]=a28;
  if (res[0]!=0) res[0][67]=a15;
  if (res[0]!=0) res[0][68]=a64;
  if (res[0]!=0) res[0][69]=a45;
  if (res[0]!=0) res[0][70]=a58;
  if (res[0]!=0) res[0][71]=a20;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cylinder_orbit_mpc_cost_y_e_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cylinder_orbit_mpc_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_cylinder_orbit_mpc_cost_y_e_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cylinder_orbit_mpc_cost_y_e_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cylinder_orbit_mpc_cost_y_e_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cylinder_orbit_mpc_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cylinder_orbit_mpc_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_cost_y_e_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
