/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hover_mpc_qrdiag_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {179, 1, 1};
static const casadi_int casadi_s4[148] = 
  {19, 13, 0, 8, 16, 24, 31, 38,
  45, 52, 67, 80, 91, 106, 121, 132,
  6, 9, 10, 11, 12, 13, 14, 15,
  7, 9, 10, 11, 12, 13, 14, 15,
  8, 9, 10, 11, 12, 13, 14, 15,
  9, 10, 11, 12, 16, 17, 18, 9,
  10, 11, 12, 16, 17, 18, 9, 10,
  11, 12, 16, 17, 18, 9, 10, 11,
  12, 16, 17, 18, 0, 1, 2, 3,
  4, 5, 9, 10, 11, 12, 13, 14,
  15, 17, 18, 0, 1, 2, 3, 9,
  10, 11, 12, 13, 14, 15, 16, 18,
  4, 5, 9, 10, 11, 12, 13, 14,
  15, 16, 17, 0, 1, 2, 3, 4,
  5, 9, 10, 11, 12, 14, 15, 16,
  17, 18, 0, 1, 2, 3, 4, 5,
  9, 10, 11, 12, 13, 15, 16, 17,
  18, 0, 1, 2, 3, 4, 5, 13,
  14, 16, 17, 18};

/* hover_mpc_qrdiag_dyn_disc_phi_fun_jac:(i0[13],i1[6],i2[4],i3[179])->(o0[13],o1[19x13,132nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  casadi_real a72, a73, a74, a75, a76, a77, a78, a79, a80, a81, a82, a83;
  casadi_real a84, a85, a86, a87, a88, a89, a90, a91, a92, a93, a94, a95;
  casadi_real a96, a97, a98, a99;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.6000000000000000e-02;
  a02=1.;
  a03=2.;
  a04=arg[0]? arg[0][5] : 0;
  a05=arg[0]? arg[0][3] : 0;
  a06=casadi_sq(a05);
  a07=arg[0]? arg[0][4] : 0;
  a08=casadi_sq(a07);
  a06=(a06+a08);
  a08=casadi_sq(a04);
  a06=(a06+a08);
  a08=arg[0]? arg[0][6] : 0;
  a09=casadi_sq(a08);
  a06=(a06+a09);
  a09=9.9999999999999998e-13;
  a06=(a06+a09);
  a06=sqrt(a06);
  a10=(a04/a06);
  a11=casadi_sq(a10);
  a12=(a08/a06);
  a13=casadi_sq(a12);
  a14=(a11+a13);
  a14=(a03*a14);
  a14=(a02-a14);
  a15=arg[0]? arg[0][7] : 0;
  a16=(a14*a15);
  a17=(a07/a06);
  a18=(a17*a10);
  a19=(a05/a06);
  a20=(a12*a19);
  a21=(a18-a20);
  a21=(a03*a21);
  a22=arg[0]? arg[0][8] : 0;
  a23=(a21*a22);
  a16=(a16+a23);
  a23=(a17*a12);
  a24=(a10*a19);
  a25=(a23+a24);
  a25=(a03*a25);
  a26=arg[0]? arg[0][9] : 0;
  a27=(a25*a26);
  a16=(a16+a27);
  a16=(a01*a16);
  a00=(a00+a16);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a18=(a18+a20);
  a18=(a03*a18);
  a20=(a18*a15);
  a16=casadi_sq(a17);
  a13=(a16+a13);
  a13=(a03*a13);
  a13=(a02-a13);
  a27=(a13*a22);
  a20=(a20+a27);
  a27=(a10*a12);
  a28=(a17*a19);
  a29=(a27-a28);
  a29=(a03*a29);
  a30=(a29*a26);
  a20=(a20+a30);
  a20=(a01*a20);
  a00=(a00+a20);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a23=(a23-a24);
  a23=(a03*a23);
  a24=(a23*a15);
  a27=(a27+a28);
  a27=(a03*a27);
  a28=(a27*a22);
  a24=(a24+a28);
  a16=(a16+a11);
  a16=(a03*a16);
  a16=(a02-a16);
  a11=(a16*a26);
  a24=(a24+a11);
  a24=(a01*a24);
  a00=(a00+a24);
  if (res[0]!=0) res[0][2]=a00;
  a00=5.0000000000000000e-01;
  a24=arg[0]? arg[0][10] : 0;
  a11=(a24*a17);
  a28=arg[0]? arg[0][11] : 0;
  a20=(a28*a10);
  a11=(a11+a20);
  a20=arg[0]? arg[0][12] : 0;
  a30=(a20*a12);
  a11=(a11+a30);
  a11=(a00*a11);
  a11=(a01*a11);
  a05=(a05-a11);
  a11=casadi_sq(a05);
  a30=(a24*a19);
  a31=(a20*a10);
  a30=(a30+a31);
  a31=(a28*a12);
  a30=(a30-a31);
  a30=(a00*a30);
  a30=(a01*a30);
  a07=(a07+a30);
  a30=casadi_sq(a07);
  a11=(a11+a30);
  a30=(a28*a19);
  a31=(a20*a17);
  a30=(a30-a31);
  a31=(a24*a12);
  a30=(a30+a31);
  a30=(a00*a30);
  a30=(a01*a30);
  a04=(a04+a30);
  a30=casadi_sq(a04);
  a11=(a11+a30);
  a30=(a20*a19);
  a31=(a28*a17);
  a30=(a30+a31);
  a31=(a24*a10);
  a30=(a30-a31);
  a30=(a00*a30);
  a30=(a01*a30);
  a08=(a08+a30);
  a30=casadi_sq(a08);
  a11=(a11+a30);
  a11=(a11+a09);
  a11=sqrt(a11);
  a09=(a05/a11);
  if (res[0]!=0) res[0][3]=a09;
  a30=(a07/a11);
  if (res[0]!=0) res[0][4]=a30;
  a31=(a04/a11);
  if (res[0]!=0) res[0][5]=a31;
  a32=(a08/a11);
  if (res[0]!=0) res[0][6]=a32;
  a33=5.9880240204865237e-02;
  a34=7.0710670948028564e-01;
  a35=arg[1]? arg[1][0] : 0;
  a36=(a34*a35);
  a37=arg[1]? arg[1][1] : 0;
  a34=(a34*a37);
  a36=(a36+a34);
  a34=-7.0710670948028564e-01;
  a38=arg[1]? arg[1][2] : 0;
  a39=(a34*a38);
  a36=(a36+a39);
  a39=arg[1]? arg[1][3] : 0;
  a34=(a34*a39);
  a36=(a36+a34);
  a34=1.1920927533992653e-07;
  a40=arg[1]? arg[1][4] : 0;
  a41=(a34*a40);
  a36=(a36+a41);
  a41=arg[1]? arg[1][5] : 0;
  a34=(a34*a41);
  a36=(a36+a34);
  a34=1.2699999999999999e+01;
  a42=(a34*a22);
  a43=(a42*a20);
  a44=1.4570000000000000e+01;
  a45=(a44*a26);
  a46=(a45*a28);
  a43=(a43-a46);
  a46=4.0300000000000002e+00;
  a47=1.8180000000000000e+01;
  a48=casadi_fabs(a15);
  a48=(a47*a48);
  a46=(a46+a48);
  a48=(a46*a15);
  a43=(a43-a48);
  a48=1.1096936916300001e+02;
  a49=(a48*a23);
  a43=(a43+a49);
  a50=-1.0987199812889099e+02;
  a51=(a50*a23);
  a43=(a43+a51);
  a36=(a36+a43);
  a36=(a33*a36);
  a36=(a01*a36);
  a36=(a15+a36);
  if (res[0]!=0) res[0][7]=a36;
  a36=4.1841004518014153e-02;
  a43=7.0710682868957520e-01;
  a51=(a43*a35);
  a52=-7.0710682868957520e-01;
  a53=(a52*a37);
  a51=(a51+a53);
  a43=(a43*a38);
  a51=(a51+a43);
  a52=(a52*a39);
  a51=(a51+a52);
  a52=(a45*a24);
  a43=5.5000000000000000e+00;
  a53=(a43*a15);
  a54=(a53*a20);
  a52=(a52-a54);
  a54=6.2199999999999998e+00;
  a55=2.1660000000000000e+01;
  a56=casadi_fabs(a22);
  a56=(a55*a56);
  a54=(a54+a56);
  a56=(a54*a22);
  a52=(a52-a56);
  a56=(a48*a27);
  a52=(a52+a56);
  a57=(a50*a27);
  a52=(a52+a57);
  a51=(a51+a52);
  a51=(a36*a51);
  a51=(a01*a51);
  a51=(a22+a51);
  if (res[0]!=0) res[0][8]=a51;
  a51=3.8804812083873902e-02;
  a52=(a40+a41);
  a57=(a53*a28);
  a58=(a42*a24);
  a57=(a57-a58);
  a58=5.1799999999999997e+00;
  a59=3.6990000000000002e+01;
  a60=casadi_fabs(a26);
  a60=(a59*a60);
  a58=(a58+a60);
  a60=(a58*a26);
  a57=(a57-a60);
  a60=(a48*a16);
  a57=(a57+a60);
  a60=(a50*a16);
  a57=(a57+a60);
  a52=(a52+a57);
  a52=(a51*a52);
  a52=(a01*a52);
  a52=(a26+a52);
  if (res[0]!=0) res[0][9]=a52;
  a52=2.3598819594279892e+00;
  a57=5.1265239715576172e-02;
  a60=(a57*a35);
  a61=-5.1265239715576172e-02;
  a62=(a61*a37);
  a60=(a60+a62);
  a57=(a57*a38);
  a60=(a60+a57);
  a61=(a61*a39);
  a60=(a60+a61);
  a61=-1.1050006002187729e-01;
  a61=(a61*a40);
  a60=(a60+a61);
  a61=1.1050006002187729e-01;
  a61=(a61*a41);
  a60=(a60+a61);
  a61=(a42*a26);
  a57=(a45*a22);
  a61=(a61-a57);
  a57=1.2000000000000000e-01;
  a62=(a57*a28);
  a63=(a62*a20);
  a64=(a57*a20);
  a65=(a64*a28);
  a63=(a63-a65);
  a61=(a61+a63);
  a63=7.0000000000000007e-02;
  a65=1.5500000000000000e+00;
  a66=casadi_fabs(a24);
  a66=(a65*a66);
  a66=(a63+a66);
  a67=(a66*a24);
  a61=(a61-a67);
  a67=-1.0000000000000000e-02;
  a56=(a67*a56);
  a61=(a61-a56);
  a60=(a60+a61);
  a60=(a52*a60);
  a60=(a01*a60);
  a60=(a24+a60);
  if (res[0]!=0) res[0][10]=a60;
  a60=1.3404825968608334e+00;
  a61=-5.1265228539705276e-02;
  a56=(a61*a35);
  a61=(a61*a37);
  a56=(a56+a61);
  a61=5.1265228539705276e-02;
  a68=(a61*a38);
  a56=(a56+a68);
  a61=(a61*a39);
  a56=(a56+a61);
  a61=-2.5000013411045074e-03;
  a68=(a61*a40);
  a56=(a56+a68);
  a61=(a61*a41);
  a56=(a56+a61);
  a61=(a45*a15);
  a68=(a53*a26);
  a61=(a61-a68);
  a64=(a64*a24);
  a57=(a57*a24);
  a68=(a57*a20);
  a64=(a64-a68);
  a61=(a61+a64);
  a64=casadi_fabs(a28);
  a64=(a65*a64);
  a64=(a63+a64);
  a68=(a64*a28);
  a61=(a61-a68);
  a49=(a67*a49);
  a61=(a61+a49);
  a56=(a56+a61);
  a56=(a60*a56);
  a56=(a01*a56);
  a56=(a28+a56);
  if (res[0]!=0) res[0][11]=a56;
  a56=1.4349260903094676e+00;
  a61=1.6652362048625946e-01;
  a61=(a61*a35);
  a35=-1.6652362048625946e-01;
  a35=(a35*a37);
  a61=(a61+a35);
  a35=-1.7500892281532288e-01;
  a35=(a35*a38);
  a61=(a61+a35);
  a35=1.7500892281532288e-01;
  a35=(a35*a39);
  a61=(a61+a35);
  a35=1.3172631874169838e-08;
  a35=(a35*a40);
  a61=(a61+a35);
  a35=-1.3172631874169838e-08;
  a35=(a35*a41);
  a61=(a61+a35);
  a35=(a53*a22);
  a41=(a42*a15);
  a35=(a35-a41);
  a57=(a57*a28);
  a62=(a62*a24);
  a57=(a57-a62);
  a35=(a35+a57);
  a57=casadi_fabs(a20);
  a57=(a65*a57);
  a63=(a63+a57);
  a57=(a63*a20);
  a35=(a35-a57);
  a61=(a61+a35);
  a61=(a56*a61);
  a61=(a01*a61);
  a61=(a20+a61);
  if (res[0]!=0) res[0][12]=a61;
  if (res[1]!=0) res[1][0]=a02;
  a61=(a10+a10);
  a35=(a10/a06);
  a57=(a35*a19);
  a62=(a61*a57);
  a41=(a12+a12);
  a40=(a12/a06);
  a39=(a40*a19);
  a38=(a41*a39);
  a37=(a62+a38);
  a37=(a03*a37);
  a37=(a15*a37);
  a49=(a17/a06);
  a68=(a49*a19);
  a69=(a10*a68);
  a70=(a17*a57);
  a69=(a69+a70);
  a70=(1./a06);
  a06=(a19/a06);
  a71=(a06*a19);
  a71=(a70-a71);
  a72=(a12*a71);
  a73=(a19*a39);
  a72=(a72-a73);
  a73=(a69+a72);
  a73=(a03*a73);
  a73=(a22*a73);
  a37=(a37-a73);
  a73=(a10*a71);
  a74=(a19*a57);
  a73=(a73-a74);
  a74=(a12*a68);
  a75=(a17*a39);
  a74=(a74+a75);
  a75=(a73-a74);
  a75=(a03*a75);
  a75=(a26*a75);
  a37=(a37+a75);
  a37=(a01*a37);
  if (res[1]!=0) res[1][1]=a37;
  a37=(a35*a17);
  a75=(a61*a37);
  a76=(a40*a17);
  a77=(a41*a76);
  a78=(a75+a77);
  a78=(a03*a78);
  a78=(a15*a78);
  a79=(a49*a17);
  a79=(a70-a79);
  a80=(a10*a79);
  a81=(a17*a37);
  a80=(a80-a81);
  a81=(a19*a76);
  a82=(a06*a17);
  a83=(a12*a82);
  a81=(a81+a83);
  a83=(a80+a81);
  a83=(a03*a83);
  a83=(a22*a83);
  a78=(a78+a83);
  a83=(a12*a79);
  a84=(a17*a76);
  a83=(a83-a84);
  a84=(a19*a37);
  a85=(a10*a82);
  a84=(a84+a85);
  a85=(a83-a84);
  a85=(a03*a85);
  a85=(a26*a85);
  a78=(a78+a85);
  a78=(a01*a78);
  if (res[1]!=0) res[1][2]=a78;
  a78=(a35*a10);
  a78=(a70-a78);
  a85=(a17*a78);
  a86=(a49*a10);
  a87=(a10*a86);
  a85=(a85-a87);
  a87=(a40*a10);
  a88=(a19*a87);
  a89=(a06*a10);
  a90=(a12*a89);
  a88=(a88+a90);
  a90=(a85+a88);
  a90=(a03*a90);
  a90=(a22*a90);
  a91=(a61*a78);
  a92=(a41*a87);
  a93=(a91-a92);
  a93=(a03*a93);
  a93=(a15*a93);
  a90=(a90-a93);
  a93=(a19*a78);
  a94=(a10*a89);
  a93=(a93-a94);
  a94=(a12*a86);
  a95=(a17*a87);
  a94=(a94+a95);
  a95=(a93-a94);
  a95=(a03*a95);
  a95=(a26*a95);
  a90=(a90+a95);
  a90=(a01*a90);
  if (res[1]!=0) res[1][3]=a90;
  a40=(a40*a12);
  a70=(a70-a40);
  a40=(a17*a70);
  a49=(a49*a12);
  a90=(a12*a49);
  a40=(a40-a90);
  a35=(a35*a12);
  a90=(a19*a35);
  a06=(a06*a12);
  a95=(a10*a06);
  a90=(a90+a95);
  a95=(a40-a90);
  a95=(a03*a95);
  a95=(a26*a95);
  a41=(a41*a70);
  a61=(a61*a35);
  a96=(a41-a61);
  a96=(a03*a96);
  a96=(a15*a96);
  a97=(a10*a49);
  a98=(a17*a35);
  a97=(a97+a98);
  a98=(a19*a70);
  a99=(a12*a06);
  a98=(a98-a99);
  a99=(a97+a98);
  a99=(a03*a99);
  a99=(a22*a99);
  a96=(a96+a99);
  a95=(a95-a96);
  a95=(a01*a95);
  if (res[1]!=0) res[1][4]=a95;
  a14=(a01*a14);
  if (res[1]!=0) res[1][5]=a14;
  a21=(a01*a21);
  if (res[1]!=0) res[1][6]=a21;
  a25=(a01*a25);
  if (res[1]!=0) res[1][7]=a25;
  if (res[1]!=0) res[1][8]=a02;
  a72=(a72-a69);
  a72=(a03*a72);
  a72=(a15*a72);
  a69=(a17+a17);
  a25=(a69*a68);
  a38=(a25+a38);
  a38=(a03*a38);
  a38=(a22*a38);
  a72=(a72+a38);
  a38=(a12*a57);
  a21=(a10*a39);
  a38=(a38+a21);
  a21=(a17*a71);
  a14=(a19*a68);
  a21=(a21-a14);
  a14=(a38+a21);
  a14=(a03*a14);
  a14=(a26*a14);
  a72=(a72-a14);
  a72=(a01*a72);
  if (res[1]!=0) res[1][9]=a72;
  a80=(a80-a81);
  a80=(a03*a80);
  a80=(a15*a80);
  a81=(a69*a79);
  a77=(a81-a77);
  a77=(a03*a77);
  a77=(a22*a77);
  a80=(a80-a77);
  a77=(a12*a37);
  a72=(a10*a76);
  a77=(a77+a72);
  a72=(a19*a79);
  a14=(a17*a82);
  a72=(a72-a14);
  a14=(a77+a72);
  a14=(a03*a14);
  a14=(a26*a14);
  a80=(a80-a14);
  a80=(a01*a80);
  if (res[1]!=0) res[1][10]=a80;
  a85=(a85-a88);
  a85=(a03*a85);
  a85=(a15*a85);
  a88=(a69*a86);
  a92=(a88+a92);
  a92=(a03*a92);
  a92=(a22*a92);
  a85=(a85+a92);
  a92=(a12*a78);
  a80=(a10*a87);
  a92=(a92-a80);
  a80=(a19*a86);
  a14=(a17*a89);
  a80=(a80+a14);
  a14=(a92+a80);
  a14=(a03*a14);
  a14=(a26*a14);
  a85=(a85+a14);
  a85=(a01*a85);
  if (res[1]!=0) res[1][11]=a85;
  a98=(a98-a97);
  a98=(a03*a98);
  a98=(a15*a98);
  a69=(a69*a49);
  a41=(a41-a69);
  a41=(a03*a41);
  a41=(a22*a41);
  a98=(a98-a41);
  a41=(a10*a70);
  a97=(a12*a35);
  a41=(a41-a97);
  a97=(a19*a49);
  a85=(a17*a06);
  a97=(a97+a85);
  a85=(a41+a97);
  a85=(a03*a85);
  a85=(a26*a85);
  a98=(a98+a85);
  a98=(a01*a98);
  if (res[1]!=0) res[1][12]=a98;
  a18=(a01*a18);
  if (res[1]!=0) res[1][13]=a18;
  a13=(a01*a13);
  if (res[1]!=0) res[1][14]=a13;
  a29=(a01*a29);
  if (res[1]!=0) res[1][15]=a29;
  if (res[1]!=0) res[1][16]=a02;
  a21=(a21-a38);
  a21=(a03*a21);
  a38=(a22*a21);
  a74=(a74+a73);
  a74=(a03*a74);
  a73=(a15*a74);
  a38=(a38-a73);
  a25=(a25+a62);
  a25=(a03*a25);
  a62=(a26*a25);
  a38=(a38+a62);
  a38=(a01*a38);
  if (res[1]!=0) res[1][17]=a38;
  a83=(a83+a84);
  a83=(a03*a83);
  a84=(a15*a83);
  a72=(a72-a77);
  a72=(a03*a72);
  a77=(a22*a72);
  a84=(a84+a77);
  a81=(a81-a75);
  a81=(a03*a81);
  a75=(a26*a81);
  a84=(a84-a75);
  a84=(a01*a84);
  if (res[1]!=0) res[1][18]=a84;
  a92=(a92-a80);
  a92=(a03*a92);
  a80=(a22*a92);
  a94=(a94+a93);
  a94=(a03*a94);
  a93=(a15*a94);
  a80=(a80-a93);
  a91=(a91-a88);
  a91=(a03*a91);
  a88=(a26*a91);
  a80=(a80-a88);
  a80=(a01*a80);
  if (res[1]!=0) res[1][19]=a80;
  a40=(a40+a90);
  a40=(a03*a40);
  a90=(a15*a40);
  a41=(a41-a97);
  a41=(a03*a41);
  a97=(a22*a41);
  a90=(a90+a97);
  a69=(a69+a61);
  a03=(a03*a69);
  a69=(a26*a03);
  a90=(a90+a69);
  a90=(a01*a90);
  if (res[1]!=0) res[1][20]=a90;
  a23=(a01*a23);
  if (res[1]!=0) res[1][21]=a23;
  a27=(a01*a27);
  if (res[1]!=0) res[1][22]=a27;
  a16=(a01*a16);
  if (res[1]!=0) res[1][23]=a16;
  a16=(a24*a68);
  a27=(a28*a57);
  a16=(a16+a27);
  a27=(a20*a39);
  a16=(a16+a27);
  a16=(a00*a16);
  a16=(a01*a16);
  a16=(a02+a16);
  a27=(a16/a11);
  a09=(a09/a11);
  a05=(a05+a05);
  a16=(a05*a16);
  a07=(a07+a07);
  a23=(a24*a71);
  a90=(a20*a57);
  a23=(a23-a90);
  a90=(a28*a39);
  a23=(a23+a90);
  a23=(a00*a23);
  a23=(a01*a23);
  a90=(a07*a23);
  a16=(a16+a90);
  a04=(a04+a04);
  a90=(a28*a71);
  a69=(a20*a68);
  a90=(a90+a69);
  a39=(a24*a39);
  a90=(a90-a39);
  a90=(a00*a90);
  a90=(a01*a90);
  a39=(a04*a90);
  a16=(a16+a39);
  a08=(a08+a08);
  a71=(a20*a71);
  a68=(a28*a68);
  a71=(a71-a68);
  a57=(a24*a57);
  a71=(a71+a57);
  a71=(a00*a71);
  a71=(a01*a71);
  a57=(a08*a71);
  a16=(a16+a57);
  a57=(a11+a11);
  a16=(a16/a57);
  a68=(a09*a16);
  a27=(a27-a68);
  if (res[1]!=0) res[1][24]=a27;
  a27=(a24*a79);
  a68=(a28*a37);
  a27=(a27-a68);
  a68=(a20*a76);
  a27=(a27-a68);
  a27=(a00*a27);
  a27=(a01*a27);
  a68=(a27/a11);
  a39=(a28*a76);
  a69=(a24*a82);
  a61=(a20*a37);
  a69=(a69+a61);
  a39=(a39-a69);
  a39=(a00*a39);
  a39=(a01*a39);
  a39=(a02+a39);
  a69=(a07*a39);
  a27=(a05*a27);
  a69=(a69-a27);
  a27=(a28*a82);
  a61=(a20*a79);
  a27=(a27+a61);
  a76=(a24*a76);
  a27=(a27+a76);
  a27=(a00*a27);
  a27=(a01*a27);
  a76=(a04*a27);
  a69=(a69-a76);
  a79=(a28*a79);
  a82=(a20*a82);
  a79=(a79-a82);
  a37=(a24*a37);
  a79=(a79+a37);
  a79=(a00*a79);
  a79=(a01*a79);
  a37=(a08*a79);
  a69=(a69+a37);
  a69=(a69/a57);
  a37=(a09*a69);
  a68=(a68+a37);
  a68=(-a68);
  if (res[1]!=0) res[1][25]=a68;
  a68=(a28*a78);
  a37=(a24*a86);
  a68=(a68-a37);
  a37=(a20*a87);
  a68=(a68-a37);
  a68=(a00*a68);
  a68=(a01*a68);
  a37=(a68/a11);
  a82=(a20*a78);
  a76=(a24*a89);
  a82=(a82-a76);
  a76=(a28*a87);
  a82=(a82+a76);
  a82=(a00*a82);
  a82=(a01*a82);
  a76=(a07*a82);
  a68=(a05*a68);
  a76=(a76-a68);
  a68=(a20*a86);
  a61=(a28*a89);
  a68=(a68-a61);
  a87=(a24*a87);
  a68=(a68-a87);
  a68=(a00*a68);
  a68=(a01*a68);
  a68=(a02+a68);
  a87=(a04*a68);
  a76=(a76+a87);
  a89=(a20*a89);
  a86=(a28*a86);
  a89=(a89+a86);
  a78=(a24*a78);
  a89=(a89+a78);
  a89=(a00*a89);
  a89=(a01*a89);
  a78=(a08*a89);
  a76=(a76-a78);
  a76=(a76/a57);
  a78=(a09*a76);
  a37=(a37+a78);
  a37=(-a37);
  if (res[1]!=0) res[1][26]=a37;
  a37=(a20*a70);
  a78=(a24*a49);
  a86=(a28*a35);
  a78=(a78+a86);
  a37=(a37-a78);
  a37=(a00*a37);
  a37=(a01*a37);
  a78=(a37/a11);
  a86=(a20*a49);
  a87=(a28*a06);
  a86=(a86-a87);
  a87=(a24*a70);
  a86=(a86+a87);
  a86=(a00*a86);
  a86=(a01*a86);
  a87=(a04*a86);
  a37=(a05*a37);
  a61=(a24*a06);
  a97=(a20*a35);
  a61=(a61+a97);
  a70=(a28*a70);
  a61=(a61+a70);
  a61=(a00*a61);
  a61=(a01*a61);
  a70=(a07*a61);
  a37=(a37+a70);
  a87=(a87-a37);
  a35=(a24*a35);
  a06=(a20*a06);
  a49=(a28*a49);
  a06=(a06+a49);
  a35=(a35-a06);
  a35=(a00*a35);
  a35=(a01*a35);
  a35=(a02+a35);
  a06=(a08*a35);
  a87=(a87+a06);
  a87=(a87/a57);
  a06=(a09*a87);
  a78=(a78+a06);
  a78=(-a78);
  if (res[1]!=0) res[1][27]=a78;
  a17=(a00*a17);
  a17=(a01*a17);
  a78=(a17/a11);
  a19=(a00*a19);
  a19=(a01*a19);
  a06=(a07*a19);
  a49=(a05*a17);
  a06=(a06-a49);
  a12=(a00*a12);
  a12=(a01*a12);
  a49=(a04*a12);
  a06=(a06+a49);
  a00=(a00*a10);
  a00=(a01*a00);
  a10=(a08*a00);
  a06=(a06-a10);
  a06=(a06/a57);
  a10=(a09*a06);
  a10=(a78+a10);
  a10=(-a10);
  if (res[1]!=0) res[1][28]=a10;
  a10=(a00/a11);
  a49=(a04*a19);
  a37=(a05*a00);
  a70=(a07*a12);
  a37=(a37+a70);
  a49=(a49-a37);
  a37=(a08*a17);
  a49=(a49+a37);
  a49=(a49/a57);
  a37=(a09*a49);
  a37=(a10+a37);
  a37=(-a37);
  if (res[1]!=0) res[1][29]=a37;
  a37=(a12/a11);
  a07=(a07*a00);
  a05=(a05*a12);
  a07=(a07-a05);
  a04=(a04*a17);
  a07=(a07-a04);
  a08=(a08*a19);
  a07=(a07+a08);
  a07=(a07/a57);
  a09=(a09*a07);
  a09=(a37+a09);
  a09=(-a09);
  if (res[1]!=0) res[1][30]=a09;
  a23=(a23/a11);
  a30=(a30/a11);
  a09=(a30*a16);
  a23=(a23-a09);
  if (res[1]!=0) res[1][31]=a23;
  a39=(a39/a11);
  a23=(a30*a69);
  a39=(a39-a23);
  if (res[1]!=0) res[1][32]=a39;
  a82=(a82/a11);
  a39=(a30*a76);
  a82=(a82-a39);
  if (res[1]!=0) res[1][33]=a82;
  a61=(a61/a11);
  a82=(a30*a87);
  a61=(a61+a82);
  a61=(-a61);
  if (res[1]!=0) res[1][34]=a61;
  a19=(a19/a11);
  a61=(a30*a06);
  a61=(a19-a61);
  if (res[1]!=0) res[1][35]=a61;
  a61=(a30*a49);
  a61=(a37+a61);
  a61=(-a61);
  if (res[1]!=0) res[1][36]=a61;
  a30=(a30*a07);
  a30=(a10-a30);
  if (res[1]!=0) res[1][37]=a30;
  a90=(a90/a11);
  a31=(a31/a11);
  a30=(a31*a16);
  a90=(a90-a30);
  if (res[1]!=0) res[1][38]=a90;
  a27=(a27/a11);
  a90=(a31*a69);
  a27=(a27+a90);
  a27=(-a27);
  if (res[1]!=0) res[1][39]=a27;
  a68=(a68/a11);
  a27=(a31*a76);
  a68=(a68-a27);
  if (res[1]!=0) res[1][40]=a68;
  a86=(a86/a11);
  a68=(a31*a87);
  a86=(a86-a68);
  if (res[1]!=0) res[1][41]=a86;
  a86=(a31*a06);
  a37=(a37-a86);
  if (res[1]!=0) res[1][42]=a37;
  a37=(a31*a49);
  a37=(a19-a37);
  if (res[1]!=0) res[1][43]=a37;
  a31=(a31*a07);
  a31=(a78+a31);
  a31=(-a31);
  if (res[1]!=0) res[1][44]=a31;
  a71=(a71/a11);
  a32=(a32/a11);
  a16=(a32*a16);
  a71=(a71-a16);
  if (res[1]!=0) res[1][45]=a71;
  a79=(a79/a11);
  a69=(a32*a69);
  a79=(a79-a69);
  if (res[1]!=0) res[1][46]=a79;
  a89=(a89/a11);
  a76=(a32*a76);
  a89=(a89+a76);
  a89=(-a89);
  if (res[1]!=0) res[1][47]=a89;
  a35=(a35/a11);
  a87=(a32*a87);
  a35=(a35-a87);
  if (res[1]!=0) res[1][48]=a35;
  a06=(a32*a06);
  a10=(a10+a06);
  a10=(-a10);
  if (res[1]!=0) res[1][49]=a10;
  a49=(a32*a49);
  a78=(a78-a49);
  if (res[1]!=0) res[1][50]=a78;
  a32=(a32*a07);
  a19=(a19-a32);
  if (res[1]!=0) res[1][51]=a19;
  a19=6.7746751382642180e-04;
  if (res[1]!=0) res[1][52]=a19;
  if (res[1]!=0) res[1][53]=a19;
  a19=-6.7746751382642180e-04;
  if (res[1]!=0) res[1][54]=a19;
  if (res[1]!=0) res[1][55]=a19;
  a19=1.1421248067204351e-10;
  if (res[1]!=0) res[1][56]=a19;
  if (res[1]!=0) res[1][57]=a19;
  a19=(a48*a74);
  a74=(a50*a74);
  a74=(a19+a74);
  a74=(a33*a74);
  a74=(a01*a74);
  a74=(-a74);
  if (res[1]!=0) res[1][58]=a74;
  a74=(a48*a83);
  a83=(a50*a83);
  a83=(a74+a83);
  a83=(a33*a83);
  a83=(a01*a83);
  if (res[1]!=0) res[1][59]=a83;
  a83=(a48*a94);
  a94=(a50*a94);
  a94=(a83+a94);
  a94=(a33*a94);
  a94=(a01*a94);
  a94=(-a94);
  if (res[1]!=0) res[1][60]=a94;
  a94=(a48*a40);
  a40=(a50*a40);
  a40=(a94+a40);
  a40=(a33*a40);
  a40=(a01*a40);
  if (res[1]!=0) res[1][61]=a40;
  a40=casadi_sign(a15);
  a47=(a47*a40);
  a47=(a15*a47);
  a47=(a47+a46);
  a47=(a33*a47);
  a47=(a01*a47);
  a47=(a02-a47);
  if (res[1]!=0) res[1][62]=a47;
  a47=(a34*a20);
  a47=(a33*a47);
  a47=(a01*a47);
  if (res[1]!=0) res[1][63]=a47;
  a47=(a44*a28);
  a47=(a33*a47);
  a47=(a01*a47);
  a47=(-a47);
  if (res[1]!=0) res[1][64]=a47;
  a47=(a33*a45);
  a47=(a01*a47);
  a47=(-a47);
  if (res[1]!=0) res[1][65]=a47;
  a33=(a33*a42);
  a33=(a01*a33);
  if (res[1]!=0) res[1][66]=a33;
  a33=4.7337696022270681e-04;
  if (res[1]!=0) res[1][67]=a33;
  a47=-4.7337696022270681e-04;
  if (res[1]!=0) res[1][68]=a47;
  if (res[1]!=0) res[1][69]=a33;
  if (res[1]!=0) res[1][70]=a47;
  a47=(a48*a21);
  a21=(a50*a21);
  a21=(a47+a21);
  a21=(a36*a21);
  a21=(a01*a21);
  if (res[1]!=0) res[1][71]=a21;
  a21=(a48*a72);
  a72=(a50*a72);
  a72=(a21+a72);
  a72=(a36*a72);
  a72=(a01*a72);
  if (res[1]!=0) res[1][72]=a72;
  a72=(a48*a92);
  a92=(a50*a92);
  a92=(a72+a92);
  a92=(a36*a92);
  a92=(a01*a92);
  if (res[1]!=0) res[1][73]=a92;
  a92=(a48*a41);
  a41=(a50*a41);
  a41=(a92+a41);
  a41=(a36*a41);
  a41=(a01*a41);
  if (res[1]!=0) res[1][74]=a41;
  a41=(a43*a20);
  a41=(a36*a41);
  a41=(a01*a41);
  a41=(-a41);
  if (res[1]!=0) res[1][75]=a41;
  a41=casadi_sign(a22);
  a55=(a55*a41);
  a55=(a22*a55);
  a55=(a55+a54);
  a55=(a36*a55);
  a55=(a01*a55);
  a55=(a02-a55);
  if (res[1]!=0) res[1][76]=a55;
  a55=(a44*a24);
  a55=(a36*a55);
  a55=(a01*a55);
  if (res[1]!=0) res[1][77]=a55;
  a55=(a36*a45);
  a55=(a01*a55);
  if (res[1]!=0) res[1][78]=a55;
  a36=(a36*a53);
  a36=(a01*a36);
  a36=(-a36);
  if (res[1]!=0) res[1][79]=a36;
  a36=6.2087699334198248e-04;
  if (res[1]!=0) res[1][80]=a36;
  if (res[1]!=0) res[1][81]=a36;
  a36=(a48*a25);
  a25=(a50*a25);
  a36=(a36+a25);
  a36=(a51*a36);
  a36=(a01*a36);
  if (res[1]!=0) res[1][82]=a36;
  a36=(a48*a81);
  a81=(a50*a81);
  a36=(a36+a81);
  a36=(a51*a36);
  a36=(a01*a36);
  a36=(-a36);
  if (res[1]!=0) res[1][83]=a36;
  a36=(a48*a91);
  a91=(a50*a91);
  a36=(a36+a91);
  a36=(a51*a36);
  a36=(a01*a36);
  a36=(-a36);
  if (res[1]!=0) res[1][84]=a36;
  a48=(a48*a03);
  a50=(a50*a03);
  a48=(a48+a50);
  a48=(a51*a48);
  a48=(a01*a48);
  if (res[1]!=0) res[1][85]=a48;
  a48=(a43*a28);
  a48=(a51*a48);
  a48=(a01*a48);
  if (res[1]!=0) res[1][86]=a48;
  a48=(a34*a24);
  a48=(a51*a48);
  a48=(a01*a48);
  a48=(-a48);
  if (res[1]!=0) res[1][87]=a48;
  a48=casadi_sign(a26);
  a59=(a59*a48);
  a59=(a26*a59);
  a59=(a59+a58);
  a59=(a51*a59);
  a59=(a01*a59);
  a59=(a02-a59);
  if (res[1]!=0) res[1][88]=a59;
  a59=(a51*a42);
  a59=(a01*a59);
  a59=(-a59);
  if (res[1]!=0) res[1][89]=a59;
  a51=(a51*a53);
  a51=(a01*a51);
  if (res[1]!=0) res[1][90]=a51;
  a51=1.9356786296086314e-03;
  if (res[1]!=0) res[1][91]=a51;
  a59=-1.9356786296086314e-03;
  if (res[1]!=0) res[1][92]=a59;
  if (res[1]!=0) res[1][93]=a51;
  if (res[1]!=0) res[1][94]=a59;
  a59=-4.1722735705814109e-03;
  if (res[1]!=0) res[1][95]=a59;
  a59=4.1722735705814109e-03;
  if (res[1]!=0) res[1][96]=a59;
  a47=(a67*a47);
  a47=(a52*a47);
  a47=(a01*a47);
  a47=(-a47);
  if (res[1]!=0) res[1][97]=a47;
  a21=(a67*a21);
  a21=(a52*a21);
  a21=(a01*a21);
  a21=(-a21);
  if (res[1]!=0) res[1][98]=a21;
  a72=(a67*a72);
  a72=(a52*a72);
  a72=(a01*a72);
  a72=(-a72);
  if (res[1]!=0) res[1][99]=a72;
  a92=(a67*a92);
  a92=(a52*a92);
  a92=(a01*a92);
  a92=(-a92);
  if (res[1]!=0) res[1][100]=a92;
  a92=(a34*a26);
  a92=(a92-a45);
  a92=(a52*a92);
  a92=(a01*a92);
  if (res[1]!=0) res[1][101]=a92;
  a92=(a44*a22);
  a92=(a42-a92);
  a92=(a52*a92);
  a92=(a01*a92);
  if (res[1]!=0) res[1][102]=a92;
  a92=casadi_sign(a24);
  a92=(a65*a92);
  a24=(a24*a92);
  a24=(a24+a66);
  a52=(a52*a24);
  a52=(a01*a52);
  a52=(a02-a52);
  if (res[1]!=0) res[1][103]=a52;
  a52=0.;
  if (res[1]!=0) res[1][104]=a52;
  if (res[1]!=0) res[1][105]=a52;
  a24=-1.0995223469050918e-03;
  if (res[1]!=0) res[1][106]=a24;
  if (res[1]!=0) res[1][107]=a24;
  a24=1.0995223469050918e-03;
  if (res[1]!=0) res[1][108]=a24;
  if (res[1]!=0) res[1][109]=a24;
  a24=-5.3619332638069381e-05;
  if (res[1]!=0) res[1][110]=a24;
  if (res[1]!=0) res[1][111]=a24;
  a19=(a67*a19);
  a19=(a60*a19);
  a19=(a01*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][112]=a19;
  a74=(a67*a74);
  a74=(a60*a74);
  a74=(a01*a74);
  if (res[1]!=0) res[1][113]=a74;
  a83=(a67*a83);
  a83=(a60*a83);
  a83=(a01*a83);
  a83=(-a83);
  if (res[1]!=0) res[1][114]=a83;
  a67=(a67*a94);
  a67=(a60*a67);
  a67=(a01*a67);
  if (res[1]!=0) res[1][115]=a67;
  a26=(a43*a26);
  a45=(a45-a26);
  a45=(a60*a45);
  a45=(a01*a45);
  if (res[1]!=0) res[1][116]=a45;
  a44=(a44*a15);
  a44=(a44-a53);
  a44=(a60*a44);
  a44=(a01*a44);
  if (res[1]!=0) res[1][117]=a44;
  if (res[1]!=0) res[1][118]=a52;
  a44=casadi_sign(a28);
  a44=(a65*a44);
  a28=(a28*a44);
  a28=(a28+a64);
  a60=(a60*a28);
  a60=(a01*a60);
  a60=(a02-a60);
  if (res[1]!=0) res[1][119]=a60;
  if (res[1]!=0) res[1][120]=a52;
  a60=3.8231854030164139e-03;
  if (res[1]!=0) res[1][121]=a60;
  a60=-3.8231854030164139e-03;
  if (res[1]!=0) res[1][122]=a60;
  a60=-4.0179979101546024e-03;
  if (res[1]!=0) res[1][123]=a60;
  a60=4.0179979101546024e-03;
  if (res[1]!=0) res[1][124]=a60;
  a60=3.0242805046861442e-10;
  if (res[1]!=0) res[1][125]=a60;
  a60=-3.0242805046861442e-10;
  if (res[1]!=0) res[1][126]=a60;
  a43=(a43*a22);
  a43=(a43-a42);
  a43=(a56*a43);
  a43=(a01*a43);
  if (res[1]!=0) res[1][127]=a43;
  a34=(a34*a15);
  a53=(a53-a34);
  a53=(a56*a53);
  a53=(a01*a53);
  if (res[1]!=0) res[1][128]=a53;
  if (res[1]!=0) res[1][129]=a52;
  if (res[1]!=0) res[1][130]=a52;
  a52=casadi_sign(a20);
  a65=(a65*a52);
  a20=(a20*a65);
  a20=(a20+a63);
  a56=(a56*a20);
  a01=(a01*a56);
  a02=(a02-a01);
  if (res[1]!=0) res[1][131]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_dyn_disc_phi_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real hover_mpc_qrdiag_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
