/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hover_mpc_qrdiag_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {179, 1, 1};

/* hover_mpc_qrdiag_dyn_disc_phi_fun:(i0[13],i1[6],i2[4],i3[179])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.6000000000000000e-02;
  a02=1.;
  a03=2.;
  a04=arg[0]? arg[0][5] : 0;
  a05=arg[0]? arg[0][3] : 0;
  a06=casadi_sq(a05);
  a07=arg[0]? arg[0][4] : 0;
  a08=casadi_sq(a07);
  a06=(a06+a08);
  a08=casadi_sq(a04);
  a06=(a06+a08);
  a08=arg[0]? arg[0][6] : 0;
  a09=casadi_sq(a08);
  a06=(a06+a09);
  a09=9.9999999999999998e-13;
  a06=(a06+a09);
  a06=sqrt(a06);
  a10=(a04/a06);
  a11=casadi_sq(a10);
  a12=(a08/a06);
  a13=casadi_sq(a12);
  a14=(a11+a13);
  a14=(a03*a14);
  a14=(a02-a14);
  a15=arg[0]? arg[0][7] : 0;
  a14=(a14*a15);
  a16=(a07/a06);
  a17=(a16*a10);
  a06=(a05/a06);
  a18=(a12*a06);
  a19=(a17-a18);
  a19=(a03*a19);
  a20=arg[0]? arg[0][8] : 0;
  a19=(a19*a20);
  a14=(a14+a19);
  a19=(a16*a12);
  a21=(a10*a06);
  a22=(a19+a21);
  a22=(a03*a22);
  a23=arg[0]? arg[0][9] : 0;
  a22=(a22*a23);
  a14=(a14+a22);
  a14=(a01*a14);
  a00=(a00+a14);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a17=(a17+a18);
  a17=(a03*a17);
  a17=(a17*a15);
  a18=casadi_sq(a16);
  a13=(a18+a13);
  a13=(a03*a13);
  a13=(a02-a13);
  a13=(a13*a20);
  a17=(a17+a13);
  a13=(a10*a12);
  a14=(a16*a06);
  a22=(a13-a14);
  a22=(a03*a22);
  a22=(a22*a23);
  a17=(a17+a22);
  a17=(a01*a17);
  a00=(a00+a17);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a19=(a19-a21);
  a19=(a03*a19);
  a21=(a19*a15);
  a13=(a13+a14);
  a13=(a03*a13);
  a14=(a13*a20);
  a21=(a21+a14);
  a18=(a18+a11);
  a03=(a03*a18);
  a02=(a02-a03);
  a03=(a02*a23);
  a21=(a21+a03);
  a21=(a01*a21);
  a00=(a00+a21);
  if (res[0]!=0) res[0][2]=a00;
  a00=5.0000000000000000e-01;
  a21=arg[0]? arg[0][10] : 0;
  a03=(a21*a16);
  a18=arg[0]? arg[0][11] : 0;
  a11=(a18*a10);
  a03=(a03+a11);
  a11=arg[0]? arg[0][12] : 0;
  a14=(a11*a12);
  a03=(a03+a14);
  a03=(a00*a03);
  a03=(a01*a03);
  a05=(a05-a03);
  a03=casadi_sq(a05);
  a14=(a21*a06);
  a17=(a11*a10);
  a14=(a14+a17);
  a17=(a18*a12);
  a14=(a14-a17);
  a14=(a00*a14);
  a14=(a01*a14);
  a07=(a07+a14);
  a14=casadi_sq(a07);
  a03=(a03+a14);
  a14=(a18*a06);
  a17=(a11*a16);
  a14=(a14-a17);
  a12=(a21*a12);
  a14=(a14+a12);
  a14=(a00*a14);
  a14=(a01*a14);
  a04=(a04+a14);
  a14=casadi_sq(a04);
  a03=(a03+a14);
  a06=(a11*a06);
  a16=(a18*a16);
  a06=(a06+a16);
  a10=(a21*a10);
  a06=(a06-a10);
  a00=(a00*a06);
  a00=(a01*a00);
  a08=(a08+a00);
  a00=casadi_sq(a08);
  a03=(a03+a00);
  a03=(a03+a09);
  a03=sqrt(a03);
  a05=(a05/a03);
  if (res[0]!=0) res[0][3]=a05;
  a07=(a07/a03);
  if (res[0]!=0) res[0][4]=a07;
  a04=(a04/a03);
  if (res[0]!=0) res[0][5]=a04;
  a08=(a08/a03);
  if (res[0]!=0) res[0][6]=a08;
  a08=5.9880240204865237e-02;
  a03=7.0710670948028564e-01;
  a04=arg[1]? arg[1][0] : 0;
  a07=(a03*a04);
  a05=arg[1]? arg[1][1] : 0;
  a03=(a03*a05);
  a07=(a07+a03);
  a03=-7.0710670948028564e-01;
  a09=arg[1]? arg[1][2] : 0;
  a00=(a03*a09);
  a07=(a07+a00);
  a00=arg[1]? arg[1][3] : 0;
  a03=(a03*a00);
  a07=(a07+a03);
  a03=1.1920927533992653e-07;
  a06=arg[1]? arg[1][4] : 0;
  a10=(a03*a06);
  a07=(a07+a10);
  a10=arg[1]? arg[1][5] : 0;
  a03=(a03*a10);
  a07=(a07+a03);
  a03=1.2699999999999999e+01;
  a03=(a03*a20);
  a16=(a03*a11);
  a14=1.4570000000000000e+01;
  a14=(a14*a23);
  a12=(a14*a18);
  a16=(a16-a12);
  a12=4.0300000000000002e+00;
  a17=1.8180000000000000e+01;
  a22=casadi_fabs(a15);
  a17=(a17*a22);
  a12=(a12+a17);
  a12=(a12*a15);
  a16=(a16-a12);
  a12=1.1096936916300001e+02;
  a17=(a12*a19);
  a16=(a16+a17);
  a22=-1.0987199812889099e+02;
  a19=(a22*a19);
  a16=(a16+a19);
  a07=(a07+a16);
  a08=(a08*a07);
  a08=(a01*a08);
  a08=(a15+a08);
  if (res[0]!=0) res[0][7]=a08;
  a08=4.1841004518014153e-02;
  a07=7.0710682868957520e-01;
  a16=(a07*a04);
  a19=-7.0710682868957520e-01;
  a24=(a19*a05);
  a16=(a16+a24);
  a07=(a07*a09);
  a16=(a16+a07);
  a19=(a19*a00);
  a16=(a16+a19);
  a19=(a14*a21);
  a07=5.5000000000000000e+00;
  a07=(a07*a15);
  a24=(a07*a11);
  a19=(a19-a24);
  a24=6.2199999999999998e+00;
  a25=2.1660000000000000e+01;
  a26=casadi_fabs(a20);
  a25=(a25*a26);
  a24=(a24+a25);
  a24=(a24*a20);
  a19=(a19-a24);
  a24=(a12*a13);
  a19=(a19+a24);
  a13=(a22*a13);
  a19=(a19+a13);
  a16=(a16+a19);
  a08=(a08*a16);
  a08=(a01*a08);
  a08=(a20+a08);
  if (res[0]!=0) res[0][8]=a08;
  a08=3.8804812083873902e-02;
  a16=(a06+a10);
  a19=(a07*a18);
  a13=(a03*a21);
  a19=(a19-a13);
  a13=5.1799999999999997e+00;
  a25=3.6990000000000002e+01;
  a26=casadi_fabs(a23);
  a25=(a25*a26);
  a13=(a13+a25);
  a13=(a13*a23);
  a19=(a19-a13);
  a12=(a12*a02);
  a19=(a19+a12);
  a22=(a22*a02);
  a19=(a19+a22);
  a16=(a16+a19);
  a08=(a08*a16);
  a08=(a01*a08);
  a08=(a23+a08);
  if (res[0]!=0) res[0][9]=a08;
  a08=2.3598819594279892e+00;
  a16=5.1265239715576172e-02;
  a19=(a16*a04);
  a22=-5.1265239715576172e-02;
  a02=(a22*a05);
  a19=(a19+a02);
  a16=(a16*a09);
  a19=(a19+a16);
  a22=(a22*a00);
  a19=(a19+a22);
  a22=-1.1050006002187729e-01;
  a22=(a22*a06);
  a19=(a19+a22);
  a22=1.1050006002187729e-01;
  a22=(a22*a10);
  a19=(a19+a22);
  a22=(a03*a23);
  a16=(a14*a20);
  a22=(a22-a16);
  a16=1.2000000000000000e-01;
  a02=(a16*a18);
  a12=(a02*a11);
  a13=(a16*a11);
  a25=(a13*a18);
  a12=(a12-a25);
  a22=(a22+a12);
  a12=7.0000000000000007e-02;
  a25=1.5500000000000000e+00;
  a26=casadi_fabs(a21);
  a26=(a25*a26);
  a26=(a12+a26);
  a26=(a26*a21);
  a22=(a22-a26);
  a26=-1.0000000000000000e-02;
  a24=(a26*a24);
  a22=(a22-a24);
  a19=(a19+a22);
  a08=(a08*a19);
  a08=(a01*a08);
  a08=(a21+a08);
  if (res[0]!=0) res[0][10]=a08;
  a08=1.3404825968608334e+00;
  a19=-5.1265228539705276e-02;
  a22=(a19*a04);
  a19=(a19*a05);
  a22=(a22+a19);
  a19=5.1265228539705276e-02;
  a24=(a19*a09);
  a22=(a22+a24);
  a19=(a19*a00);
  a22=(a22+a19);
  a19=-2.5000013411045074e-03;
  a24=(a19*a06);
  a22=(a22+a24);
  a19=(a19*a10);
  a22=(a22+a19);
  a14=(a14*a15);
  a23=(a07*a23);
  a14=(a14-a23);
  a13=(a13*a21);
  a16=(a16*a21);
  a23=(a16*a11);
  a13=(a13-a23);
  a14=(a14+a13);
  a13=casadi_fabs(a18);
  a13=(a25*a13);
  a13=(a12+a13);
  a13=(a13*a18);
  a14=(a14-a13);
  a26=(a26*a17);
  a14=(a14+a26);
  a22=(a22+a14);
  a08=(a08*a22);
  a08=(a01*a08);
  a08=(a18+a08);
  if (res[0]!=0) res[0][11]=a08;
  a08=1.4349260903094676e+00;
  a22=1.6652362048625946e-01;
  a22=(a22*a04);
  a04=-1.6652362048625946e-01;
  a04=(a04*a05);
  a22=(a22+a04);
  a04=-1.7500892281532288e-01;
  a04=(a04*a09);
  a22=(a22+a04);
  a04=1.7500892281532288e-01;
  a04=(a04*a00);
  a22=(a22+a04);
  a04=1.3172631874169838e-08;
  a04=(a04*a06);
  a22=(a22+a04);
  a04=-1.3172631874169838e-08;
  a04=(a04*a10);
  a22=(a22+a04);
  a07=(a07*a20);
  a03=(a03*a15);
  a07=(a07-a03);
  a16=(a16*a18);
  a02=(a02*a21);
  a16=(a16-a02);
  a07=(a07+a16);
  a16=casadi_fabs(a11);
  a25=(a25*a16);
  a12=(a12+a25);
  a12=(a12*a11);
  a07=(a07-a12);
  a22=(a22+a07);
  a08=(a08*a22);
  a01=(a01*a08);
  a11=(a11+a01);
  if (res[0]!=0) res[0][12]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_dyn_disc_phi_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hover_mpc_qrdiag_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
