/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {21, 1, 1};

/* bluerov_mpc_expl_vde_adj:(i0[13],i1[13],i2[8],i3[0])->(o0[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=5.0000000000000000e-01;
  a01=arg[0]? arg[0][12] : 0;
  a01=(a00*a01);
  a02=arg[1]? arg[1][6] : 0;
  a03=(a01*a02);
  a04=arg[0]? arg[0][11] : 0;
  a04=(a00*a04);
  a05=arg[1]? arg[1][5] : 0;
  a06=(a04*a05);
  a03=(a03+a06);
  a06=arg[0]? arg[0][10] : 0;
  a06=(a00*a06);
  a07=arg[1]? arg[1][4] : 0;
  a08=(a06*a07);
  a03=(a03+a08);
  a08=arg[0]? arg[0][4] : 0;
  a09=2.;
  a10=-1.1016629550933838e+02;
  a11=8.9047198643149833e-02;
  a12=arg[1]? arg[1][8] : 0;
  a12=(a11*a12);
  a13=(a10*a12);
  a14=1.1016629550933838e+02;
  a15=(a14*a12);
  a13=(a13+a15);
  a15=arg[0]? arg[0][8] : 0;
  a16=arg[1]? arg[1][2] : 0;
  a17=(a15*a16);
  a13=(a13+a17);
  a13=(a09*a13);
  a17=(a08*a13);
  a03=(a03+a17);
  a17=arg[0]? arg[0][5] : 0;
  a18=arg[1]? arg[1][7] : 0;
  a18=(a11*a18);
  a19=(a10*a18);
  a20=(a14*a18);
  a19=(a19+a20);
  a20=arg[0]? arg[0][7] : 0;
  a21=(a20*a16);
  a19=(a19+a21);
  a19=(a09*a19);
  a21=(a17*a19);
  a03=(a03-a21);
  a21=arg[0]? arg[0][9] : 0;
  a22=arg[1]? arg[1][1] : 0;
  a23=(a21*a22);
  a23=(a09*a23);
  a24=(a08*a23);
  a03=(a03-a24);
  a24=arg[0]? arg[0][6] : 0;
  a25=(a20*a22);
  a25=(a09*a25);
  a26=(a24*a25);
  a03=(a03+a26);
  a26=arg[1]? arg[1][0] : 0;
  a27=(a21*a26);
  a27=(a09*a27);
  a28=(a17*a27);
  a03=(a03+a28);
  a28=(a15*a26);
  a28=(a09*a28);
  a29=(a24*a28);
  a03=(a03-a29);
  if (res[0]!=0) res[0][3]=a03;
  a03=(a04*a02);
  a29=(a01*a05);
  a03=(a03-a29);
  a29=arg[1]? arg[1][3] : 0;
  a30=(a06*a29);
  a03=(a03-a30);
  a30=(a08+a08);
  a31=arg[1]? arg[1][9] : 0;
  a11=(a11*a31);
  a10=(a10*a11);
  a14=(a14*a11);
  a10=(a10+a14);
  a21=(a21*a16);
  a10=(a10+a21);
  a10=(a09*a10);
  a21=(a30*a10);
  a03=(a03-a21);
  a21=arg[0]? arg[0][3] : 0;
  a14=(a21*a13);
  a03=(a03+a14);
  a14=(a24*a19);
  a03=(a03+a14);
  a14=(a21*a23);
  a03=(a03-a14);
  a15=(a15*a22);
  a15=(a09*a15);
  a30=(a30*a15);
  a03=(a03-a30);
  a30=(a17*a25);
  a03=(a03+a30);
  a30=(a24*a27);
  a03=(a03+a30);
  a30=(a17*a28);
  a03=(a03+a30);
  if (res[0]!=0) res[0][4]=a03;
  a03=(a01*a07);
  a30=(a06*a02);
  a03=(a03-a30);
  a30=(a04*a29);
  a03=(a03-a30);
  a30=(a17+a17);
  a10=(a30*a10);
  a03=(a03-a10);
  a10=(a24*a13);
  a03=(a03+a10);
  a10=(a21*a19);
  a03=(a03-a10);
  a10=(a24*a23);
  a03=(a03+a10);
  a10=(a08*a25);
  a03=(a03+a10);
  a10=(a21*a27);
  a03=(a03+a10);
  a10=(a08*a28);
  a03=(a03+a10);
  a20=(a20*a26);
  a20=(a09*a20);
  a30=(a30*a20);
  a03=(a03-a30);
  if (res[0]!=0) res[0][5]=a03;
  a06=(a06*a05);
  a04=(a04*a07);
  a06=(a06-a04);
  a01=(a01*a29);
  a06=(a06-a01);
  a13=(a17*a13);
  a06=(a06+a13);
  a19=(a08*a19);
  a06=(a06+a19);
  a23=(a17*a23);
  a06=(a06+a23);
  a23=(a24+a24);
  a15=(a23*a15);
  a06=(a06-a15);
  a25=(a21*a25);
  a06=(a06+a25);
  a27=(a08*a27);
  a06=(a06+a27);
  a28=(a21*a28);
  a06=(a06-a28);
  a23=(a23*a20);
  a06=(a06-a23);
  if (res[0]!=0) res[0][6]=a06;
  a06=(a08*a24);
  a23=(a17*a21);
  a20=(a06-a23);
  a20=(a09*a20);
  a20=(a20*a16);
  a28=(a08*a17);
  a27=(a24*a21);
  a25=(a28+a27);
  a25=(a09*a25);
  a25=(a25*a22);
  a20=(a20+a25);
  a25=1.;
  a15=casadi_sq(a17);
  a19=casadi_sq(a24);
  a13=(a15+a19);
  a13=(a09*a13);
  a13=(a25-a13);
  a13=(a13*a26);
  a20=(a20+a13);
  if (res[0]!=0) res[0][7]=a20;
  a20=(a17*a24);
  a13=(a08*a21);
  a01=(a20+a13);
  a01=(a09*a01);
  a01=(a01*a16);
  a04=casadi_sq(a08);
  a19=(a04+a19);
  a19=(a09*a19);
  a19=(a25-a19);
  a19=(a19*a22);
  a01=(a01+a19);
  a28=(a28-a27);
  a28=(a09*a28);
  a28=(a28*a26);
  a01=(a01+a28);
  if (res[0]!=0) res[0][8]=a01;
  a04=(a04+a15);
  a04=(a09*a04);
  a25=(a25-a04);
  a25=(a25*a16);
  a20=(a20-a13);
  a20=(a09*a20);
  a20=(a20*a22);
  a25=(a25+a20);
  a06=(a06+a23);
  a09=(a09*a06);
  a09=(a09*a26);
  a25=(a25+a09);
  if (res[0]!=0) res[0][9]=a25;
  a25=(a24*a05);
  a25=(a00*a25);
  a09=(a17*a02);
  a09=(a00*a09);
  a25=(a25-a09);
  a09=(a21*a07);
  a09=(a00*a09);
  a25=(a25+a09);
  a09=(a08*a29);
  a09=(a00*a09);
  a25=(a25-a09);
  if (res[0]!=0) res[0][10]=a25;
  a25=(a08*a02);
  a25=(a00*a25);
  a09=(a21*a05);
  a09=(a00*a09);
  a25=(a25+a09);
  a09=(a24*a07);
  a09=(a00*a09);
  a25=(a25-a09);
  a09=(a17*a29);
  a09=(a00*a09);
  a25=(a25-a09);
  if (res[0]!=0) res[0][11]=a25;
  a21=(a21*a02);
  a21=(a00*a21);
  a08=(a08*a05);
  a08=(a00*a08);
  a21=(a21-a08);
  a17=(a17*a07);
  a17=(a00*a17);
  a21=(a21+a17);
  a24=(a24*a29);
  a00=(a00*a24);
  a21=(a21-a00);
  if (res[0]!=0) res[0][12]=a21;
  a21=7.0710681378841400e-02;
  a00=2.2321427511217657e+01;
  a24=arg[1]? arg[1][12] : 0;
  a24=(a00*a24);
  a21=(a21*a24);
  a29=7.0710682868957520e-01;
  a17=(a29*a12);
  a07=(a21+a17);
  a29=(a29*a18);
  a07=(a07+a29);
  if (res[0]!=0) res[0][13]=a07;
  a07=-7.0710681378841400e-02;
  a07=(a07*a24);
  a24=-7.0710682868957520e-01;
  a12=(a24*a12);
  a08=(a07+a12);
  a08=(a08+a29);
  if (res[0]!=0) res[0][14]=a08;
  a07=(a07+a17);
  a24=(a24*a18);
  a07=(a07+a24);
  if (res[0]!=0) res[0][15]=a07;
  a21=(a21+a12);
  a21=(a21+a24);
  if (res[0]!=0) res[0][16]=a21;
  a21=-2.0000000298023224e-01;
  a24=arg[1]? arg[1][11] : 0;
  a24=(a00*a24);
  a21=(a21*a24);
  a12=1.5000000596046448e-01;
  a07=arg[1]? arg[1][10] : 0;
  a00=(a00*a07);
  a12=(a12*a00);
  a07=(a21+a12);
  a07=(a07+a11);
  if (res[0]!=0) res[0][17]=a07;
  a07=-1.5000000596046448e-01;
  a07=(a07*a00);
  a21=(a21+a07);
  a21=(a21+a11);
  if (res[0]!=0) res[0][18]=a21;
  a21=2.0000000298023224e-01;
  a21=(a21*a24);
  a12=(a21+a12);
  a12=(a12+a11);
  if (res[0]!=0) res[0][19]=a12;
  a21=(a21+a07);
  a21=(a21+a11);
  if (res[0]!=0) res[0][20]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_mpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
