/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_mpc_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* bluerov_mpc_expl_ode_fun:(i0[13],i1[6],i2[0])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25;
  a00=1.;
  a01=2.;
  a02=arg[0]? arg[0][5] : 0;
  a03=casadi_sq(a02);
  a04=arg[0]? arg[0][6] : 0;
  a05=casadi_sq(a04);
  a06=(a03+a05);
  a06=(a01*a06);
  a06=(a00-a06);
  a07=arg[0]? arg[0][7] : 0;
  a06=(a06*a07);
  a08=arg[0]? arg[0][4] : 0;
  a09=(a08*a02);
  a10=arg[0]? arg[0][3] : 0;
  a11=(a04*a10);
  a12=(a09-a11);
  a12=(a01*a12);
  a13=arg[0]? arg[0][8] : 0;
  a12=(a12*a13);
  a06=(a06+a12);
  a12=(a08*a04);
  a14=(a02*a10);
  a15=(a12+a14);
  a15=(a01*a15);
  a16=arg[0]? arg[0][9] : 0;
  a15=(a15*a16);
  a06=(a06+a15);
  if (res[0]!=0) res[0][0]=a06;
  a09=(a09+a11);
  a09=(a01*a09);
  a09=(a09*a07);
  a11=casadi_sq(a08);
  a05=(a11+a05);
  a05=(a01*a05);
  a05=(a00-a05);
  a05=(a05*a13);
  a09=(a09+a05);
  a05=(a02*a04);
  a06=(a08*a10);
  a15=(a05-a06);
  a15=(a01*a15);
  a15=(a15*a16);
  a09=(a09+a15);
  if (res[0]!=0) res[0][1]=a09;
  a12=(a12-a14);
  a12=(a01*a12);
  a14=(a12*a07);
  a05=(a05+a06);
  a05=(a01*a05);
  a06=(a05*a13);
  a14=(a14+a06);
  a11=(a11+a03);
  a01=(a01*a11);
  a00=(a00-a01);
  a01=(a00*a16);
  a14=(a14+a01);
  if (res[0]!=0) res[0][2]=a14;
  a14=5.0000000000000000e-01;
  a01=arg[0]? arg[0][10] : 0;
  a11=(a14*a01);
  a03=(a11*a08);
  a06=arg[0]? arg[0][11] : 0;
  a09=(a14*a06);
  a15=(a09*a02);
  a03=(a03+a15);
  a15=arg[0]? arg[0][12] : 0;
  a14=(a14*a15);
  a17=(a14*a04);
  a03=(a03+a17);
  a03=(-a03);
  if (res[0]!=0) res[0][3]=a03;
  a03=(a11*a10);
  a17=(a14*a02);
  a03=(a03+a17);
  a17=(a09*a04);
  a03=(a03-a17);
  if (res[0]!=0) res[0][4]=a03;
  a03=(a09*a10);
  a17=(a14*a08);
  a03=(a03-a17);
  a04=(a11*a04);
  a03=(a03+a04);
  if (res[0]!=0) res[0][5]=a03;
  a14=(a14*a10);
  a09=(a09*a08);
  a14=(a14+a09);
  a11=(a11*a02);
  a14=(a14-a11);
  if (res[0]!=0) res[0][6]=a14;
  a14=5.9880240204865237e-02;
  a11=7.0710670948028564e-01;
  a02=arg[1]? arg[1][0] : 0;
  a09=(a11*a02);
  a08=arg[1]? arg[1][1] : 0;
  a11=(a11*a08);
  a09=(a09+a11);
  a11=-7.0710670948028564e-01;
  a10=arg[1]? arg[1][2] : 0;
  a03=(a11*a10);
  a09=(a09+a03);
  a03=arg[1]? arg[1][3] : 0;
  a11=(a11*a03);
  a09=(a09+a11);
  a11=1.1920927533992653e-07;
  a04=arg[1]? arg[1][4] : 0;
  a17=(a11*a04);
  a09=(a09+a17);
  a17=arg[1]? arg[1][5] : 0;
  a11=(a11*a17);
  a09=(a09+a11);
  a11=1.2699999999999999e+01;
  a11=(a11*a13);
  a18=(a11*a15);
  a19=1.4570000000000000e+01;
  a19=(a19*a16);
  a20=(a19*a06);
  a18=(a18-a20);
  a20=4.0300000000000002e+00;
  a21=1.8180000000000000e+01;
  a22=casadi_fabs(a07);
  a21=(a21*a22);
  a20=(a20+a21);
  a20=(a20*a07);
  a18=(a18-a20);
  a20=1.1096936916300001e+02;
  a21=(a20*a12);
  a18=(a18+a21);
  a22=-1.0987199812889099e+02;
  a12=(a22*a12);
  a18=(a18+a12);
  a09=(a09+a18);
  a14=(a14*a09);
  if (res[0]!=0) res[0][7]=a14;
  a14=4.1841004518014153e-02;
  a09=7.0710682868957520e-01;
  a18=(a09*a02);
  a12=-7.0710682868957520e-01;
  a23=(a12*a08);
  a18=(a18+a23);
  a09=(a09*a10);
  a18=(a18+a09);
  a12=(a12*a03);
  a18=(a18+a12);
  a12=(a19*a01);
  a09=5.5000000000000000e+00;
  a09=(a09*a07);
  a23=(a09*a15);
  a12=(a12-a23);
  a23=6.2199999999999998e+00;
  a24=2.1660000000000000e+01;
  a25=casadi_fabs(a13);
  a24=(a24*a25);
  a23=(a23+a24);
  a23=(a23*a13);
  a12=(a12-a23);
  a23=(a20*a05);
  a12=(a12+a23);
  a05=(a22*a05);
  a12=(a12+a05);
  a18=(a18+a12);
  a14=(a14*a18);
  if (res[0]!=0) res[0][8]=a14;
  a14=3.8804812083873902e-02;
  a18=(a04+a17);
  a12=(a09*a06);
  a05=(a11*a01);
  a12=(a12-a05);
  a05=5.1799999999999997e+00;
  a24=3.6990000000000002e+01;
  a25=casadi_fabs(a16);
  a24=(a24*a25);
  a05=(a05+a24);
  a05=(a05*a16);
  a12=(a12-a05);
  a20=(a20*a00);
  a12=(a12+a20);
  a22=(a22*a00);
  a12=(a12+a22);
  a18=(a18+a12);
  a14=(a14*a18);
  if (res[0]!=0) res[0][9]=a14;
  a14=2.3598819594279892e+00;
  a18=5.1265239715576172e-02;
  a12=(a18*a02);
  a22=-5.1265239715576172e-02;
  a00=(a22*a08);
  a12=(a12+a00);
  a18=(a18*a10);
  a12=(a12+a18);
  a22=(a22*a03);
  a12=(a12+a22);
  a22=-1.1050006002187729e-01;
  a22=(a22*a04);
  a12=(a12+a22);
  a22=1.1050006002187729e-01;
  a22=(a22*a17);
  a12=(a12+a22);
  a22=(a11*a16);
  a18=(a19*a13);
  a22=(a22-a18);
  a18=1.2000000000000000e-01;
  a00=(a18*a06);
  a20=(a00*a15);
  a05=(a18*a15);
  a24=(a05*a06);
  a20=(a20-a24);
  a22=(a22+a20);
  a20=7.0000000000000007e-02;
  a24=1.5500000000000000e+00;
  a25=casadi_fabs(a01);
  a25=(a24*a25);
  a25=(a20+a25);
  a25=(a25*a01);
  a22=(a22-a25);
  a25=-1.0000000000000000e-02;
  a23=(a25*a23);
  a22=(a22-a23);
  a12=(a12+a22);
  a14=(a14*a12);
  if (res[0]!=0) res[0][10]=a14;
  a14=1.3404825968608334e+00;
  a12=-5.1265228539705276e-02;
  a22=(a12*a02);
  a12=(a12*a08);
  a22=(a22+a12);
  a12=5.1265228539705276e-02;
  a23=(a12*a10);
  a22=(a22+a23);
  a12=(a12*a03);
  a22=(a22+a12);
  a12=-2.5000013411045074e-03;
  a23=(a12*a04);
  a22=(a22+a23);
  a12=(a12*a17);
  a22=(a22+a12);
  a19=(a19*a07);
  a16=(a09*a16);
  a19=(a19-a16);
  a05=(a05*a01);
  a18=(a18*a01);
  a16=(a18*a15);
  a05=(a05-a16);
  a19=(a19+a05);
  a05=casadi_fabs(a06);
  a05=(a24*a05);
  a05=(a20+a05);
  a05=(a05*a06);
  a19=(a19-a05);
  a25=(a25*a21);
  a19=(a19+a25);
  a22=(a22+a19);
  a14=(a14*a22);
  if (res[0]!=0) res[0][11]=a14;
  a14=1.4349260903094676e+00;
  a22=1.6652362048625946e-01;
  a22=(a22*a02);
  a02=-1.6652362048625946e-01;
  a02=(a02*a08);
  a22=(a22+a02);
  a02=-1.7500892281532288e-01;
  a02=(a02*a10);
  a22=(a22+a02);
  a02=1.7500892281532288e-01;
  a02=(a02*a03);
  a22=(a22+a02);
  a02=1.3172631874169838e-08;
  a02=(a02*a04);
  a22=(a22+a02);
  a02=-1.3172631874169838e-08;
  a02=(a02*a17);
  a22=(a22+a02);
  a09=(a09*a13);
  a11=(a11*a07);
  a09=(a09-a11);
  a18=(a18*a06);
  a00=(a00*a01);
  a18=(a18-a00);
  a09=(a09+a18);
  a18=casadi_fabs(a15);
  a24=(a24*a18);
  a20=(a20+a24);
  a20=(a20*a15);
  a09=(a09-a20);
  a22=(a22+a09);
  a14=(a14*a22);
  if (res[0]!=0) res[0][12]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_mpc_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
