/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hover_mpc_qrdiag_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {179, 1, 1};
static const casadi_int casadi_s5[3] = {1, 1, 1};

/* hover_mpc_qrdiag_cost_ext_cost_0_fun:(i0[13],i1[6],i2[0],i3[4],i4[179])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  a00=5.0000000000000000e-01;
  a01=arg[4]? arg[4][0] : 0;
  a02=arg[0]? arg[0][0] : 0;
  a03=casadi_sq(a02);
  a01=(a01*a03);
  a03=arg[4]? arg[4][1] : 0;
  a04=arg[0]? arg[0][1] : 0;
  a05=casadi_sq(a04);
  a03=(a03*a05);
  a01=(a01+a03);
  a03=arg[4]? arg[4][2] : 0;
  a05=arg[0]? arg[0][2] : 0;
  a06=casadi_sq(a05);
  a03=(a03*a06);
  a01=(a01+a03);
  a03=arg[4]? arg[4][3] : 0;
  a06=arg[0]? arg[0][3] : 0;
  a07=casadi_sq(a06);
  a08=arg[0]? arg[0][4] : 0;
  a09=casadi_sq(a08);
  a07=(a07+a09);
  a09=arg[0]? arg[0][5] : 0;
  a10=casadi_sq(a09);
  a07=(a07+a10);
  a10=arg[0]? arg[0][6] : 0;
  a11=casadi_sq(a10);
  a07=(a07+a11);
  a11=9.9999999999999998e-13;
  a07=(a07+a11);
  a07=sqrt(a07);
  a12=(a06/a07);
  a13=arg[3]? arg[3][0] : 0;
  a14=casadi_sq(a13);
  a15=arg[3]? arg[3][1] : 0;
  a16=casadi_sq(a15);
  a14=(a14+a16);
  a16=arg[3]? arg[3][2] : 0;
  a17=casadi_sq(a16);
  a14=(a14+a17);
  a17=arg[3]? arg[3][3] : 0;
  a18=casadi_sq(a17);
  a14=(a14+a18);
  a14=(a14+a11);
  a14=sqrt(a14);
  a13=(a13/a14);
  a12=(a12*a13);
  a11=(a08/a07);
  a15=(a15/a14);
  a11=(a11*a15);
  a12=(a12+a11);
  a11=(a09/a07);
  a16=(a16/a14);
  a11=(a11*a16);
  a12=(a12+a11);
  a07=(a10/a07);
  a17=(a17/a14);
  a07=(a07*a17);
  a12=(a12+a07);
  a07=0.;
  a12=(a12<a07);
  a07=(-a13);
  a07=(a12?a07:0);
  a14=(!a12);
  a13=(a14?a13:0);
  a07=(a07+a13);
  a06=(a06-a07);
  a07=casadi_sq(a06);
  a03=(a03*a07);
  a01=(a01+a03);
  a03=arg[4]? arg[4][4] : 0;
  a07=(-a15);
  a07=(a12?a07:0);
  a15=(a14?a15:0);
  a07=(a07+a15);
  a08=(a08-a07);
  a07=casadi_sq(a08);
  a03=(a03*a07);
  a01=(a01+a03);
  a03=arg[4]? arg[4][5] : 0;
  a07=(-a16);
  a07=(a12?a07:0);
  a16=(a14?a16:0);
  a07=(a07+a16);
  a09=(a09-a07);
  a07=casadi_sq(a09);
  a03=(a03*a07);
  a01=(a01+a03);
  a03=arg[4]? arg[4][6] : 0;
  a07=(-a17);
  a12=(a12?a07:0);
  a14=(a14?a17:0);
  a12=(a12+a14);
  a10=(a10-a12);
  a12=casadi_sq(a10);
  a03=(a03*a12);
  a01=(a01+a03);
  a03=arg[4]? arg[4][7] : 0;
  a12=arg[0]? arg[0][7] : 0;
  a14=casadi_sq(a12);
  a03=(a03*a14);
  a01=(a01+a03);
  a03=arg[4]? arg[4][8] : 0;
  a14=arg[0]? arg[0][8] : 0;
  a17=casadi_sq(a14);
  a03=(a03*a17);
  a01=(a01+a03);
  a03=arg[4]? arg[4][9] : 0;
  a17=arg[0]? arg[0][9] : 0;
  a07=casadi_sq(a17);
  a03=(a03*a07);
  a01=(a01+a03);
  a03=arg[4]? arg[4][10] : 0;
  a07=arg[0]? arg[0][10] : 0;
  a16=casadi_sq(a07);
  a03=(a03*a16);
  a01=(a01+a03);
  a03=arg[4]? arg[4][11] : 0;
  a16=arg[0]? arg[0][11] : 0;
  a15=casadi_sq(a16);
  a03=(a03*a15);
  a01=(a01+a03);
  a03=arg[4]? arg[4][12] : 0;
  a15=arg[0]? arg[0][12] : 0;
  a13=casadi_sq(a15);
  a03=(a03*a13);
  a01=(a01+a03);
  a03=arg[4]? arg[4][13] : 0;
  a13=arg[1]? arg[1][0] : 0;
  a11=casadi_sq(a13);
  a03=(a03*a11);
  a11=arg[4]? arg[4][14] : 0;
  a18=arg[1]? arg[1][1] : 0;
  a19=casadi_sq(a18);
  a11=(a11*a19);
  a03=(a03+a11);
  a11=arg[4]? arg[4][15] : 0;
  a19=arg[1]? arg[1][2] : 0;
  a20=casadi_sq(a19);
  a11=(a11*a20);
  a03=(a03+a11);
  a11=arg[4]? arg[4][16] : 0;
  a20=arg[1]? arg[1][3] : 0;
  a21=casadi_sq(a20);
  a11=(a11*a21);
  a03=(a03+a11);
  a11=arg[4]? arg[4][17] : 0;
  a21=arg[1]? arg[1][4] : 0;
  a22=casadi_sq(a21);
  a11=(a11*a22);
  a03=(a03+a11);
  a11=arg[4]? arg[4][18] : 0;
  a22=arg[1]? arg[1][5] : 0;
  a23=casadi_sq(a22);
  a11=(a11*a23);
  a03=(a03+a11);
  a01=(a01+a03);
  a00=(a00*a01);
  a01=arg[4]? arg[4][19] : 0;
  a01=(a01*a02);
  a02=arg[4]? arg[4][20] : 0;
  a02=(a02*a04);
  a01=(a01+a02);
  a02=arg[4]? arg[4][21] : 0;
  a02=(a02*a05);
  a01=(a01+a02);
  a02=arg[4]? arg[4][22] : 0;
  a02=(a02*a06);
  a01=(a01+a02);
  a02=arg[4]? arg[4][23] : 0;
  a02=(a02*a08);
  a01=(a01+a02);
  a02=arg[4]? arg[4][24] : 0;
  a02=(a02*a09);
  a01=(a01+a02);
  a02=arg[4]? arg[4][25] : 0;
  a02=(a02*a10);
  a01=(a01+a02);
  a02=arg[4]? arg[4][26] : 0;
  a02=(a02*a12);
  a01=(a01+a02);
  a02=arg[4]? arg[4][27] : 0;
  a02=(a02*a14);
  a01=(a01+a02);
  a02=arg[4]? arg[4][28] : 0;
  a02=(a02*a17);
  a01=(a01+a02);
  a02=arg[4]? arg[4][29] : 0;
  a02=(a02*a07);
  a01=(a01+a02);
  a02=arg[4]? arg[4][30] : 0;
  a02=(a02*a16);
  a01=(a01+a02);
  a02=arg[4]? arg[4][31] : 0;
  a02=(a02*a15);
  a01=(a01+a02);
  a00=(a00+a01);
  a01=arg[4]? arg[4][32] : 0;
  a01=(a01*a13);
  a13=arg[4]? arg[4][33] : 0;
  a13=(a13*a18);
  a01=(a01+a13);
  a13=arg[4]? arg[4][34] : 0;
  a13=(a13*a19);
  a01=(a01+a13);
  a13=arg[4]? arg[4][35] : 0;
  a13=(a13*a20);
  a01=(a01+a13);
  a13=arg[4]? arg[4][36] : 0;
  a13=(a13*a21);
  a01=(a01+a13);
  a13=arg[4]? arg[4][37] : 0;
  a13=(a13*a22);
  a01=(a01+a13);
  a00=(a00+a01);
  if (res[0]!=0) res[0][0]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_cost_ext_cost_0_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hover_mpc_qrdiag_cost_ext_cost_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_cost_ext_cost_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_cost_ext_cost_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
