/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {4, 1, 1};
static const casadi_int casadi_s3[3] = {179, 1, 1};
static const casadi_int casadi_s4[67] = 
  {13, 38, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  13, 13, 13, 13, 13, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23,
  24, 25, 26, 26, 26, 26, 26, 26,
  26, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 0, 1,
  2, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 12};

/* hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p:(i0[13],i1[0],i2[0],i3[4],i4[179])->(o0[13x38,26nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13;
  a00=5.;
  a01=arg[0]? arg[0][0] : 0;
  a01=(a01+a01);
  a01=(a00*a01);
  if (res[0]!=0) res[0][0]=a01;
  a01=arg[0]? arg[0][1] : 0;
  a01=(a01+a01);
  a01=(a00*a01);
  if (res[0]!=0) res[0][1]=a01;
  a01=arg[0]? arg[0][2] : 0;
  a01=(a01+a01);
  a01=(a00*a01);
  if (res[0]!=0) res[0][2]=a01;
  a01=arg[0]? arg[0][3] : 0;
  a02=casadi_sq(a01);
  a03=arg[0]? arg[0][4] : 0;
  a04=casadi_sq(a03);
  a02=(a02+a04);
  a04=arg[0]? arg[0][5] : 0;
  a05=casadi_sq(a04);
  a02=(a02+a05);
  a05=arg[0]? arg[0][6] : 0;
  a06=casadi_sq(a05);
  a02=(a02+a06);
  a06=9.9999999999999998e-13;
  a02=(a02+a06);
  a02=sqrt(a02);
  a07=(a01/a02);
  a08=arg[3]? arg[3][0] : 0;
  a09=casadi_sq(a08);
  a10=arg[3]? arg[3][1] : 0;
  a11=casadi_sq(a10);
  a09=(a09+a11);
  a11=arg[3]? arg[3][2] : 0;
  a12=casadi_sq(a11);
  a09=(a09+a12);
  a12=arg[3]? arg[3][3] : 0;
  a13=casadi_sq(a12);
  a09=(a09+a13);
  a09=(a09+a06);
  a09=sqrt(a09);
  a08=(a08/a09);
  a07=(a07*a08);
  a06=(a03/a02);
  a10=(a10/a09);
  a06=(a06*a10);
  a07=(a07+a06);
  a06=(a04/a02);
  a11=(a11/a09);
  a06=(a06*a11);
  a07=(a07+a06);
  a02=(a05/a02);
  a12=(a12/a09);
  a02=(a02*a12);
  a07=(a07+a02);
  a02=0.;
  a07=(a07<a02);
  a02=(-a08);
  a02=(a07?a02:0);
  a09=(!a07);
  a08=(a09?a08:0);
  a02=(a02+a08);
  a01=(a01-a02);
  a01=(a01+a01);
  a01=(a00*a01);
  if (res[0]!=0) res[0][3]=a01;
  a01=(-a10);
  a01=(a07?a01:0);
  a10=(a09?a10:0);
  a01=(a01+a10);
  a03=(a03-a01);
  a03=(a03+a03);
  a03=(a00*a03);
  if (res[0]!=0) res[0][4]=a03;
  a03=(-a11);
  a03=(a07?a03:0);
  a11=(a09?a11:0);
  a03=(a03+a11);
  a04=(a04-a03);
  a04=(a04+a04);
  a04=(a00*a04);
  if (res[0]!=0) res[0][5]=a04;
  a04=(-a12);
  a07=(a07?a04:0);
  a09=(a09?a12:0);
  a07=(a07+a09);
  a05=(a05-a07);
  a05=(a05+a05);
  a05=(a00*a05);
  if (res[0]!=0) res[0][6]=a05;
  a05=arg[0]? arg[0][7] : 0;
  a05=(a05+a05);
  a05=(a00*a05);
  if (res[0]!=0) res[0][7]=a05;
  a05=arg[0]? arg[0][8] : 0;
  a05=(a05+a05);
  a05=(a00*a05);
  if (res[0]!=0) res[0][8]=a05;
  a05=arg[0]? arg[0][9] : 0;
  a05=(a05+a05);
  a05=(a00*a05);
  if (res[0]!=0) res[0][9]=a05;
  a05=arg[0]? arg[0][10] : 0;
  a05=(a05+a05);
  a05=(a00*a05);
  if (res[0]!=0) res[0][10]=a05;
  a05=arg[0]? arg[0][11] : 0;
  a05=(a05+a05);
  a05=(a00*a05);
  if (res[0]!=0) res[0][11]=a05;
  a05=arg[0]? arg[0][12] : 0;
  a05=(a05+a05);
  a00=(a00*a05);
  if (res[0]!=0) res[0][12]=a00;
  a00=10.;
  if (res[0]!=0) res[0][13]=a00;
  if (res[0]!=0) res[0][14]=a00;
  if (res[0]!=0) res[0][15]=a00;
  if (res[0]!=0) res[0][16]=a00;
  if (res[0]!=0) res[0][17]=a00;
  if (res[0]!=0) res[0][18]=a00;
  if (res[0]!=0) res[0][19]=a00;
  if (res[0]!=0) res[0][20]=a00;
  if (res[0]!=0) res[0][21]=a00;
  if (res[0]!=0) res[0][22]=a00;
  if (res[0]!=0) res[0][23]=a00;
  if (res[0]!=0) res[0][24]=a00;
  if (res[0]!=0) res[0][25]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_incref(void) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_e_hess_xu_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
