/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {4, 1, 1};
static const casadi_int casadi_s4[3] = {179, 1, 1};
static const casadi_int casadi_s5[3] = {1, 1, 1};
static const casadi_int casadi_s6[3] = {19, 1, 1};
static const casadi_int casadi_s7[53] = 
  {19, 19, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 13, 17, 21, 25,
  26, 27, 28, 29, 30, 31, 0, 1,
  2, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 12, 9, 10, 11, 12, 9,
  10, 11, 12, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18};
static const casadi_int casadi_s8[3] = {0, 0, 1};
static const casadi_int casadi_s9[3] = {0, 19, 1};

/* hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess:(i0[13],i1[6],i2[0],i3[4],i4[179])->(o0,o1[19],o2[19x19,31nz],o3[],o4[0x19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60;
  a00=5.0000000000000000e-01;
  a01=arg[4]? arg[4][0] : 0;
  a02=arg[0]? arg[0][0] : 0;
  a03=casadi_sq(a02);
  a03=(a01*a03);
  a04=arg[4]? arg[4][1] : 0;
  a05=arg[0]? arg[0][1] : 0;
  a06=casadi_sq(a05);
  a06=(a04*a06);
  a03=(a03+a06);
  a06=arg[4]? arg[4][2] : 0;
  a07=arg[0]? arg[0][2] : 0;
  a08=casadi_sq(a07);
  a08=(a06*a08);
  a03=(a03+a08);
  a08=arg[4]? arg[4][3] : 0;
  a09=arg[0]? arg[0][3] : 0;
  a10=casadi_sq(a09);
  a11=arg[0]? arg[0][4] : 0;
  a12=casadi_sq(a11);
  a10=(a10+a12);
  a12=arg[0]? arg[0][5] : 0;
  a13=casadi_sq(a12);
  a10=(a10+a13);
  a13=arg[0]? arg[0][6] : 0;
  a14=casadi_sq(a13);
  a10=(a10+a14);
  a14=9.9999999999999998e-13;
  a10=(a10+a14);
  a10=sqrt(a10);
  a15=(a09/a10);
  a16=arg[3]? arg[3][0] : 0;
  a17=casadi_sq(a16);
  a18=arg[3]? arg[3][1] : 0;
  a19=casadi_sq(a18);
  a17=(a17+a19);
  a19=arg[3]? arg[3][2] : 0;
  a20=casadi_sq(a19);
  a17=(a17+a20);
  a20=arg[3]? arg[3][3] : 0;
  a21=casadi_sq(a20);
  a17=(a17+a21);
  a17=(a17+a14);
  a17=sqrt(a17);
  a16=(a16/a17);
  a15=(a15*a16);
  a14=(a11/a10);
  a18=(a18/a17);
  a14=(a14*a18);
  a15=(a15+a14);
  a14=(a12/a10);
  a19=(a19/a17);
  a14=(a14*a19);
  a15=(a15+a14);
  a10=(a13/a10);
  a20=(a20/a17);
  a10=(a10*a20);
  a15=(a15+a10);
  a10=0.;
  a15=(a15<a10);
  a17=(-a16);
  a17=(a15?a17:0);
  a14=(!a15);
  a16=(a14?a16:0);
  a17=(a17+a16);
  a09=(a09-a17);
  a17=casadi_sq(a09);
  a17=(a08*a17);
  a03=(a03+a17);
  a17=arg[4]? arg[4][4] : 0;
  a16=(-a18);
  a16=(a15?a16:0);
  a18=(a14?a18:0);
  a16=(a16+a18);
  a11=(a11-a16);
  a16=casadi_sq(a11);
  a16=(a17*a16);
  a03=(a03+a16);
  a16=arg[4]? arg[4][5] : 0;
  a18=(-a19);
  a18=(a15?a18:0);
  a19=(a14?a19:0);
  a18=(a18+a19);
  a12=(a12-a18);
  a18=casadi_sq(a12);
  a18=(a16*a18);
  a03=(a03+a18);
  a18=arg[4]? arg[4][6] : 0;
  a19=(-a20);
  a15=(a15?a19:0);
  a14=(a14?a20:0);
  a15=(a15+a14);
  a13=(a13-a15);
  a15=casadi_sq(a13);
  a15=(a18*a15);
  a03=(a03+a15);
  a15=arg[4]? arg[4][7] : 0;
  a14=arg[0]? arg[0][7] : 0;
  a20=casadi_sq(a14);
  a20=(a15*a20);
  a03=(a03+a20);
  a20=arg[4]? arg[4][8] : 0;
  a19=arg[0]? arg[0][8] : 0;
  a21=casadi_sq(a19);
  a21=(a20*a21);
  a03=(a03+a21);
  a21=arg[4]? arg[4][9] : 0;
  a22=arg[0]? arg[0][9] : 0;
  a23=casadi_sq(a22);
  a23=(a21*a23);
  a03=(a03+a23);
  a23=arg[4]? arg[4][10] : 0;
  a24=arg[0]? arg[0][10] : 0;
  a25=casadi_sq(a24);
  a25=(a23*a25);
  a03=(a03+a25);
  a25=arg[4]? arg[4][11] : 0;
  a26=arg[0]? arg[0][11] : 0;
  a27=casadi_sq(a26);
  a27=(a25*a27);
  a03=(a03+a27);
  a27=arg[4]? arg[4][12] : 0;
  a28=arg[0]? arg[0][12] : 0;
  a29=casadi_sq(a28);
  a29=(a27*a29);
  a03=(a03+a29);
  a29=arg[4]? arg[4][13] : 0;
  a30=arg[1]? arg[1][0] : 0;
  a31=casadi_sq(a30);
  a31=(a29*a31);
  a32=arg[4]? arg[4][14] : 0;
  a33=arg[1]? arg[1][1] : 0;
  a34=casadi_sq(a33);
  a34=(a32*a34);
  a31=(a31+a34);
  a34=arg[4]? arg[4][15] : 0;
  a35=arg[1]? arg[1][2] : 0;
  a36=casadi_sq(a35);
  a36=(a34*a36);
  a31=(a31+a36);
  a36=arg[4]? arg[4][16] : 0;
  a37=arg[1]? arg[1][3] : 0;
  a38=casadi_sq(a37);
  a38=(a36*a38);
  a31=(a31+a38);
  a38=arg[4]? arg[4][17] : 0;
  a39=arg[1]? arg[1][4] : 0;
  a40=casadi_sq(a39);
  a40=(a38*a40);
  a31=(a31+a40);
  a40=arg[4]? arg[4][18] : 0;
  a41=arg[1]? arg[1][5] : 0;
  a42=casadi_sq(a41);
  a42=(a40*a42);
  a31=(a31+a42);
  a03=(a03+a31);
  a00=(a00*a03);
  a03=arg[4]? arg[4][19] : 0;
  a31=(a03*a02);
  a42=arg[4]? arg[4][20] : 0;
  a43=(a42*a05);
  a31=(a31+a43);
  a43=arg[4]? arg[4][21] : 0;
  a44=(a43*a07);
  a31=(a31+a44);
  a44=arg[4]? arg[4][22] : 0;
  a45=(a44*a09);
  a31=(a31+a45);
  a45=arg[4]? arg[4][23] : 0;
  a46=(a45*a11);
  a31=(a31+a46);
  a46=arg[4]? arg[4][24] : 0;
  a47=(a46*a12);
  a31=(a31+a47);
  a47=arg[4]? arg[4][25] : 0;
  a48=(a47*a13);
  a31=(a31+a48);
  a48=arg[4]? arg[4][26] : 0;
  a49=(a48*a14);
  a31=(a31+a49);
  a49=arg[4]? arg[4][27] : 0;
  a50=(a49*a19);
  a31=(a31+a50);
  a50=arg[4]? arg[4][28] : 0;
  a51=(a50*a22);
  a31=(a31+a51);
  a51=arg[4]? arg[4][29] : 0;
  a52=(a51*a24);
  a31=(a31+a52);
  a52=arg[4]? arg[4][30] : 0;
  a53=(a52*a26);
  a31=(a31+a53);
  a53=arg[4]? arg[4][31] : 0;
  a54=(a53*a28);
  a31=(a31+a54);
  a00=(a00+a31);
  a31=arg[4]? arg[4][32] : 0;
  a54=(a31*a30);
  a55=arg[4]? arg[4][33] : 0;
  a56=(a55*a33);
  a54=(a54+a56);
  a56=arg[4]? arg[4][34] : 0;
  a57=(a56*a35);
  a54=(a54+a57);
  a57=arg[4]? arg[4][35] : 0;
  a58=(a57*a37);
  a54=(a54+a58);
  a58=arg[4]? arg[4][36] : 0;
  a59=(a58*a39);
  a54=(a54+a59);
  a59=arg[4]? arg[4][37] : 0;
  a60=(a59*a41);
  a54=(a54+a60);
  a00=(a00+a54);
  if (res[0]!=0) res[0][0]=a00;
  a30=(a30+a30);
  a00=arg[4]? arg[4][38] : 0;
  a30=(a30*a00);
  a31=(a31+a30);
  if (res[1]!=0) res[1][0]=a31;
  a33=(a33+a33);
  a31=arg[4]? arg[4][39] : 0;
  a33=(a33*a31);
  a55=(a55+a33);
  if (res[1]!=0) res[1][1]=a55;
  a35=(a35+a35);
  a55=arg[4]? arg[4][40] : 0;
  a35=(a35*a55);
  a56=(a56+a35);
  if (res[1]!=0) res[1][2]=a56;
  a37=(a37+a37);
  a56=arg[4]? arg[4][41] : 0;
  a37=(a37*a56);
  a57=(a57+a37);
  if (res[1]!=0) res[1][3]=a57;
  a39=(a39+a39);
  a57=arg[4]? arg[4][42] : 0;
  a39=(a39*a57);
  a58=(a58+a39);
  if (res[1]!=0) res[1][4]=a58;
  a41=(a41+a41);
  a58=arg[4]? arg[4][43] : 0;
  a41=(a41*a58);
  a59=(a59+a41);
  if (res[1]!=0) res[1][5]=a59;
  a02=(a02+a02);
  a59=arg[4]? arg[4][44] : 0;
  a02=(a02*a59);
  a03=(a03+a02);
  if (res[1]!=0) res[1][6]=a03;
  a05=(a05+a05);
  a03=arg[4]? arg[4][45] : 0;
  a05=(a05*a03);
  a42=(a42+a05);
  if (res[1]!=0) res[1][7]=a42;
  a07=(a07+a07);
  a42=arg[4]? arg[4][46] : 0;
  a07=(a07*a42);
  a43=(a43+a07);
  if (res[1]!=0) res[1][8]=a43;
  a09=(a09+a09);
  a43=arg[4]? arg[4][47] : 0;
  a09=(a09*a43);
  a44=(a44+a09);
  if (res[1]!=0) res[1][9]=a44;
  a11=(a11+a11);
  a44=arg[4]? arg[4][48] : 0;
  a11=(a11*a44);
  a45=(a45+a11);
  if (res[1]!=0) res[1][10]=a45;
  a12=(a12+a12);
  a45=arg[4]? arg[4][49] : 0;
  a12=(a12*a45);
  a46=(a46+a12);
  if (res[1]!=0) res[1][11]=a46;
  a13=(a13+a13);
  a46=arg[4]? arg[4][50] : 0;
  a13=(a13*a46);
  a47=(a47+a13);
  if (res[1]!=0) res[1][12]=a47;
  a14=(a14+a14);
  a47=arg[4]? arg[4][51] : 0;
  a14=(a14*a47);
  a48=(a48+a14);
  if (res[1]!=0) res[1][13]=a48;
  a19=(a19+a19);
  a48=arg[4]? arg[4][52] : 0;
  a19=(a19*a48);
  a49=(a49+a19);
  if (res[1]!=0) res[1][14]=a49;
  a22=(a22+a22);
  a49=arg[4]? arg[4][53] : 0;
  a22=(a22*a49);
  a50=(a50+a22);
  if (res[1]!=0) res[1][15]=a50;
  a24=(a24+a24);
  a50=arg[4]? arg[4][54] : 0;
  a24=(a24*a50);
  a51=(a51+a24);
  if (res[1]!=0) res[1][16]=a51;
  a26=(a26+a26);
  a51=arg[4]? arg[4][55] : 0;
  a26=(a26*a51);
  a52=(a52+a26);
  if (res[1]!=0) res[1][17]=a52;
  a28=(a28+a28);
  a52=arg[4]? arg[4][56] : 0;
  a28=(a28*a52);
  a53=(a53+a28);
  if (res[1]!=0) res[1][18]=a53;
  if (res[2]!=0) res[2][0]=a29;
  if (res[2]!=0) res[2][1]=a32;
  if (res[2]!=0) res[2][2]=a34;
  if (res[2]!=0) res[2][3]=a36;
  if (res[2]!=0) res[2][4]=a38;
  if (res[2]!=0) res[2][5]=a40;
  if (res[2]!=0) res[2][6]=a01;
  if (res[2]!=0) res[2][7]=a04;
  if (res[2]!=0) res[2][8]=a06;
  if (res[2]!=0) res[2][9]=a08;
  if (res[2]!=0) res[2][10]=a10;
  if (res[2]!=0) res[2][11]=a10;
  if (res[2]!=0) res[2][12]=a10;
  if (res[2]!=0) res[2][13]=a10;
  if (res[2]!=0) res[2][14]=a17;
  if (res[2]!=0) res[2][15]=a10;
  if (res[2]!=0) res[2][16]=a10;
  if (res[2]!=0) res[2][17]=a10;
  if (res[2]!=0) res[2][18]=a10;
  if (res[2]!=0) res[2][19]=a16;
  if (res[2]!=0) res[2][20]=a10;
  if (res[2]!=0) res[2][21]=a10;
  if (res[2]!=0) res[2][22]=a10;
  if (res[2]!=0) res[2][23]=a10;
  if (res[2]!=0) res[2][24]=a18;
  if (res[2]!=0) res[2][25]=a15;
  if (res[2]!=0) res[2][26]=a20;
  if (res[2]!=0) res[2][27]=a21;
  if (res[2]!=0) res[2][28]=a23;
  if (res[2]!=0) res[2][29]=a25;
  if (res[2]!=0) res[2][30]=a27;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
