/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_cylinder_orbit_mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};
static const casadi_int casadi_s3[3] = {19, 1, 1};

/* bluerov_cylinder_orbit_mpc_expl_vde_adj:(i0[13],i1[13],i2[6],i3[8])->(o0[19]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=5.0000000000000000e-01;
  a01=arg[0]? arg[0][12] : 0;
  a02=(a00*a01);
  a03=arg[1]? arg[1][6] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][11] : 0;
  a06=(a00*a05);
  a07=arg[1]? arg[1][5] : 0;
  a08=(a06*a07);
  a04=(a04+a08);
  a08=arg[0]? arg[0][10] : 0;
  a09=(a00*a08);
  a10=arg[1]? arg[1][4] : 0;
  a11=(a09*a10);
  a04=(a04+a11);
  a11=arg[0]? arg[0][4] : 0;
  a12=2.;
  a13=-1.0987199812889099e+02;
  a14=4.1841004518014153e-02;
  a15=arg[1]? arg[1][8] : 0;
  a14=(a14*a15);
  a15=(a13*a14);
  a16=1.1096936916300001e+02;
  a17=-1.0000000000000000e-02;
  a18=2.3598819594279892e+00;
  a19=arg[1]? arg[1][10] : 0;
  a18=(a18*a19);
  a19=(a17*a18);
  a19=(a14-a19);
  a19=(a16*a19);
  a15=(a15+a19);
  a19=arg[0]? arg[0][8] : 0;
  a20=arg[1]? arg[1][2] : 0;
  a21=(a19*a20);
  a15=(a15+a21);
  a15=(a12*a15);
  a21=(a11*a15);
  a04=(a04+a21);
  a21=arg[0]? arg[0][5] : 0;
  a22=5.9880240204865237e-02;
  a23=arg[1]? arg[1][7] : 0;
  a22=(a22*a23);
  a23=(a13*a22);
  a24=1.3404825968608334e+00;
  a25=arg[1]? arg[1][11] : 0;
  a24=(a24*a25);
  a17=(a17*a24);
  a17=(a17+a22);
  a17=(a16*a17);
  a23=(a23+a17);
  a17=arg[0]? arg[0][7] : 0;
  a25=(a17*a20);
  a23=(a23+a25);
  a23=(a12*a23);
  a25=(a21*a23);
  a04=(a04-a25);
  a25=arg[0]? arg[0][9] : 0;
  a26=arg[1]? arg[1][1] : 0;
  a27=(a25*a26);
  a27=(a12*a27);
  a28=(a11*a27);
  a04=(a04-a28);
  a28=arg[0]? arg[0][6] : 0;
  a29=(a17*a26);
  a29=(a12*a29);
  a30=(a28*a29);
  a04=(a04+a30);
  a30=arg[1]? arg[1][0] : 0;
  a31=(a25*a30);
  a31=(a12*a31);
  a32=(a21*a31);
  a04=(a04+a32);
  a32=(a19*a30);
  a32=(a12*a32);
  a33=(a28*a32);
  a04=(a04-a33);
  if (res[0]!=0) res[0][3]=a04;
  a04=(a06*a03);
  a33=(a02*a07);
  a04=(a04-a33);
  a33=arg[1]? arg[1][3] : 0;
  a34=(a09*a33);
  a04=(a04-a34);
  a34=(a11+a11);
  a35=3.8804812083873902e-02;
  a36=arg[1]? arg[1][9] : 0;
  a35=(a35*a36);
  a13=(a13*a35);
  a16=(a16*a35);
  a13=(a13+a16);
  a16=(a25*a20);
  a13=(a13+a16);
  a13=(a12*a13);
  a16=(a34*a13);
  a04=(a04-a16);
  a16=arg[0]? arg[0][3] : 0;
  a36=(a16*a15);
  a04=(a04+a36);
  a36=(a28*a23);
  a04=(a04+a36);
  a36=(a16*a27);
  a04=(a04-a36);
  a36=(a19*a26);
  a36=(a12*a36);
  a34=(a34*a36);
  a04=(a04-a34);
  a34=(a21*a29);
  a04=(a04+a34);
  a34=(a28*a31);
  a04=(a04+a34);
  a34=(a21*a32);
  a04=(a04+a34);
  if (res[0]!=0) res[0][4]=a04;
  a04=(a02*a10);
  a34=(a09*a03);
  a04=(a04-a34);
  a34=(a06*a33);
  a04=(a04-a34);
  a34=(a21+a21);
  a13=(a34*a13);
  a04=(a04-a13);
  a13=(a28*a15);
  a04=(a04+a13);
  a13=(a16*a23);
  a04=(a04-a13);
  a13=(a28*a27);
  a04=(a04+a13);
  a13=(a11*a29);
  a04=(a04+a13);
  a13=(a16*a31);
  a04=(a04+a13);
  a13=(a11*a32);
  a04=(a04+a13);
  a13=(a17*a30);
  a13=(a12*a13);
  a34=(a34*a13);
  a04=(a04-a34);
  if (res[0]!=0) res[0][5]=a04;
  a09=(a09*a07);
  a06=(a06*a10);
  a09=(a09-a06);
  a02=(a02*a33);
  a09=(a09-a02);
  a15=(a21*a15);
  a09=(a09+a15);
  a23=(a11*a23);
  a09=(a09+a23);
  a27=(a21*a27);
  a09=(a09+a27);
  a27=(a28+a28);
  a36=(a27*a36);
  a09=(a09-a36);
  a29=(a16*a29);
  a09=(a09+a29);
  a31=(a11*a31);
  a09=(a09+a31);
  a32=(a16*a32);
  a09=(a09-a32);
  a27=(a27*a13);
  a09=(a09-a27);
  if (res[0]!=0) res[0][6]=a09;
  a09=1.4570000000000000e+01;
  a27=(a09*a25);
  a13=(a27*a24);
  a32=1.2699999999999999e+01;
  a31=(a32*a19);
  a29=1.4349260903094676e+00;
  a36=arg[1]? arg[1][12] : 0;
  a29=(a29*a36);
  a36=(a31*a29);
  a13=(a13-a36);
  a36=5.5000000000000000e+00;
  a23=(a19*a29);
  a15=(a25*a24);
  a23=(a23-a15);
  a15=(a05*a35);
  a23=(a23+a15);
  a15=(a01*a14);
  a23=(a23-a15);
  a23=(a36*a23);
  a13=(a13+a23);
  a23=4.0300000000000002e+00;
  a15=1.8180000000000000e+01;
  a02=casadi_fabs(a17);
  a02=(a15*a02);
  a23=(a23+a02);
  a23=(a23*a22);
  a13=(a13-a23);
  a23=casadi_sign(a17);
  a02=(a17*a22);
  a15=(a15*a02);
  a23=(a23*a15);
  a13=(a13-a23);
  a23=(a11*a28);
  a15=(a21*a16);
  a02=(a23-a15);
  a02=(a12*a02);
  a02=(a02*a20);
  a13=(a13+a02);
  a02=(a11*a21);
  a06=(a28*a16);
  a04=(a02+a06);
  a04=(a12*a04);
  a04=(a04*a26);
  a13=(a13+a04);
  a04=1.;
  a34=casadi_sq(a21);
  a37=casadi_sq(a28);
  a38=(a34+a37);
  a38=(a12*a38);
  a38=(a04-a38);
  a38=(a38*a30);
  a13=(a13+a38);
  if (res[0]!=0) res[0][7]=a13;
  a36=(a36*a17);
  a13=(a36*a29);
  a38=(a27*a18);
  a13=(a13-a38);
  a38=6.2199999999999998e+00;
  a39=2.1660000000000000e+01;
  a40=casadi_fabs(a19);
  a40=(a39*a40);
  a38=(a38+a40);
  a38=(a38*a14);
  a13=(a13-a38);
  a38=casadi_sign(a19);
  a40=(a19*a14);
  a39=(a39*a40);
  a38=(a38*a39);
  a13=(a13-a38);
  a38=(a25*a18);
  a39=(a17*a29);
  a38=(a38-a39);
  a39=(a08*a35);
  a38=(a38-a39);
  a39=(a01*a22);
  a38=(a38+a39);
  a32=(a32*a38);
  a13=(a13+a32);
  a32=(a21*a28);
  a38=(a11*a16);
  a39=(a32+a38);
  a39=(a12*a39);
  a39=(a39*a20);
  a13=(a13+a39);
  a39=casadi_sq(a11);
  a37=(a39+a37);
  a37=(a12*a37);
  a37=(a04-a37);
  a37=(a37*a26);
  a13=(a13+a37);
  a02=(a02-a06);
  a02=(a12*a02);
  a02=(a02*a30);
  a13=(a13+a02);
  if (res[0]!=0) res[0][8]=a13;
  a13=(a31*a18);
  a02=(a36*a24);
  a13=(a13-a02);
  a02=5.1799999999999997e+00;
  a06=3.6990000000000002e+01;
  a37=casadi_fabs(a25);
  a37=(a06*a37);
  a02=(a02+a37);
  a02=(a02*a35);
  a13=(a13-a02);
  a02=casadi_sign(a25);
  a25=(a25*a35);
  a06=(a06*a25);
  a02=(a02*a06);
  a13=(a13-a02);
  a17=(a17*a24);
  a19=(a19*a18);
  a17=(a17-a19);
  a19=(a08*a14);
  a17=(a17+a19);
  a19=(a05*a22);
  a17=(a17-a19);
  a09=(a09*a17);
  a13=(a13+a09);
  a39=(a39+a34);
  a39=(a12*a39);
  a04=(a04-a39);
  a04=(a04*a20);
  a13=(a13+a04);
  a32=(a32-a38);
  a32=(a12*a32);
  a32=(a32*a26);
  a13=(a13+a32);
  a23=(a23+a15);
  a12=(a12*a23);
  a12=(a12*a30);
  a13=(a13+a12);
  if (res[0]!=0) res[0][9]=a13;
  a13=1.2000000000000000e-01;
  a12=(a05*a29);
  a30=(a01*a24);
  a12=(a12-a30);
  a12=(a13*a12);
  a30=(a13*a05);
  a23=(a30*a29);
  a12=(a12-a23);
  a23=(a13*a01);
  a15=(a23*a24);
  a12=(a12+a15);
  a15=7.0000000000000007e-02;
  a32=1.5500000000000000e+00;
  a26=casadi_fabs(a08);
  a26=(a32*a26);
  a26=(a15+a26);
  a26=(a26*a18);
  a12=(a12-a26);
  a26=casadi_sign(a08);
  a38=(a08*a18);
  a38=(a32*a38);
  a26=(a26*a38);
  a12=(a12-a26);
  a26=(a31*a35);
  a12=(a12-a26);
  a26=(a27*a14);
  a12=(a12+a26);
  a26=(a21*a03);
  a26=(a00*a26);
  a12=(a12-a26);
  a26=(a28*a07);
  a26=(a00*a26);
  a12=(a12+a26);
  a26=(a16*a10);
  a26=(a00*a26);
  a12=(a12+a26);
  a26=(a11*a33);
  a26=(a00*a26);
  a12=(a12-a26);
  if (res[0]!=0) res[0][10]=a12;
  a12=(a13*a08);
  a26=(a12*a29);
  a38=casadi_fabs(a05);
  a38=(a32*a38);
  a38=(a15+a38);
  a38=(a38*a24);
  a26=(a26-a38);
  a38=casadi_sign(a05);
  a04=(a05*a24);
  a04=(a32*a04);
  a38=(a38*a04);
  a26=(a26-a38);
  a23=(a23*a18);
  a26=(a26-a23);
  a23=(a01*a18);
  a38=(a08*a29);
  a23=(a23-a38);
  a23=(a13*a23);
  a26=(a26+a23);
  a23=(a36*a35);
  a26=(a26+a23);
  a27=(a27*a22);
  a26=(a26-a27);
  a27=(a11*a03);
  a27=(a00*a27);
  a26=(a26+a27);
  a27=(a16*a07);
  a27=(a00*a27);
  a26=(a26+a27);
  a27=(a28*a10);
  a27=(a00*a27);
  a26=(a26-a27);
  a27=(a21*a33);
  a27=(a00*a27);
  a26=(a26-a27);
  if (res[0]!=0) res[0][11]=a26;
  a08=(a08*a24);
  a05=(a05*a18);
  a08=(a08-a05);
  a13=(a13*a08);
  a08=casadi_fabs(a01);
  a08=(a32*a08);
  a15=(a15+a08);
  a15=(a15*a29);
  a08=casadi_sign(a01);
  a01=(a01*a29);
  a32=(a32*a01);
  a08=(a08*a32);
  a15=(a15+a08);
  a12=(a12*a24);
  a15=(a15+a12);
  a13=(a13-a15);
  a30=(a30*a18);
  a13=(a13+a30);
  a36=(a36*a14);
  a13=(a13-a36);
  a31=(a31*a22);
  a13=(a13+a31);
  a16=(a16*a03);
  a16=(a00*a16);
  a13=(a13+a16);
  a11=(a11*a07);
  a11=(a00*a11);
  a13=(a13-a11);
  a21=(a21*a10);
  a21=(a00*a21);
  a13=(a13+a21);
  a28=(a28*a33);
  a00=(a00*a28);
  a13=(a13-a00);
  if (res[0]!=0) res[0][12]=a13;
  a13=1.6652362048625946e-01;
  a13=(a13*a29);
  a00=-5.1265228539705276e-02;
  a00=(a00*a24);
  a13=(a13+a00);
  a28=5.1265239715576172e-02;
  a28=(a28*a18);
  a13=(a13+a28);
  a33=7.0710682868957520e-01;
  a33=(a33*a14);
  a13=(a13+a33);
  a21=7.0710670948028564e-01;
  a21=(a21*a22);
  a13=(a13+a21);
  if (res[0]!=0) res[0][13]=a13;
  a13=-1.6652362048625946e-01;
  a13=(a13*a29);
  a13=(a13+a00);
  a00=-5.1265239715576172e-02;
  a00=(a00*a18);
  a13=(a13+a00);
  a10=-7.0710682868957520e-01;
  a10=(a10*a14);
  a13=(a13+a10);
  a13=(a13+a21);
  if (res[0]!=0) res[0][14]=a13;
  a13=-1.7500892281532288e-01;
  a13=(a13*a29);
  a21=5.1265228539705276e-02;
  a21=(a21*a24);
  a13=(a13+a21);
  a13=(a13+a28);
  a13=(a13+a33);
  a33=-7.0710670948028564e-01;
  a33=(a33*a22);
  a13=(a13+a33);
  if (res[0]!=0) res[0][15]=a13;
  a13=1.7500892281532288e-01;
  a13=(a13*a29);
  a13=(a13+a21);
  a13=(a13+a00);
  a13=(a13+a10);
  a13=(a13+a33);
  if (res[0]!=0) res[0][16]=a13;
  a13=1.3172631874169838e-08;
  a13=(a13*a29);
  a33=-2.5000013411045074e-03;
  a33=(a33*a24);
  a13=(a13+a33);
  a24=-1.1050006002187729e-01;
  a24=(a24*a18);
  a13=(a13+a24);
  a13=(a13+a35);
  a24=1.1920927533992653e-07;
  a24=(a24*a22);
  a13=(a13+a24);
  if (res[0]!=0) res[0][17]=a13;
  a13=-1.3172631874169838e-08;
  a13=(a13*a29);
  a13=(a13+a33);
  a33=1.1050006002187729e-01;
  a33=(a33*a18);
  a13=(a13+a33);
  a13=(a13+a35);
  a13=(a13+a24);
  if (res[0]!=0) res[0][18]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_cylinder_orbit_mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cylinder_orbit_mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_cylinder_orbit_mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_cylinder_orbit_mpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cylinder_orbit_mpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_cylinder_orbit_mpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cylinder_orbit_mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_cylinder_orbit_mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_cylinder_orbit_mpc_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
