"""
Acados 기반 MPC 컨트롤러.

주의:
- `casadi`, `acados_template`이 설치되어 있어야 동작합니다.
- 모듈 import 시점에는 의존성이 없어도(예: RL만 쓸 때) 전체 프로젝트가 깨지지 않도록,
  실제로 MPC를 생성/사용할 때만 ImportError를 내도록 구성했습니다.
"""

import numpy as np
import torch

from .controller import ControllerBase

try:
    import casadi as ca
    from acados_template import AcadosModel, AcadosOcp, AcadosOcpSolver

    _ACADOS_AVAILABLE = True
    _ACADOS_IMPORT_ERROR: Exception | None = None
except Exception as e:  # pragma: no cover
    ca = None
    AcadosModel = AcadosOcp = AcadosOcpSolver = None
    _ACADOS_AVAILABLE = False
    _ACADOS_IMPORT_ERROR = e

# Helper functions for CasADi symbolic math
def quat_to_rot_mat(q):
    w, x, y, z = q[0], q[1], q[2], q[3]
    return ca.vertcat(
        ca.horzcat(1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)),
        ca.horzcat(2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)),
        ca.horzcat(2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)),
    )

def omega_mat(omega):
    p, q, r = omega[0], omega[1], omega[2]
    return ca.vertcat(
        ca.horzcat(0, -p, -q, -r), ca.horzcat(p, 0, r, -q),
        ca.horzcat(q, -r, 0, p), ca.horzcat(r, q, -p, 0),
    )


def _cross(a, b):
    return ca.vertcat(
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def _quat_to_rpy(q):
    # match marinegym.utils.torch.quaternion_to_euler (roll, pitch, yaw)
    w, x, y, z = q[0], q[1], q[2], q[3]
    roll = ca.atan2(2.0 * (w * x + y * z), 1.0 - 2.0 * (x * x + y * y))
    pitch = ca.asin(2.0 * (w * y - z * x))
    yaw = ca.atan2(2.0 * (w * z + x * y), 1.0 - 2.0 * (y * y + z * z))
    return roll, pitch, yaw


def get_thruster_allocation_matrix():
    """
    (Fallback) BlueROV2에 대한 하드코딩 B 행렬.

    현재 프로젝트에서는 시뮬(USD/prim)에서 geometry를 읽어 B를 자동 산출하는 것을 권장하며,
    이 함수는 `uav_params["thruster_allocation"]`가 제공되지 않았을 때만 사용됩니다.

    B는 thruster 힘 u를 body-frame wrench tau로 매핑합니다: tau = B @ u
      - Rows: Fx, Fy, Fz, Mx, My, Mz
      - Cols: thr1..thr6
    """
    # From URDF: thruster forces are mapped to a wrench (tau) by this matrix.
    # Note: Roll(Mx) and Pitch(My) moments are missing in the URDF map.
    # This assumes they are generated by vertical thrusters (5, 6) at positions
    # (x,y) = (0.1, 0.1) and (-0.1, -0.1) respectively as a plausible guess.
    c45 = 0.7071  # cos(45)
    l = 0.15 # Approximate lever arm for horizontal thrusters
    k_m = 0.05 # Approximate moment constant from propeller rotation

    # Rows: wrench components (Fx, Fy, Fz, Mx, My, Mz)
    # Cols: thruster forces (thr1..thr6)
    B = np.array([
        [ c45,    c45,   -c45,   -c45,    0.0,    0.0],    # Fx
        [ c45,   -c45,    c45,   -c45,    0.0,    0.0],    # Fy
        [ 0.0,    0.0,    0.0,    0.0,    1.0,    1.0],    # Fz
        [ 0.0,    0.0,    0.0,    0.0,   -0.1,    0.1],    # Mx (Roll) - thr6 at +y, thr5 at -y
        [ 0.1,   -0.1,    0.1,   -0.1,    0.0,    0.0],    # My (Pitch) - thr 1,3 at +x, thr 2,4 at -x
        [-k_m,    k_m,   -k_m,    k_m,    0.0,    0.0],    # Mz (Yaw) from reaction torque
    ])
    return B


def setup_acados_ocp(uav_params, dt=0.05, N=20):
    if not _ACADOS_AVAILABLE:  # pragma: no cover
        raise ImportError(
            "MPCController를 사용하려면 casadi와 acados_template이 필요합니다."
        ) from _ACADOS_IMPORT_ERROR

    ocp = AcadosOcp()
    model = AcadosModel()
    model.name = "bluerov_mpc"

    # --- Dimensions ---
    # State: [pos(3), quat(4), lin_vel(3), ang_vel(3)]
    nx = 13

    # Control dimension is derived from B (6 x nu)
    B_np = uav_params.get("thruster_allocation", None)
    if B_np is None:
        B_np = get_thruster_allocation_matrix()
    B_np = np.asarray(B_np, dtype=np.float64)
    if B_np.ndim != 2 or B_np.shape[0] != 6:
        raise ValueError(
            f"thruster_allocation must have shape (6, nu). got {B_np.shape}"
        )
    nu = int(B_np.shape[1])

    # --- Symbolic Variables ---
    x = ca.SX.sym("x", nx)
    u = ca.SX.sym("u", nu) # u is now thruster *forces*
    x_dot = ca.SX.sym("x_dot", nx)

    p, q, v, w = x[0:3], x[3:7], x[7:10], x[10:13]

    # --- Dynamics ---
    # Thruster allocation: tau = B * u
    B = ca.DM(B_np)
    tau = B @ u

    # Rigid body / hydrodynamic parameters (환경 모델을 최대한 반영)
    mass = float(uav_params["mass"])
    inertia = uav_params["inertia"]
    I_mat = np.diag([float(inertia["xx"]), float(inertia["yy"]), float(inertia["zz"])])
    M_rb = ca.DM(
        np.block([[mass * np.eye(3), np.zeros((3, 3))], [np.zeros((3, 3)), I_mat]])
    )

    hydro_params = uav_params["hydro_coef"]
    A = ca.DM(np.diag(hydro_params["added_mass"]))  # added mass (6x6)
    D_lin = ca.DM(np.diag(hydro_params["linear_damping"]))
    D_quad = ca.DM(np.diag(hydro_params["quadratic_damping"]))

    nu_total = x[7:13]  # body-frame twist (6,)

    # coriolis (match UnderwaterVehicle.calculate_corilis)
    ab = A @ nu_total
    ab_lin, ab_ang = ab[0:3], ab[3:6]
    nu_lin, nu_ang = nu_total[0:3], nu_total[3:6]
    coriolis = ca.vertcat(
        -_cross(ab_lin, nu_ang),
        -(_cross(ab_lin, nu_lin) + _cross(ab_ang, nu_ang)),
    )

    # damping (기본은 diag 기반: (D_lin + D_quad*|nu|) nu)
    damping = (D_lin + D_quad @ ca.diag(ca.fabs(nu_total))) @ nu_total

    # buoyancy + gravity (환경에선 gravity는 PhysX가 처리하지만, MPC 모델엔 포함해야 hover가 가능)
    rho = float(uav_params.get("rho", 997.0))
    volume = float(uav_params.get("volume", 0.0))
    buoyancy_force = rho * 9.81 * volume
    com_offset = float(uav_params.get("coBM", 0.0))

    R = quat_to_rot_mat(q)  # body -> world
    f_g_body = R.T @ ca.vertcat(0.0, 0.0, -mass * 9.81)
    f_b_body = R.T @ ca.vertcat(0.0, 0.0, buoyancy_force)
    # buoyancy torque from offset along body z axis (approx)
    r_cb = ca.vertcat(0.0, 0.0, -com_offset)
    tau_b = ca.vertcat(f_b_body, _cross(r_cb, f_b_body))
    tau_g = ca.vertcat(f_g_body, ca.vertcat(0.0, 0.0, 0.0))

    hydro_wrench = -coriolis - damping + tau_b + tau_g

    # Kinematics
    p_dot = R @ v
    q_dot = 0.5 * omega_mat(w) @ q

    # Dynamics: (M_rb + A) * nu_dot = tau + hydro_wrench
    nu_dot = ca.inv(M_rb + A) @ (tau + hydro_wrench)
    v_dot, w_dot = nu_dot[0:3], nu_dot[3:6]

    model.f_expl_expr = ca.vertcat(p_dot, q_dot, v_dot, w_dot)
    model.x, model.u, model.xdot = x, u, x_dot

    # --- Cost Function ---
    ocp.cost.cost_type = "NONLINEAR_LS"
    ocp.cost.cost_type_e = "NONLINEAR_LS"

    # Optional: add roll/pitch tracking terms to keep vehicle level (helps reduce banking).
    # This avoids yaw wrap issues by not using yaw in the additional terms.
    q_roll = float(uav_params.get("mpc_q_roll", 0.0))
    q_pitch = float(uav_params.get("mpc_q_pitch", 0.0))
    roll, pitch, _yaw = _quat_to_rpy(q)
    add_rp_cost = (q_roll > 0.0) or (q_pitch > 0.0)

    if add_rp_cost:
        model.cost_y_expr = ca.vertcat(x, roll, pitch, u)
        model.cost_y_expr_e = ca.vertcat(x, roll, pitch)
    else:
        model.cost_y_expr = ca.vertcat(x, u)
        model.cost_y_expr_e = x

    # cost weights (기본값은 hover에 더 공격적으로)
    q_pos = float(uav_params.get("mpc_q_pos", 50.0))
    q_quat = float(uav_params.get("mpc_q_quat", 5.0))
    q_vel = float(uav_params.get("mpc_q_vel", 2.0))
    q_omega = float(uav_params.get("mpc_q_omega", 0.5))
    r_u = float(uav_params.get("mpc_r_u", 0.01))

    # state weights
    q_state = [q_pos] * 3 + [q_quat] * 4 + [q_vel] * 3 + [q_omega] * 3
    # additional roll/pitch weights (if enabled)
    if add_rp_cost:
        q_state += [q_roll, q_pitch]

    Q = np.diag(q_state)
    R = np.diag([r_u] * nu)

    ny = int(Q.shape[0] + nu)
    ocp.cost.W = np.block([[Q, np.zeros((Q.shape[0], nu))], [np.zeros((nu, Q.shape[0])), R]])
    ocp.cost.W_e = Q
    ocp.cost.yref = np.zeros(ny)
    ocp.cost.yref_e = np.zeros(Q.shape[0])

    # --- Constraints ---
    max_thruster_force = 40.0 # From T200 specs (approx)
    ocp.constraints.lbu = np.array([-max_thruster_force] * nu)
    ocp.constraints.ubu = np.array([max_thruster_force] * nu)
    ocp.constraints.idxbu = np.arange(nu)

    # 초기 상태 제약 (x(0) = x0)용: stage 0에서만 사용
    ocp.constraints.idxbx_0 = np.arange(nx)
    ocp.constraints.lbx_0 = np.zeros(nx)
    ocp.constraints.ubx_0 = np.zeros(nx)
    
    # --- Solver Settings ---
    ocp.model = model
    ocp.dims.N = N
    ocp.solver_options.tf = N * dt
    ocp.solver_options.qp_solver = "PARTIAL_CONDENSING_HPIPM"
    ocp.solver_options.hessian_approx = "GAUSS_NEWTON"
    ocp.solver_options.integrator_type = "ERK"
    ocp.solver_options.nlp_solver_type = "SQP_RTI"

    acados_solver = AcadosOcpSolver(ocp, json_file=f"{model.name}.json")
    return acados_solver


class MPCController(ControllerBase):

    def __init__(self, g, uav_params, dt=0.05, N=20):
        super().__init__()
        self.solver = setup_acados_ocp(uav_params, dt, N)
        self.nx = self.solver.acados_ocp.dims.nx
        self.nu = self.solver.acados_ocp.dims.nu
        # cost output dimensions (ny may include extra roll/pitch terms)
        self.ny = int(getattr(self.solver.acados_ocp.dims, "ny", self.nx + self.nu))
        self.ny_e = int(getattr(self.solver.acados_ocp.dims, "ny_e", self.nx))
        self.N = N
        
        # --- Thruster model constants ---
        # Approximate force = k_f * command^2 or k_f * command for normalized commands
        # For simplicity, we assume solver outputs force, and we convert it to a [-1, 1] command
        self.max_force_per_thruster = 40.0 # Newtons
        
        # --- References ---
        self._yref = np.zeros(self.ny, dtype=np.float64)
        self._yref_e = np.zeros(self.ny_e, dtype=np.float64)
        self._u_ref = np.zeros(self.nu, dtype=np.float64)

        self._warn_count = 0
        
        self.requires_grad_(False)

    def compute(
        self,
        root_state: torch.Tensor,
        target_pos: torch.Tensor,
        *,
        target_quat: torch.Tensor | None = None,
        target_vel_b: torch.Tensor | None = None,
        target_omega_b: torch.Tensor | None = None,
        **kwargs,
    ) -> torch.Tensor:
        device = root_state.device

        x0_batch = root_state.reshape(-1, root_state.shape[-1])
        tp_batch = target_pos.reshape(-1, target_pos.shape[-1])
        tq_batch = None
        if target_quat is not None:
            tq_batch = target_quat.reshape(-1, target_quat.shape[-1])
        tv_batch = None
        if target_vel_b is not None:
            tv_batch = target_vel_b.reshape(-1, target_vel_b.shape[-1])
        tw_batch = None
        if target_omega_b is not None:
            tw_batch = target_omega_b.reshape(-1, target_omega_b.shape[-1])
        batch_size = x0_batch.shape[0]

        commands = torch.zeros(batch_size, self.nu, device=device, dtype=root_state.dtype)

        for i in range(batch_size):
            x0 = x0_batch[i].detach().cpu().numpy().astype(np.float64, copy=False)
            tp = tp_batch[i].detach().cpu().numpy().astype(np.float64, copy=False)

            # 1) initial state constraint: x(0) = x0
            self.solver.set(0, "lbx", x0)
            self.solver.set(0, "ubx", x0)

            # 2) reference: 현재 자세 유지 + 목표 위치로 이동, 속도는 0으로 유도
            x_ref = x0.copy()
            x_ref[0:3] = tp[0:3]
            x_ref[7:13] = 0.0
            if tv_batch is not None:
                tv = tv_batch[i].detach().cpu().numpy().astype(np.float64, copy=False)
                x_ref[7:10] = tv[0:3]
            if tw_batch is not None:
                tw = tw_batch[i].detach().cpu().numpy().astype(np.float64, copy=False)
                x_ref[10:13] = tw[0:3]

            # target pose (quat) tracking
            if tq_batch is not None:
                tq = tq_batch[i].detach().cpu().numpy().astype(np.float64, copy=False)
                # normalize and pick closest representation (q ~ -q)
                tq_norm = np.linalg.norm(tq)
                if tq_norm > 0:
                    tq = tq / tq_norm
                if np.dot(tq, x0[3:7]) < 0:
                    tq = -tq
                x_ref[3:7] = tq

            # cost output may include extra roll/pitch terms after state, before control
            extra = int(self.ny - (self.nx + self.nu))
            extra_e = int(self.ny_e - self.nx)
            if extra not in (0, 2) or extra_e not in (0, 2):
                raise RuntimeError(f"Unexpected MPC cost dims: ny={self.ny} nx={self.nx} nu={self.nu} ny_e={self.ny_e}")

            self._yref[0:self.nx] = x_ref
            if extra == 2:
                # roll/pitch from reference quaternion (wxyz), matching _quat_to_rpy()
                w, x, y, z = x_ref[3], x_ref[4], x_ref[5], x_ref[6]
                roll = np.arctan2(2.0 * (w * x + y * z), 1.0 - 2.0 * (x * x + y * y))
                pitch = np.arcsin(np.clip(2.0 * (w * y - z * x), -1.0, 1.0))
                self._yref[self.nx : self.nx + 2] = np.array([roll, pitch], dtype=np.float64)
                self._yref[self.nx + 2 :] = self._u_ref
            else:
                self._yref[self.nx :] = self._u_ref

            self._yref_e[0:self.nx] = x_ref
            if extra_e == 2:
                self._yref_e[self.nx : self.nx + 2] = self._yref[self.nx : self.nx + 2]

            for k in range(self.N):
                self.solver.set(k, "yref", self._yref)
            self.solver.set(self.N, "yref", self._yref_e)

            # 3) solve
            status = self.solver.solve()
            if status != 0:
                if self._warn_count < 10:
                    print(f"[MPCController] acados solve 실패: status={status}")
                    self._warn_count += 1
                u_opt = np.zeros(self.nu, dtype=np.float64)
            else:
                u_opt = self.solver.get(0, "u")

            # 4) force -> [-1, 1] 커맨드(근사)
            u_cmd = np.clip(u_opt / self.max_force_per_thruster, -1.0, 1.0)
            commands[i].copy_(torch.as_tensor(u_cmd, device=device, dtype=commands.dtype))

        return commands

    def process_rl_actions(self, actions) -> torch.Tensor:
        return actions
