/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {411, 1, 1};
static const casadi_int casadi_s4[41] = 
  {13, 13, 0, 1, 2, 3, 7, 11,
  15, 19, 20, 21, 22, 23, 24, 25,
  0, 1, 2, 3, 4, 5, 6, 3,
  4, 5, 6, 3, 4, 5, 6, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12};
static const casadi_int casadi_s5[3] = {0, 0, 1};
static const casadi_int casadi_s6[3] = {0, 13, 1};

/* pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[0],i2[0],i3,i4[411])->(o0,o1[13],o2[13x13,25nz],o3[],o4[0x13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44;
  a00=5.;
  a01=-200.;
  a02=arg[3]? arg[3][0] : 0;
  a03=(a01*a02);
  a03=(a03*a02);
  a03=exp(a03);
  a04=arg[4]? arg[4][0] : 0;
  a04=(a03*a04);
  a05=1.;
  a05=(a02-a05);
  a06=(a01*a05);
  a06=(a06*a05);
  a06=exp(a06);
  a05=arg[4]? arg[4][1] : 0;
  a05=(a06*a05);
  a04=(a04+a05);
  a05=2.;
  a07=(a02-a05);
  a08=(a01*a07);
  a08=(a08*a07);
  a08=exp(a08);
  a07=arg[4]? arg[4][2] : 0;
  a07=(a08*a07);
  a04=(a04+a07);
  a07=3.;
  a07=(a02-a07);
  a09=(a01*a07);
  a09=(a09*a07);
  a09=exp(a09);
  a07=arg[4]? arg[4][3] : 0;
  a07=(a09*a07);
  a04=(a04+a07);
  a07=4.;
  a07=(a02-a07);
  a10=(a01*a07);
  a10=(a10*a07);
  a10=exp(a10);
  a07=arg[4]? arg[4][4] : 0;
  a07=(a10*a07);
  a04=(a04+a07);
  a07=(a02-a00);
  a11=(a01*a07);
  a11=(a11*a07);
  a11=exp(a11);
  a07=arg[4]? arg[4][5] : 0;
  a07=(a11*a07);
  a04=(a04+a07);
  a07=6.;
  a07=(a02-a07);
  a12=(a01*a07);
  a12=(a12*a07);
  a12=exp(a12);
  a07=arg[4]? arg[4][6] : 0;
  a07=(a12*a07);
  a04=(a04+a07);
  a07=7.;
  a07=(a02-a07);
  a13=(a01*a07);
  a13=(a13*a07);
  a13=exp(a13);
  a07=arg[4]? arg[4][7] : 0;
  a07=(a13*a07);
  a04=(a04+a07);
  a07=8.;
  a07=(a02-a07);
  a14=(a01*a07);
  a14=(a14*a07);
  a14=exp(a14);
  a07=arg[4]? arg[4][8] : 0;
  a07=(a14*a07);
  a04=(a04+a07);
  a07=9.;
  a07=(a02-a07);
  a15=(a01*a07);
  a15=(a15*a07);
  a15=exp(a15);
  a07=arg[4]? arg[4][9] : 0;
  a07=(a15*a07);
  a04=(a04+a07);
  a07=10.;
  a07=(a02-a07);
  a16=(a01*a07);
  a16=(a16*a07);
  a16=exp(a16);
  a07=arg[4]? arg[4][10] : 0;
  a07=(a16*a07);
  a04=(a04+a07);
  a07=11.;
  a07=(a02-a07);
  a17=(a01*a07);
  a17=(a17*a07);
  a17=exp(a17);
  a07=arg[4]? arg[4][11] : 0;
  a07=(a17*a07);
  a04=(a04+a07);
  a07=12.;
  a07=(a02-a07);
  a18=(a01*a07);
  a18=(a18*a07);
  a18=exp(a18);
  a07=arg[4]? arg[4][12] : 0;
  a07=(a18*a07);
  a04=(a04+a07);
  a07=13.;
  a07=(a02-a07);
  a19=(a01*a07);
  a19=(a19*a07);
  a19=exp(a19);
  a07=arg[4]? arg[4][13] : 0;
  a07=(a19*a07);
  a04=(a04+a07);
  a07=14.;
  a02=(a02-a07);
  a01=(a01*a02);
  a01=(a01*a02);
  a01=exp(a01);
  a02=arg[4]? arg[4][14] : 0;
  a02=(a01*a02);
  a04=(a04+a02);
  a02=9.9999999999999998e-13;
  a07=(a02+a03);
  a07=(a07+a06);
  a07=(a07+a08);
  a07=(a07+a09);
  a07=(a07+a10);
  a07=(a07+a11);
  a07=(a07+a12);
  a07=(a07+a13);
  a07=(a07+a14);
  a07=(a07+a15);
  a07=(a07+a16);
  a07=(a07+a17);
  a07=(a07+a18);
  a07=(a07+a19);
  a07=(a07+a01);
  a04=(a04/a07);
  a20=arg[0]? arg[0][0] : 0;
  a21=casadi_sq(a20);
  a21=(a04*a21);
  a22=arg[4]? arg[4][15] : 0;
  a22=(a03*a22);
  a23=arg[4]? arg[4][16] : 0;
  a23=(a06*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][17] : 0;
  a23=(a08*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][18] : 0;
  a23=(a09*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][19] : 0;
  a23=(a10*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][20] : 0;
  a23=(a11*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][21] : 0;
  a23=(a12*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][22] : 0;
  a23=(a13*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][23] : 0;
  a23=(a14*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][24] : 0;
  a23=(a15*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][25] : 0;
  a23=(a16*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][26] : 0;
  a23=(a17*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][27] : 0;
  a23=(a18*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][28] : 0;
  a23=(a19*a23);
  a22=(a22+a23);
  a23=arg[4]? arg[4][29] : 0;
  a23=(a01*a23);
  a22=(a22+a23);
  a22=(a22/a07);
  a23=arg[0]? arg[0][1] : 0;
  a24=casadi_sq(a23);
  a24=(a22*a24);
  a21=(a21+a24);
  a24=arg[4]? arg[4][30] : 0;
  a24=(a03*a24);
  a25=arg[4]? arg[4][31] : 0;
  a25=(a06*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][32] : 0;
  a25=(a08*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][33] : 0;
  a25=(a09*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][34] : 0;
  a25=(a10*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][35] : 0;
  a25=(a11*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][36] : 0;
  a25=(a12*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][37] : 0;
  a25=(a13*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][38] : 0;
  a25=(a14*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][39] : 0;
  a25=(a15*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][40] : 0;
  a25=(a16*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][41] : 0;
  a25=(a17*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][42] : 0;
  a25=(a18*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][43] : 0;
  a25=(a19*a25);
  a24=(a24+a25);
  a25=arg[4]? arg[4][44] : 0;
  a25=(a01*a25);
  a24=(a24+a25);
  a24=(a24/a07);
  a25=arg[0]? arg[0][2] : 0;
  a26=casadi_sq(a25);
  a26=(a24*a26);
  a21=(a21+a26);
  a26=arg[4]? arg[4][45] : 0;
  a26=(a03*a26);
  a27=arg[4]? arg[4][46] : 0;
  a27=(a06*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][47] : 0;
  a27=(a08*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][48] : 0;
  a27=(a09*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][49] : 0;
  a27=(a10*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][50] : 0;
  a27=(a11*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][51] : 0;
  a27=(a12*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][52] : 0;
  a27=(a13*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][53] : 0;
  a27=(a14*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][54] : 0;
  a27=(a15*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][55] : 0;
  a27=(a16*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][56] : 0;
  a27=(a17*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][57] : 0;
  a27=(a18*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][58] : 0;
  a27=(a19*a27);
  a26=(a26+a27);
  a27=arg[4]? arg[4][59] : 0;
  a27=(a01*a27);
  a26=(a26+a27);
  a26=(a26/a07);
  a27=arg[0]? arg[0][3] : 0;
  a28=casadi_sq(a27);
  a29=arg[0]? arg[0][4] : 0;
  a30=casadi_sq(a29);
  a28=(a28+a30);
  a30=arg[0]? arg[0][5] : 0;
  a31=casadi_sq(a30);
  a28=(a28+a31);
  a31=arg[0]? arg[0][6] : 0;
  a32=casadi_sq(a31);
  a28=(a28+a32);
  a28=(a28+a02);
  a28=sqrt(a28);
  a02=(a27/a28);
  a32=arg[4]? arg[4][377] : 0;
  a02=(a02*a32);
  a33=(a29/a28);
  a34=arg[4]? arg[4][378] : 0;
  a33=(a33*a34);
  a02=(a02+a33);
  a33=(a30/a28);
  a35=arg[4]? arg[4][379] : 0;
  a33=(a33*a35);
  a02=(a02+a33);
  a28=(a31/a28);
  a33=arg[4]? arg[4][380] : 0;
  a28=(a28*a33);
  a02=(a02+a28);
  a28=0.;
  a02=(a02<a28);
  a36=arg[4]? arg[4][381] : 0;
  a36=(a02?a36:0);
  a37=(!a02);
  a32=(a37?a32:0);
  a36=(a36+a32);
  a27=(a27-a36);
  a36=casadi_sq(a27);
  a36=(a26*a36);
  a21=(a21+a36);
  a36=arg[4]? arg[4][65] : 0;
  a36=(a03*a36);
  a32=arg[4]? arg[4][66] : 0;
  a32=(a06*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][67] : 0;
  a32=(a08*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][68] : 0;
  a32=(a09*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][69] : 0;
  a32=(a10*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][70] : 0;
  a32=(a11*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][71] : 0;
  a32=(a12*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][72] : 0;
  a32=(a13*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][73] : 0;
  a32=(a14*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][74] : 0;
  a32=(a15*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][75] : 0;
  a32=(a16*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][76] : 0;
  a32=(a17*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][77] : 0;
  a32=(a18*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][78] : 0;
  a32=(a19*a32);
  a36=(a36+a32);
  a32=arg[4]? arg[4][79] : 0;
  a32=(a01*a32);
  a36=(a36+a32);
  a36=(a36/a07);
  a32=arg[4]? arg[4][382] : 0;
  a32=(a02?a32:0);
  a34=(a37?a34:0);
  a32=(a32+a34);
  a29=(a29-a32);
  a32=casadi_sq(a29);
  a32=(a36*a32);
  a21=(a21+a32);
  a32=arg[4]? arg[4][81] : 0;
  a32=(a03*a32);
  a34=arg[4]? arg[4][82] : 0;
  a34=(a06*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][83] : 0;
  a34=(a08*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][84] : 0;
  a34=(a09*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][85] : 0;
  a34=(a10*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][86] : 0;
  a34=(a11*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][87] : 0;
  a34=(a12*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][88] : 0;
  a34=(a13*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][89] : 0;
  a34=(a14*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][90] : 0;
  a34=(a15*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][91] : 0;
  a34=(a16*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][92] : 0;
  a34=(a17*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][93] : 0;
  a34=(a18*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][94] : 0;
  a34=(a19*a34);
  a32=(a32+a34);
  a34=arg[4]? arg[4][95] : 0;
  a34=(a01*a34);
  a32=(a32+a34);
  a32=(a32/a07);
  a34=arg[4]? arg[4][383] : 0;
  a34=(a02?a34:0);
  a35=(a37?a35:0);
  a34=(a34+a35);
  a30=(a30-a34);
  a34=casadi_sq(a30);
  a34=(a32*a34);
  a21=(a21+a34);
  a34=arg[4]? arg[4][97] : 0;
  a34=(a03*a34);
  a35=arg[4]? arg[4][98] : 0;
  a35=(a06*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][99] : 0;
  a35=(a08*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][100] : 0;
  a35=(a09*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][101] : 0;
  a35=(a10*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][102] : 0;
  a35=(a11*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][103] : 0;
  a35=(a12*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][104] : 0;
  a35=(a13*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][105] : 0;
  a35=(a14*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][106] : 0;
  a35=(a15*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][107] : 0;
  a35=(a16*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][108] : 0;
  a35=(a17*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][109] : 0;
  a35=(a18*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][110] : 0;
  a35=(a19*a35);
  a34=(a34+a35);
  a35=arg[4]? arg[4][111] : 0;
  a35=(a01*a35);
  a34=(a34+a35);
  a34=(a34/a07);
  a35=arg[4]? arg[4][384] : 0;
  a02=(a02?a35:0);
  a37=(a37?a33:0);
  a02=(a02+a37);
  a31=(a31-a02);
  a02=casadi_sq(a31);
  a02=(a34*a02);
  a21=(a21+a02);
  a02=arg[4]? arg[4][113] : 0;
  a02=(a03*a02);
  a37=arg[4]? arg[4][114] : 0;
  a37=(a06*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][115] : 0;
  a37=(a08*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][116] : 0;
  a37=(a09*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][117] : 0;
  a37=(a10*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][118] : 0;
  a37=(a11*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][119] : 0;
  a37=(a12*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][120] : 0;
  a37=(a13*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][121] : 0;
  a37=(a14*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][122] : 0;
  a37=(a15*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][123] : 0;
  a37=(a16*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][124] : 0;
  a37=(a17*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][125] : 0;
  a37=(a18*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][126] : 0;
  a37=(a19*a37);
  a02=(a02+a37);
  a37=arg[4]? arg[4][127] : 0;
  a37=(a01*a37);
  a02=(a02+a37);
  a02=(a02/a07);
  a37=arg[0]? arg[0][7] : 0;
  a33=casadi_sq(a37);
  a33=(a02*a33);
  a21=(a21+a33);
  a33=arg[4]? arg[4][128] : 0;
  a33=(a03*a33);
  a35=arg[4]? arg[4][129] : 0;
  a35=(a06*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][130] : 0;
  a35=(a08*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][131] : 0;
  a35=(a09*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][132] : 0;
  a35=(a10*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][133] : 0;
  a35=(a11*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][134] : 0;
  a35=(a12*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][135] : 0;
  a35=(a13*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][136] : 0;
  a35=(a14*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][137] : 0;
  a35=(a15*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][138] : 0;
  a35=(a16*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][139] : 0;
  a35=(a17*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][140] : 0;
  a35=(a18*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][141] : 0;
  a35=(a19*a35);
  a33=(a33+a35);
  a35=arg[4]? arg[4][142] : 0;
  a35=(a01*a35);
  a33=(a33+a35);
  a33=(a33/a07);
  a35=arg[0]? arg[0][8] : 0;
  a38=casadi_sq(a35);
  a38=(a33*a38);
  a21=(a21+a38);
  a38=arg[4]? arg[4][143] : 0;
  a38=(a03*a38);
  a39=arg[4]? arg[4][144] : 0;
  a39=(a06*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][145] : 0;
  a39=(a08*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][146] : 0;
  a39=(a09*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][147] : 0;
  a39=(a10*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][148] : 0;
  a39=(a11*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][149] : 0;
  a39=(a12*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][150] : 0;
  a39=(a13*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][151] : 0;
  a39=(a14*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][152] : 0;
  a39=(a15*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][153] : 0;
  a39=(a16*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][154] : 0;
  a39=(a17*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][155] : 0;
  a39=(a18*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][156] : 0;
  a39=(a19*a39);
  a38=(a38+a39);
  a39=arg[4]? arg[4][157] : 0;
  a39=(a01*a39);
  a38=(a38+a39);
  a38=(a38/a07);
  a39=arg[0]? arg[0][9] : 0;
  a40=casadi_sq(a39);
  a40=(a38*a40);
  a21=(a21+a40);
  a40=arg[4]? arg[4][158] : 0;
  a40=(a03*a40);
  a41=arg[4]? arg[4][159] : 0;
  a41=(a06*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][160] : 0;
  a41=(a08*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][161] : 0;
  a41=(a09*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][162] : 0;
  a41=(a10*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][163] : 0;
  a41=(a11*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][164] : 0;
  a41=(a12*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][165] : 0;
  a41=(a13*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][166] : 0;
  a41=(a14*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][167] : 0;
  a41=(a15*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][168] : 0;
  a41=(a16*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][169] : 0;
  a41=(a17*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][170] : 0;
  a41=(a18*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][171] : 0;
  a41=(a19*a41);
  a40=(a40+a41);
  a41=arg[4]? arg[4][172] : 0;
  a41=(a01*a41);
  a40=(a40+a41);
  a40=(a40/a07);
  a41=arg[0]? arg[0][10] : 0;
  a42=casadi_sq(a41);
  a42=(a40*a42);
  a21=(a21+a42);
  a42=arg[4]? arg[4][173] : 0;
  a42=(a03*a42);
  a43=arg[4]? arg[4][174] : 0;
  a43=(a06*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][175] : 0;
  a43=(a08*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][176] : 0;
  a43=(a09*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][177] : 0;
  a43=(a10*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][178] : 0;
  a43=(a11*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][179] : 0;
  a43=(a12*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][180] : 0;
  a43=(a13*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][181] : 0;
  a43=(a14*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][182] : 0;
  a43=(a15*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][183] : 0;
  a43=(a16*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][184] : 0;
  a43=(a17*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][185] : 0;
  a43=(a18*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][186] : 0;
  a43=(a19*a43);
  a42=(a42+a43);
  a43=arg[4]? arg[4][187] : 0;
  a43=(a01*a43);
  a42=(a42+a43);
  a42=(a42/a07);
  a43=arg[0]? arg[0][11] : 0;
  a44=casadi_sq(a43);
  a44=(a42*a44);
  a21=(a21+a44);
  a44=arg[4]? arg[4][188] : 0;
  a03=(a03*a44);
  a44=arg[4]? arg[4][189] : 0;
  a06=(a06*a44);
  a03=(a03+a06);
  a06=arg[4]? arg[4][190] : 0;
  a08=(a08*a06);
  a03=(a03+a08);
  a08=arg[4]? arg[4][191] : 0;
  a09=(a09*a08);
  a03=(a03+a09);
  a09=arg[4]? arg[4][192] : 0;
  a10=(a10*a09);
  a03=(a03+a10);
  a10=arg[4]? arg[4][193] : 0;
  a11=(a11*a10);
  a03=(a03+a11);
  a11=arg[4]? arg[4][194] : 0;
  a12=(a12*a11);
  a03=(a03+a12);
  a12=arg[4]? arg[4][195] : 0;
  a13=(a13*a12);
  a03=(a03+a13);
  a13=arg[4]? arg[4][196] : 0;
  a14=(a14*a13);
  a03=(a03+a14);
  a14=arg[4]? arg[4][197] : 0;
  a15=(a15*a14);
  a03=(a03+a15);
  a15=arg[4]? arg[4][198] : 0;
  a16=(a16*a15);
  a03=(a03+a16);
  a16=arg[4]? arg[4][199] : 0;
  a17=(a17*a16);
  a03=(a03+a17);
  a17=arg[4]? arg[4][200] : 0;
  a18=(a18*a17);
  a03=(a03+a18);
  a18=arg[4]? arg[4][201] : 0;
  a19=(a19*a18);
  a03=(a03+a19);
  a19=arg[4]? arg[4][202] : 0;
  a01=(a01*a19);
  a03=(a03+a01);
  a03=(a03/a07);
  a07=arg[0]? arg[0][12] : 0;
  a01=casadi_sq(a07);
  a01=(a03*a01);
  a21=(a21+a01);
  a21=(a00*a21);
  if (res[0]!=0) res[0][0]=a21;
  a20=(a20+a20);
  a04=(a00*a04);
  a20=(a20*a04);
  if (res[1]!=0) res[1][0]=a20;
  a23=(a23+a23);
  a22=(a00*a22);
  a23=(a23*a22);
  if (res[1]!=0) res[1][1]=a23;
  a25=(a25+a25);
  a24=(a00*a24);
  a25=(a25*a24);
  if (res[1]!=0) res[1][2]=a25;
  a27=(a27+a27);
  a26=(a00*a26);
  a27=(a27*a26);
  if (res[1]!=0) res[1][3]=a27;
  a29=(a29+a29);
  a36=(a00*a36);
  a29=(a29*a36);
  if (res[1]!=0) res[1][4]=a29;
  a30=(a30+a30);
  a32=(a00*a32);
  a30=(a30*a32);
  if (res[1]!=0) res[1][5]=a30;
  a31=(a31+a31);
  a34=(a00*a34);
  a31=(a31*a34);
  if (res[1]!=0) res[1][6]=a31;
  a37=(a37+a37);
  a02=(a00*a02);
  a37=(a37*a02);
  if (res[1]!=0) res[1][7]=a37;
  a35=(a35+a35);
  a33=(a00*a33);
  a35=(a35*a33);
  if (res[1]!=0) res[1][8]=a35;
  a39=(a39+a39);
  a38=(a00*a38);
  a39=(a39*a38);
  if (res[1]!=0) res[1][9]=a39;
  a41=(a41+a41);
  a40=(a00*a40);
  a41=(a41*a40);
  if (res[1]!=0) res[1][10]=a41;
  a43=(a43+a43);
  a42=(a00*a42);
  a43=(a43*a42);
  if (res[1]!=0) res[1][11]=a43;
  a07=(a07+a07);
  a00=(a00*a03);
  a07=(a07*a00);
  if (res[1]!=0) res[1][12]=a07;
  a04=(a05*a04);
  if (res[2]!=0) res[2][0]=a04;
  a22=(a05*a22);
  if (res[2]!=0) res[2][1]=a22;
  a24=(a05*a24);
  if (res[2]!=0) res[2][2]=a24;
  a26=(a05*a26);
  if (res[2]!=0) res[2][3]=a26;
  if (res[2]!=0) res[2][4]=a28;
  if (res[2]!=0) res[2][5]=a28;
  if (res[2]!=0) res[2][6]=a28;
  if (res[2]!=0) res[2][7]=a28;
  a36=(a05*a36);
  if (res[2]!=0) res[2][8]=a36;
  if (res[2]!=0) res[2][9]=a28;
  if (res[2]!=0) res[2][10]=a28;
  if (res[2]!=0) res[2][11]=a28;
  if (res[2]!=0) res[2][12]=a28;
  a32=(a05*a32);
  if (res[2]!=0) res[2][13]=a32;
  if (res[2]!=0) res[2][14]=a28;
  if (res[2]!=0) res[2][15]=a28;
  if (res[2]!=0) res[2][16]=a28;
  if (res[2]!=0) res[2][17]=a28;
  a34=(a05*a34);
  if (res[2]!=0) res[2][18]=a34;
  a02=(a05*a02);
  if (res[2]!=0) res[2][19]=a02;
  a33=(a05*a33);
  if (res[2]!=0) res[2][20]=a33;
  a38=(a05*a38);
  if (res[2]!=0) res[2][21]=a38;
  a40=(a05*a40);
  if (res[2]!=0) res[2][22]=a40;
  a42=(a05*a42);
  if (res[2]!=0) res[2][23]=a42;
  a05=(a05*a00);
  if (res[2]!=0) res[2][24]=a05;
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
