/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pypose_mpc_alloc_tv_cost_ext_cost_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[3] = {411, 1, 1};

/* pypose_mpc_alloc_tv_cost_ext_cost_fun:(i0[13],i1[6],i2[0],i3,i4[411])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=5.0000000000000000e-01;
  a01=-200.;
  a02=arg[3]? arg[3][0] : 0;
  a03=(a01*a02);
  a03=(a03*a02);
  a03=exp(a03);
  a04=arg[4]? arg[4][0] : 0;
  a04=(a03*a04);
  a05=1.;
  a05=(a02-a05);
  a06=(a01*a05);
  a06=(a06*a05);
  a06=exp(a06);
  a05=arg[4]? arg[4][1] : 0;
  a05=(a06*a05);
  a04=(a04+a05);
  a05=2.;
  a05=(a02-a05);
  a07=(a01*a05);
  a07=(a07*a05);
  a07=exp(a07);
  a05=arg[4]? arg[4][2] : 0;
  a05=(a07*a05);
  a04=(a04+a05);
  a05=3.;
  a05=(a02-a05);
  a08=(a01*a05);
  a08=(a08*a05);
  a08=exp(a08);
  a05=arg[4]? arg[4][3] : 0;
  a05=(a08*a05);
  a04=(a04+a05);
  a05=4.;
  a05=(a02-a05);
  a09=(a01*a05);
  a09=(a09*a05);
  a09=exp(a09);
  a05=arg[4]? arg[4][4] : 0;
  a05=(a09*a05);
  a04=(a04+a05);
  a05=5.;
  a05=(a02-a05);
  a10=(a01*a05);
  a10=(a10*a05);
  a10=exp(a10);
  a05=arg[4]? arg[4][5] : 0;
  a05=(a10*a05);
  a04=(a04+a05);
  a05=6.;
  a05=(a02-a05);
  a11=(a01*a05);
  a11=(a11*a05);
  a11=exp(a11);
  a05=arg[4]? arg[4][6] : 0;
  a05=(a11*a05);
  a04=(a04+a05);
  a05=7.;
  a05=(a02-a05);
  a12=(a01*a05);
  a12=(a12*a05);
  a12=exp(a12);
  a05=arg[4]? arg[4][7] : 0;
  a05=(a12*a05);
  a04=(a04+a05);
  a05=8.;
  a05=(a02-a05);
  a13=(a01*a05);
  a13=(a13*a05);
  a13=exp(a13);
  a05=arg[4]? arg[4][8] : 0;
  a05=(a13*a05);
  a04=(a04+a05);
  a05=9.;
  a05=(a02-a05);
  a14=(a01*a05);
  a14=(a14*a05);
  a14=exp(a14);
  a05=arg[4]? arg[4][9] : 0;
  a05=(a14*a05);
  a04=(a04+a05);
  a05=10.;
  a05=(a02-a05);
  a15=(a01*a05);
  a15=(a15*a05);
  a15=exp(a15);
  a05=arg[4]? arg[4][10] : 0;
  a05=(a15*a05);
  a04=(a04+a05);
  a05=11.;
  a05=(a02-a05);
  a16=(a01*a05);
  a16=(a16*a05);
  a16=exp(a16);
  a05=arg[4]? arg[4][11] : 0;
  a05=(a16*a05);
  a04=(a04+a05);
  a05=12.;
  a05=(a02-a05);
  a17=(a01*a05);
  a17=(a17*a05);
  a17=exp(a17);
  a05=arg[4]? arg[4][12] : 0;
  a05=(a17*a05);
  a04=(a04+a05);
  a05=13.;
  a05=(a02-a05);
  a18=(a01*a05);
  a18=(a18*a05);
  a18=exp(a18);
  a05=arg[4]? arg[4][13] : 0;
  a05=(a18*a05);
  a04=(a04+a05);
  a05=14.;
  a02=(a02-a05);
  a01=(a01*a02);
  a01=(a01*a02);
  a01=exp(a01);
  a02=arg[4]? arg[4][14] : 0;
  a02=(a01*a02);
  a04=(a04+a02);
  a02=9.9999999999999998e-13;
  a05=(a02+a03);
  a05=(a05+a06);
  a05=(a05+a07);
  a05=(a05+a08);
  a05=(a05+a09);
  a05=(a05+a10);
  a05=(a05+a11);
  a05=(a05+a12);
  a05=(a05+a13);
  a05=(a05+a14);
  a05=(a05+a15);
  a05=(a05+a16);
  a05=(a05+a17);
  a05=(a05+a18);
  a05=(a05+a01);
  a04=(a04/a05);
  a19=arg[0]? arg[0][0] : 0;
  a19=casadi_sq(a19);
  a04=(a04*a19);
  a19=arg[4]? arg[4][15] : 0;
  a19=(a03*a19);
  a20=arg[4]? arg[4][16] : 0;
  a20=(a06*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][17] : 0;
  a20=(a07*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][18] : 0;
  a20=(a08*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][19] : 0;
  a20=(a09*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][20] : 0;
  a20=(a10*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][21] : 0;
  a20=(a11*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][22] : 0;
  a20=(a12*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][23] : 0;
  a20=(a13*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][24] : 0;
  a20=(a14*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][25] : 0;
  a20=(a15*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][26] : 0;
  a20=(a16*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][27] : 0;
  a20=(a17*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][28] : 0;
  a20=(a18*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][29] : 0;
  a20=(a01*a20);
  a19=(a19+a20);
  a19=(a19/a05);
  a20=arg[0]? arg[0][1] : 0;
  a20=casadi_sq(a20);
  a19=(a19*a20);
  a04=(a04+a19);
  a19=arg[4]? arg[4][30] : 0;
  a19=(a03*a19);
  a20=arg[4]? arg[4][31] : 0;
  a20=(a06*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][32] : 0;
  a20=(a07*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][33] : 0;
  a20=(a08*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][34] : 0;
  a20=(a09*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][35] : 0;
  a20=(a10*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][36] : 0;
  a20=(a11*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][37] : 0;
  a20=(a12*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][38] : 0;
  a20=(a13*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][39] : 0;
  a20=(a14*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][40] : 0;
  a20=(a15*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][41] : 0;
  a20=(a16*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][42] : 0;
  a20=(a17*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][43] : 0;
  a20=(a18*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][44] : 0;
  a20=(a01*a20);
  a19=(a19+a20);
  a19=(a19/a05);
  a20=arg[0]? arg[0][2] : 0;
  a20=casadi_sq(a20);
  a19=(a19*a20);
  a04=(a04+a19);
  a19=arg[4]? arg[4][45] : 0;
  a19=(a03*a19);
  a20=arg[4]? arg[4][46] : 0;
  a20=(a06*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][47] : 0;
  a20=(a07*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][48] : 0;
  a20=(a08*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][49] : 0;
  a20=(a09*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][50] : 0;
  a20=(a10*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][51] : 0;
  a20=(a11*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][52] : 0;
  a20=(a12*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][53] : 0;
  a20=(a13*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][54] : 0;
  a20=(a14*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][55] : 0;
  a20=(a15*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][56] : 0;
  a20=(a16*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][57] : 0;
  a20=(a17*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][58] : 0;
  a20=(a18*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][59] : 0;
  a20=(a01*a20);
  a19=(a19+a20);
  a19=(a19/a05);
  a20=arg[0]? arg[0][3] : 0;
  a21=casadi_sq(a20);
  a22=arg[0]? arg[0][4] : 0;
  a23=casadi_sq(a22);
  a21=(a21+a23);
  a23=arg[0]? arg[0][5] : 0;
  a24=casadi_sq(a23);
  a21=(a21+a24);
  a24=arg[0]? arg[0][6] : 0;
  a25=casadi_sq(a24);
  a21=(a21+a25);
  a21=(a21+a02);
  a21=sqrt(a21);
  a02=(a20/a21);
  a25=arg[4]? arg[4][327] : 0;
  a02=(a02*a25);
  a26=(a22/a21);
  a27=arg[4]? arg[4][328] : 0;
  a26=(a26*a27);
  a02=(a02+a26);
  a26=(a23/a21);
  a28=arg[4]? arg[4][329] : 0;
  a26=(a26*a28);
  a02=(a02+a26);
  a21=(a24/a21);
  a26=arg[4]? arg[4][330] : 0;
  a21=(a21*a26);
  a02=(a02+a21);
  a21=0.;
  a02=(a02<a21);
  a21=arg[4]? arg[4][331] : 0;
  a21=(a02?a21:0);
  a29=(!a02);
  a25=(a29?a25:0);
  a21=(a21+a25);
  a20=(a20-a21);
  a20=casadi_sq(a20);
  a19=(a19*a20);
  a04=(a04+a19);
  a19=arg[4]? arg[4][65] : 0;
  a19=(a03*a19);
  a20=arg[4]? arg[4][66] : 0;
  a20=(a06*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][67] : 0;
  a20=(a07*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][68] : 0;
  a20=(a08*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][69] : 0;
  a20=(a09*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][70] : 0;
  a20=(a10*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][71] : 0;
  a20=(a11*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][72] : 0;
  a20=(a12*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][73] : 0;
  a20=(a13*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][74] : 0;
  a20=(a14*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][75] : 0;
  a20=(a15*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][76] : 0;
  a20=(a16*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][77] : 0;
  a20=(a17*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][78] : 0;
  a20=(a18*a20);
  a19=(a19+a20);
  a20=arg[4]? arg[4][79] : 0;
  a20=(a01*a20);
  a19=(a19+a20);
  a19=(a19/a05);
  a20=arg[4]? arg[4][332] : 0;
  a20=(a02?a20:0);
  a27=(a29?a27:0);
  a20=(a20+a27);
  a22=(a22-a20);
  a22=casadi_sq(a22);
  a19=(a19*a22);
  a04=(a04+a19);
  a19=arg[4]? arg[4][81] : 0;
  a19=(a03*a19);
  a22=arg[4]? arg[4][82] : 0;
  a22=(a06*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][83] : 0;
  a22=(a07*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][84] : 0;
  a22=(a08*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][85] : 0;
  a22=(a09*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][86] : 0;
  a22=(a10*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][87] : 0;
  a22=(a11*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][88] : 0;
  a22=(a12*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][89] : 0;
  a22=(a13*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][90] : 0;
  a22=(a14*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][91] : 0;
  a22=(a15*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][92] : 0;
  a22=(a16*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][93] : 0;
  a22=(a17*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][94] : 0;
  a22=(a18*a22);
  a19=(a19+a22);
  a22=arg[4]? arg[4][95] : 0;
  a22=(a01*a22);
  a19=(a19+a22);
  a19=(a19/a05);
  a22=arg[4]? arg[4][333] : 0;
  a22=(a02?a22:0);
  a28=(a29?a28:0);
  a22=(a22+a28);
  a23=(a23-a22);
  a23=casadi_sq(a23);
  a19=(a19*a23);
  a04=(a04+a19);
  a19=arg[4]? arg[4][97] : 0;
  a19=(a03*a19);
  a23=arg[4]? arg[4][98] : 0;
  a23=(a06*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][99] : 0;
  a23=(a07*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][100] : 0;
  a23=(a08*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][101] : 0;
  a23=(a09*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][102] : 0;
  a23=(a10*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][103] : 0;
  a23=(a11*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][104] : 0;
  a23=(a12*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][105] : 0;
  a23=(a13*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][106] : 0;
  a23=(a14*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][107] : 0;
  a23=(a15*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][108] : 0;
  a23=(a16*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][109] : 0;
  a23=(a17*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][110] : 0;
  a23=(a18*a23);
  a19=(a19+a23);
  a23=arg[4]? arg[4][111] : 0;
  a23=(a01*a23);
  a19=(a19+a23);
  a19=(a19/a05);
  a23=arg[4]? arg[4][334] : 0;
  a02=(a02?a23:0);
  a29=(a29?a26:0);
  a02=(a02+a29);
  a24=(a24-a02);
  a24=casadi_sq(a24);
  a19=(a19*a24);
  a04=(a04+a19);
  a19=arg[4]? arg[4][113] : 0;
  a19=(a03*a19);
  a24=arg[4]? arg[4][114] : 0;
  a24=(a06*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][115] : 0;
  a24=(a07*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][116] : 0;
  a24=(a08*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][117] : 0;
  a24=(a09*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][118] : 0;
  a24=(a10*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][119] : 0;
  a24=(a11*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][120] : 0;
  a24=(a12*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][121] : 0;
  a24=(a13*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][122] : 0;
  a24=(a14*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][123] : 0;
  a24=(a15*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][124] : 0;
  a24=(a16*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][125] : 0;
  a24=(a17*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][126] : 0;
  a24=(a18*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][127] : 0;
  a24=(a01*a24);
  a19=(a19+a24);
  a19=(a19/a05);
  a24=arg[0]? arg[0][7] : 0;
  a24=casadi_sq(a24);
  a19=(a19*a24);
  a04=(a04+a19);
  a19=arg[4]? arg[4][128] : 0;
  a19=(a03*a19);
  a24=arg[4]? arg[4][129] : 0;
  a24=(a06*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][130] : 0;
  a24=(a07*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][131] : 0;
  a24=(a08*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][132] : 0;
  a24=(a09*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][133] : 0;
  a24=(a10*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][134] : 0;
  a24=(a11*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][135] : 0;
  a24=(a12*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][136] : 0;
  a24=(a13*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][137] : 0;
  a24=(a14*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][138] : 0;
  a24=(a15*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][139] : 0;
  a24=(a16*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][140] : 0;
  a24=(a17*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][141] : 0;
  a24=(a18*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][142] : 0;
  a24=(a01*a24);
  a19=(a19+a24);
  a19=(a19/a05);
  a24=arg[0]? arg[0][8] : 0;
  a24=casadi_sq(a24);
  a19=(a19*a24);
  a04=(a04+a19);
  a19=arg[4]? arg[4][143] : 0;
  a19=(a03*a19);
  a24=arg[4]? arg[4][144] : 0;
  a24=(a06*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][145] : 0;
  a24=(a07*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][146] : 0;
  a24=(a08*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][147] : 0;
  a24=(a09*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][148] : 0;
  a24=(a10*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][149] : 0;
  a24=(a11*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][150] : 0;
  a24=(a12*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][151] : 0;
  a24=(a13*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][152] : 0;
  a24=(a14*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][153] : 0;
  a24=(a15*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][154] : 0;
  a24=(a16*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][155] : 0;
  a24=(a17*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][156] : 0;
  a24=(a18*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][157] : 0;
  a24=(a01*a24);
  a19=(a19+a24);
  a19=(a19/a05);
  a24=arg[0]? arg[0][9] : 0;
  a24=casadi_sq(a24);
  a19=(a19*a24);
  a04=(a04+a19);
  a19=arg[4]? arg[4][158] : 0;
  a19=(a03*a19);
  a24=arg[4]? arg[4][159] : 0;
  a24=(a06*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][160] : 0;
  a24=(a07*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][161] : 0;
  a24=(a08*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][162] : 0;
  a24=(a09*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][163] : 0;
  a24=(a10*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][164] : 0;
  a24=(a11*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][165] : 0;
  a24=(a12*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][166] : 0;
  a24=(a13*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][167] : 0;
  a24=(a14*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][168] : 0;
  a24=(a15*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][169] : 0;
  a24=(a16*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][170] : 0;
  a24=(a17*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][171] : 0;
  a24=(a18*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][172] : 0;
  a24=(a01*a24);
  a19=(a19+a24);
  a19=(a19/a05);
  a24=arg[0]? arg[0][10] : 0;
  a24=casadi_sq(a24);
  a19=(a19*a24);
  a04=(a04+a19);
  a19=arg[4]? arg[4][173] : 0;
  a19=(a03*a19);
  a24=arg[4]? arg[4][174] : 0;
  a24=(a06*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][175] : 0;
  a24=(a07*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][176] : 0;
  a24=(a08*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][177] : 0;
  a24=(a09*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][178] : 0;
  a24=(a10*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][179] : 0;
  a24=(a11*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][180] : 0;
  a24=(a12*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][181] : 0;
  a24=(a13*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][182] : 0;
  a24=(a14*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][183] : 0;
  a24=(a15*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][184] : 0;
  a24=(a16*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][185] : 0;
  a24=(a17*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][186] : 0;
  a24=(a18*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][187] : 0;
  a24=(a01*a24);
  a19=(a19+a24);
  a19=(a19/a05);
  a24=arg[0]? arg[0][11] : 0;
  a24=casadi_sq(a24);
  a19=(a19*a24);
  a04=(a04+a19);
  a19=arg[4]? arg[4][188] : 0;
  a19=(a03*a19);
  a24=arg[4]? arg[4][189] : 0;
  a24=(a06*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][190] : 0;
  a24=(a07*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][191] : 0;
  a24=(a08*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][192] : 0;
  a24=(a09*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][193] : 0;
  a24=(a10*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][194] : 0;
  a24=(a11*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][195] : 0;
  a24=(a12*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][196] : 0;
  a24=(a13*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][197] : 0;
  a24=(a14*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][198] : 0;
  a24=(a15*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][199] : 0;
  a24=(a16*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][200] : 0;
  a24=(a17*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][201] : 0;
  a24=(a18*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][202] : 0;
  a24=(a01*a24);
  a19=(a19+a24);
  a19=(a19/a05);
  a24=arg[0]? arg[0][12] : 0;
  a24=casadi_sq(a24);
  a19=(a19*a24);
  a04=(a04+a19);
  a19=arg[4]? arg[4][203] : 0;
  a19=(a03*a19);
  a24=arg[4]? arg[4][204] : 0;
  a24=(a06*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][205] : 0;
  a24=(a07*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][206] : 0;
  a24=(a08*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][207] : 0;
  a24=(a09*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][208] : 0;
  a24=(a10*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][209] : 0;
  a24=(a11*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][210] : 0;
  a24=(a12*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][211] : 0;
  a24=(a13*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][212] : 0;
  a24=(a14*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][213] : 0;
  a24=(a15*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][214] : 0;
  a24=(a16*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][215] : 0;
  a24=(a17*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][216] : 0;
  a24=(a18*a24);
  a19=(a19+a24);
  a24=arg[4]? arg[4][217] : 0;
  a24=(a01*a24);
  a19=(a19+a24);
  a19=(a19/a05);
  a24=arg[1]? arg[1][0] : 0;
  a24=casadi_sq(a24);
  a19=(a19*a24);
  a24=arg[4]? arg[4][218] : 0;
  a24=(a03*a24);
  a02=arg[4]? arg[4][219] : 0;
  a02=(a06*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][220] : 0;
  a02=(a07*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][221] : 0;
  a02=(a08*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][222] : 0;
  a02=(a09*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][223] : 0;
  a02=(a10*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][224] : 0;
  a02=(a11*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][225] : 0;
  a02=(a12*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][226] : 0;
  a02=(a13*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][227] : 0;
  a02=(a14*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][228] : 0;
  a02=(a15*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][229] : 0;
  a02=(a16*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][230] : 0;
  a02=(a17*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][231] : 0;
  a02=(a18*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][232] : 0;
  a02=(a01*a02);
  a24=(a24+a02);
  a24=(a24/a05);
  a02=arg[1]? arg[1][1] : 0;
  a02=casadi_sq(a02);
  a24=(a24*a02);
  a19=(a19+a24);
  a24=arg[4]? arg[4][233] : 0;
  a24=(a03*a24);
  a02=arg[4]? arg[4][234] : 0;
  a02=(a06*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][235] : 0;
  a02=(a07*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][236] : 0;
  a02=(a08*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][237] : 0;
  a02=(a09*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][238] : 0;
  a02=(a10*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][239] : 0;
  a02=(a11*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][240] : 0;
  a02=(a12*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][241] : 0;
  a02=(a13*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][242] : 0;
  a02=(a14*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][243] : 0;
  a02=(a15*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][244] : 0;
  a02=(a16*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][245] : 0;
  a02=(a17*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][246] : 0;
  a02=(a18*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][247] : 0;
  a02=(a01*a02);
  a24=(a24+a02);
  a24=(a24/a05);
  a02=arg[1]? arg[1][2] : 0;
  a02=casadi_sq(a02);
  a24=(a24*a02);
  a19=(a19+a24);
  a24=arg[4]? arg[4][248] : 0;
  a24=(a03*a24);
  a02=arg[4]? arg[4][249] : 0;
  a02=(a06*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][250] : 0;
  a02=(a07*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][251] : 0;
  a02=(a08*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][252] : 0;
  a02=(a09*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][253] : 0;
  a02=(a10*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][254] : 0;
  a02=(a11*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][255] : 0;
  a02=(a12*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][256] : 0;
  a02=(a13*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][257] : 0;
  a02=(a14*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][258] : 0;
  a02=(a15*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][259] : 0;
  a02=(a16*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][260] : 0;
  a02=(a17*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][261] : 0;
  a02=(a18*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][262] : 0;
  a02=(a01*a02);
  a24=(a24+a02);
  a24=(a24/a05);
  a02=arg[1]? arg[1][3] : 0;
  a02=casadi_sq(a02);
  a24=(a24*a02);
  a19=(a19+a24);
  a24=arg[4]? arg[4][263] : 0;
  a24=(a03*a24);
  a02=arg[4]? arg[4][264] : 0;
  a02=(a06*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][265] : 0;
  a02=(a07*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][266] : 0;
  a02=(a08*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][267] : 0;
  a02=(a09*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][268] : 0;
  a02=(a10*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][269] : 0;
  a02=(a11*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][270] : 0;
  a02=(a12*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][271] : 0;
  a02=(a13*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][272] : 0;
  a02=(a14*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][273] : 0;
  a02=(a15*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][274] : 0;
  a02=(a16*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][275] : 0;
  a02=(a17*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][276] : 0;
  a02=(a18*a02);
  a24=(a24+a02);
  a02=arg[4]? arg[4][277] : 0;
  a02=(a01*a02);
  a24=(a24+a02);
  a24=(a24/a05);
  a02=arg[1]? arg[1][4] : 0;
  a02=casadi_sq(a02);
  a24=(a24*a02);
  a19=(a19+a24);
  a24=arg[4]? arg[4][278] : 0;
  a03=(a03*a24);
  a24=arg[4]? arg[4][279] : 0;
  a06=(a06*a24);
  a03=(a03+a06);
  a06=arg[4]? arg[4][280] : 0;
  a07=(a07*a06);
  a03=(a03+a07);
  a07=arg[4]? arg[4][281] : 0;
  a08=(a08*a07);
  a03=(a03+a08);
  a08=arg[4]? arg[4][282] : 0;
  a09=(a09*a08);
  a03=(a03+a09);
  a09=arg[4]? arg[4][283] : 0;
  a10=(a10*a09);
  a03=(a03+a10);
  a10=arg[4]? arg[4][284] : 0;
  a11=(a11*a10);
  a03=(a03+a11);
  a11=arg[4]? arg[4][285] : 0;
  a12=(a12*a11);
  a03=(a03+a12);
  a12=arg[4]? arg[4][286] : 0;
  a13=(a13*a12);
  a03=(a03+a13);
  a13=arg[4]? arg[4][287] : 0;
  a14=(a14*a13);
  a03=(a03+a14);
  a14=arg[4]? arg[4][288] : 0;
  a15=(a15*a14);
  a03=(a03+a15);
  a15=arg[4]? arg[4][289] : 0;
  a16=(a16*a15);
  a03=(a03+a16);
  a16=arg[4]? arg[4][290] : 0;
  a17=(a17*a16);
  a03=(a03+a17);
  a17=arg[4]? arg[4][291] : 0;
  a18=(a18*a17);
  a03=(a03+a18);
  a18=arg[4]? arg[4][292] : 0;
  a01=(a01*a18);
  a03=(a03+a01);
  a03=(a03/a05);
  a05=arg[1]? arg[1][5] : 0;
  a05=casadi_sq(a05);
  a03=(a03*a05);
  a19=(a19+a03);
  a04=(a04+a19);
  a00=(a00*a04);
  if (res[0]!=0) res[0][0]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pypose_mpc_alloc_tv_cost_ext_cost_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int pypose_mpc_alloc_tv_cost_ext_cost_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pypose_mpc_alloc_tv_cost_ext_cost_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pypose_mpc_alloc_tv_cost_ext_cost_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pypose_mpc_alloc_tv_cost_ext_cost_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pypose_mpc_alloc_tv_cost_ext_cost_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pypose_mpc_alloc_tv_cost_ext_cost_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
