/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};
static const casadi_int casadi_s4[3] = {411, 1, 1};
static const casadi_int casadi_s5[593] = 
  {19, 289, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28, 29,
  30, 31, 32, 33, 34, 35, 36, 37,
  38, 39, 40, 41, 42, 43, 44, 45,
  46, 47, 48, 49, 50, 51, 52, 53,
  54, 55, 56, 57, 58, 59, 60, 61,
  62, 63, 64, 65, 66, 67, 68, 69,
  70, 71, 72, 73, 74, 75, 76, 77,
  78, 79, 80, 81, 82, 83, 84, 85,
  86, 87, 88, 89, 90, 91, 92, 93,
  94, 95, 96, 97, 98, 99, 100, 101,
  102, 103, 104, 105, 106, 107, 108, 109,
  110, 111, 112, 113, 114, 115, 116, 117,
  118, 119, 120, 121, 122, 123, 124, 125,
  126, 127, 128, 129, 130, 131, 132, 133,
  134, 135, 136, 137, 138, 139, 140, 141,
  142, 143, 144, 145, 146, 147, 148, 149,
  150, 151, 152, 153, 154, 155, 156, 157,
  158, 159, 160, 161, 162, 163, 164, 165,
  166, 167, 168, 169, 170, 171, 172, 173,
  174, 175, 176, 177, 178, 179, 180, 181,
  182, 183, 184, 185, 186, 187, 188, 189,
  190, 191, 192, 193, 194, 195, 196, 197,
  198, 199, 200, 201, 202, 203, 204, 205,
  206, 207, 208, 209, 210, 211, 212, 213,
  214, 215, 216, 217, 218, 219, 220, 221,
  222, 223, 224, 225, 226, 227, 228, 229,
  230, 231, 232, 233, 234, 235, 236, 237,
  238, 239, 240, 241, 242, 243, 244, 245,
  246, 247, 248, 249, 250, 251, 252, 253,
  254, 255, 256, 257, 258, 259, 260, 261,
  262, 263, 264, 265, 266, 267, 268, 269,
  270, 271, 272, 273, 274, 275, 276, 277,
  278, 279, 280, 281, 282, 283, 284, 285,
  289, 293, 297, 301, 6, 7, 8, 9,
  10, 11, 12, 13, 14, 15, 16, 17,
  18, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16, 17, 18, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12, 13, 14, 15, 16, 17, 18, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 12, 13, 14, 15, 16, 17, 18,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 0, 1, 2, 3, 4,
  5, 6, 7, 8, 9, 10, 11, 12,
  13, 14, 15, 16, 17, 18, 0, 1,
  2, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 12, 13, 14, 15, 16, 17,
  18, 0, 1, 2, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16, 17, 18, 0, 1, 2, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12, 13, 14, 15, 16, 17, 18, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  14, 15, 16, 17, 18, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9, 10,
  11, 12, 13, 14, 15, 16, 17, 18,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 0, 1, 2, 3, 4,
  5, 9, 10, 11, 12, 9, 10, 11,
  12, 9, 10, 11, 12, 9, 10, 11,
  12};

/* pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p:(i0[13],i1[6],i2[0],i3,i4[411])->(o0[19x289,301nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37;
  a00=-200.;
  a01=arg[3]? arg[3][0] : 0;
  a02=(a00*a01);
  a02=(a02*a01);
  a02=exp(a02);
  a03=5.0000000000000000e-01;
  a04=arg[0]? arg[0][0] : 0;
  a04=(a04+a04);
  a04=(a03*a04);
  a05=9.9999999999999998e-13;
  a06=(a05+a02);
  a07=1.;
  a07=(a01-a07);
  a08=(a00*a07);
  a08=(a08*a07);
  a08=exp(a08);
  a06=(a06+a08);
  a07=2.;
  a07=(a01-a07);
  a09=(a00*a07);
  a09=(a09*a07);
  a09=exp(a09);
  a06=(a06+a09);
  a07=3.;
  a07=(a01-a07);
  a10=(a00*a07);
  a10=(a10*a07);
  a10=exp(a10);
  a06=(a06+a10);
  a07=4.;
  a07=(a01-a07);
  a11=(a00*a07);
  a11=(a11*a07);
  a11=exp(a11);
  a06=(a06+a11);
  a07=5.;
  a07=(a01-a07);
  a12=(a00*a07);
  a12=(a12*a07);
  a12=exp(a12);
  a06=(a06+a12);
  a07=6.;
  a07=(a01-a07);
  a13=(a00*a07);
  a13=(a13*a07);
  a13=exp(a13);
  a06=(a06+a13);
  a07=7.;
  a07=(a01-a07);
  a14=(a00*a07);
  a14=(a14*a07);
  a14=exp(a14);
  a06=(a06+a14);
  a07=8.;
  a07=(a01-a07);
  a15=(a00*a07);
  a15=(a15*a07);
  a15=exp(a15);
  a06=(a06+a15);
  a07=9.;
  a07=(a01-a07);
  a16=(a00*a07);
  a16=(a16*a07);
  a16=exp(a16);
  a06=(a06+a16);
  a07=10.;
  a07=(a01-a07);
  a17=(a00*a07);
  a17=(a17*a07);
  a17=exp(a17);
  a06=(a06+a17);
  a07=11.;
  a07=(a01-a07);
  a18=(a00*a07);
  a18=(a18*a07);
  a18=exp(a18);
  a06=(a06+a18);
  a07=12.;
  a07=(a01-a07);
  a19=(a00*a07);
  a19=(a19*a07);
  a19=exp(a19);
  a06=(a06+a19);
  a07=13.;
  a07=(a01-a07);
  a20=(a00*a07);
  a20=(a20*a07);
  a20=exp(a20);
  a06=(a06+a20);
  a07=14.;
  a01=(a01-a07);
  a00=(a00*a01);
  a00=(a00*a01);
  a00=exp(a00);
  a06=(a06+a00);
  a04=(a04/a06);
  a01=(a02*a04);
  if (res[0]!=0) res[0][0]=a01;
  a01=arg[0]? arg[0][1] : 0;
  a01=(a01+a01);
  a01=(a03*a01);
  a01=(a01/a06);
  a07=(a02*a01);
  if (res[0]!=0) res[0][1]=a07;
  a07=arg[0]? arg[0][2] : 0;
  a07=(a07+a07);
  a07=(a03*a07);
  a07=(a07/a06);
  a21=(a02*a07);
  if (res[0]!=0) res[0][2]=a21;
  a21=arg[0]? arg[0][3] : 0;
  a22=casadi_sq(a21);
  a23=arg[0]? arg[0][4] : 0;
  a24=casadi_sq(a23);
  a22=(a22+a24);
  a24=arg[0]? arg[0][5] : 0;
  a25=casadi_sq(a24);
  a22=(a22+a25);
  a25=arg[0]? arg[0][6] : 0;
  a26=casadi_sq(a25);
  a22=(a22+a26);
  a22=(a22+a05);
  a22=sqrt(a22);
  a05=(a21/a22);
  a26=arg[4]? arg[4][351] : 0;
  a05=(a05*a26);
  a27=(a23/a22);
  a28=arg[4]? arg[4][352] : 0;
  a27=(a27*a28);
  a05=(a05+a27);
  a27=(a24/a22);
  a29=arg[4]? arg[4][353] : 0;
  a27=(a27*a29);
  a05=(a05+a27);
  a22=(a25/a22);
  a27=arg[4]? arg[4][354] : 0;
  a22=(a22*a27);
  a05=(a05+a22);
  a22=0.;
  a05=(a05<a22);
  a22=arg[4]? arg[4][355] : 0;
  a22=(a05?a22:0);
  a30=(!a05);
  a26=(a30?a26:0);
  a22=(a22+a26);
  a21=(a21-a22);
  a21=(a21+a21);
  a21=(a03*a21);
  a21=(a21/a06);
  a22=(a02*a21);
  if (res[0]!=0) res[0][3]=a22;
  a22=arg[4]? arg[4][356] : 0;
  a22=(a05?a22:0);
  a28=(a30?a28:0);
  a22=(a22+a28);
  a23=(a23-a22);
  a23=(a23+a23);
  a23=(a03*a23);
  a23=(a23/a06);
  a22=(a02*a23);
  if (res[0]!=0) res[0][4]=a22;
  a22=arg[4]? arg[4][357] : 0;
  a22=(a05?a22:0);
  a29=(a30?a29:0);
  a22=(a22+a29);
  a24=(a24-a22);
  a24=(a24+a24);
  a24=(a03*a24);
  a24=(a24/a06);
  a22=(a02*a24);
  if (res[0]!=0) res[0][5]=a22;
  a22=arg[4]? arg[4][358] : 0;
  a22=(a05?a22:0);
  a27=(a30?a27:0);
  a22=(a22+a27);
  a25=(a25-a22);
  a25=(a25+a25);
  a25=(a03*a25);
  a25=(a25/a06);
  a22=(a02*a25);
  if (res[0]!=0) res[0][6]=a22;
  a22=arg[0]? arg[0][7] : 0;
  a22=(a22+a22);
  a22=(a03*a22);
  a22=(a22/a06);
  a27=(a02*a22);
  if (res[0]!=0) res[0][7]=a27;
  a27=arg[0]? arg[0][8] : 0;
  a27=(a27+a27);
  a27=(a03*a27);
  a27=(a27/a06);
  a29=(a02*a27);
  if (res[0]!=0) res[0][8]=a29;
  a29=arg[0]? arg[0][9] : 0;
  a29=(a29+a29);
  a29=(a03*a29);
  a29=(a29/a06);
  a28=(a02*a29);
  if (res[0]!=0) res[0][9]=a28;
  a28=arg[0]? arg[0][10] : 0;
  a28=(a28+a28);
  a28=(a03*a28);
  a28=(a28/a06);
  a26=(a02*a28);
  if (res[0]!=0) res[0][10]=a26;
  a26=arg[0]? arg[0][11] : 0;
  a26=(a26+a26);
  a26=(a03*a26);
  a26=(a26/a06);
  a31=(a02*a26);
  if (res[0]!=0) res[0][11]=a31;
  a31=arg[0]? arg[0][12] : 0;
  a31=(a31+a31);
  a31=(a03*a31);
  a31=(a31/a06);
  a32=(a02*a31);
  if (res[0]!=0) res[0][12]=a32;
  a32=arg[1]? arg[1][0] : 0;
  a32=(a32+a32);
  a32=(a03*a32);
  a32=(a32/a06);
  a33=(a02*a32);
  if (res[0]!=0) res[0][13]=a33;
  a33=arg[1]? arg[1][1] : 0;
  a33=(a33+a33);
  a33=(a03*a33);
  a33=(a33/a06);
  a34=(a02*a33);
  if (res[0]!=0) res[0][14]=a34;
  a34=arg[1]? arg[1][2] : 0;
  a34=(a34+a34);
  a34=(a03*a34);
  a34=(a34/a06);
  a35=(a02*a34);
  if (res[0]!=0) res[0][15]=a35;
  a35=arg[1]? arg[1][3] : 0;
  a35=(a35+a35);
  a35=(a03*a35);
  a35=(a35/a06);
  a36=(a02*a35);
  if (res[0]!=0) res[0][16]=a36;
  a36=arg[1]? arg[1][4] : 0;
  a36=(a36+a36);
  a36=(a03*a36);
  a36=(a36/a06);
  a37=(a02*a36);
  if (res[0]!=0) res[0][17]=a37;
  a37=arg[1]? arg[1][5] : 0;
  a37=(a37+a37);
  a03=(a03*a37);
  a03=(a03/a06);
  a37=(a02*a03);
  if (res[0]!=0) res[0][18]=a37;
  a37=(a08*a04);
  if (res[0]!=0) res[0][19]=a37;
  a37=(a08*a01);
  if (res[0]!=0) res[0][20]=a37;
  a37=(a08*a07);
  if (res[0]!=0) res[0][21]=a37;
  a37=(a08*a21);
  if (res[0]!=0) res[0][22]=a37;
  a37=(a08*a23);
  if (res[0]!=0) res[0][23]=a37;
  a37=(a08*a24);
  if (res[0]!=0) res[0][24]=a37;
  a37=(a08*a25);
  if (res[0]!=0) res[0][25]=a37;
  a37=(a08*a22);
  if (res[0]!=0) res[0][26]=a37;
  a37=(a08*a27);
  if (res[0]!=0) res[0][27]=a37;
  a37=(a08*a29);
  if (res[0]!=0) res[0][28]=a37;
  a37=(a08*a28);
  if (res[0]!=0) res[0][29]=a37;
  a37=(a08*a26);
  if (res[0]!=0) res[0][30]=a37;
  a37=(a08*a31);
  if (res[0]!=0) res[0][31]=a37;
  a37=(a08*a32);
  if (res[0]!=0) res[0][32]=a37;
  a37=(a08*a33);
  if (res[0]!=0) res[0][33]=a37;
  a37=(a08*a34);
  if (res[0]!=0) res[0][34]=a37;
  a37=(a08*a35);
  if (res[0]!=0) res[0][35]=a37;
  a37=(a08*a36);
  if (res[0]!=0) res[0][36]=a37;
  a37=(a08*a03);
  if (res[0]!=0) res[0][37]=a37;
  a37=(a09*a04);
  if (res[0]!=0) res[0][38]=a37;
  a37=(a09*a01);
  if (res[0]!=0) res[0][39]=a37;
  a37=(a09*a07);
  if (res[0]!=0) res[0][40]=a37;
  a37=(a09*a21);
  if (res[0]!=0) res[0][41]=a37;
  a37=(a09*a23);
  if (res[0]!=0) res[0][42]=a37;
  a37=(a09*a24);
  if (res[0]!=0) res[0][43]=a37;
  a37=(a09*a25);
  if (res[0]!=0) res[0][44]=a37;
  a37=(a09*a22);
  if (res[0]!=0) res[0][45]=a37;
  a37=(a09*a27);
  if (res[0]!=0) res[0][46]=a37;
  a37=(a09*a29);
  if (res[0]!=0) res[0][47]=a37;
  a37=(a09*a28);
  if (res[0]!=0) res[0][48]=a37;
  a37=(a09*a26);
  if (res[0]!=0) res[0][49]=a37;
  a37=(a09*a31);
  if (res[0]!=0) res[0][50]=a37;
  a37=(a09*a32);
  if (res[0]!=0) res[0][51]=a37;
  a37=(a09*a33);
  if (res[0]!=0) res[0][52]=a37;
  a37=(a09*a34);
  if (res[0]!=0) res[0][53]=a37;
  a37=(a09*a35);
  if (res[0]!=0) res[0][54]=a37;
  a37=(a09*a36);
  if (res[0]!=0) res[0][55]=a37;
  a37=(a09*a03);
  if (res[0]!=0) res[0][56]=a37;
  a37=(a10*a04);
  if (res[0]!=0) res[0][57]=a37;
  a37=(a10*a01);
  if (res[0]!=0) res[0][58]=a37;
  a37=(a10*a07);
  if (res[0]!=0) res[0][59]=a37;
  a37=(a10*a21);
  if (res[0]!=0) res[0][60]=a37;
  a37=(a10*a23);
  if (res[0]!=0) res[0][61]=a37;
  a37=(a10*a24);
  if (res[0]!=0) res[0][62]=a37;
  a37=(a10*a25);
  if (res[0]!=0) res[0][63]=a37;
  a37=(a10*a22);
  if (res[0]!=0) res[0][64]=a37;
  a37=(a10*a27);
  if (res[0]!=0) res[0][65]=a37;
  a37=(a10*a29);
  if (res[0]!=0) res[0][66]=a37;
  a37=(a10*a28);
  if (res[0]!=0) res[0][67]=a37;
  a37=(a10*a26);
  if (res[0]!=0) res[0][68]=a37;
  a37=(a10*a31);
  if (res[0]!=0) res[0][69]=a37;
  a37=(a10*a32);
  if (res[0]!=0) res[0][70]=a37;
  a37=(a10*a33);
  if (res[0]!=0) res[0][71]=a37;
  a37=(a10*a34);
  if (res[0]!=0) res[0][72]=a37;
  a37=(a10*a35);
  if (res[0]!=0) res[0][73]=a37;
  a37=(a10*a36);
  if (res[0]!=0) res[0][74]=a37;
  a37=(a10*a03);
  if (res[0]!=0) res[0][75]=a37;
  a37=(a11*a04);
  if (res[0]!=0) res[0][76]=a37;
  a37=(a11*a01);
  if (res[0]!=0) res[0][77]=a37;
  a37=(a11*a07);
  if (res[0]!=0) res[0][78]=a37;
  a37=(a11*a21);
  if (res[0]!=0) res[0][79]=a37;
  a37=(a11*a23);
  if (res[0]!=0) res[0][80]=a37;
  a37=(a11*a24);
  if (res[0]!=0) res[0][81]=a37;
  a37=(a11*a25);
  if (res[0]!=0) res[0][82]=a37;
  a37=(a11*a22);
  if (res[0]!=0) res[0][83]=a37;
  a37=(a11*a27);
  if (res[0]!=0) res[0][84]=a37;
  a37=(a11*a29);
  if (res[0]!=0) res[0][85]=a37;
  a37=(a11*a28);
  if (res[0]!=0) res[0][86]=a37;
  a37=(a11*a26);
  if (res[0]!=0) res[0][87]=a37;
  a37=(a11*a31);
  if (res[0]!=0) res[0][88]=a37;
  a37=(a11*a32);
  if (res[0]!=0) res[0][89]=a37;
  a37=(a11*a33);
  if (res[0]!=0) res[0][90]=a37;
  a37=(a11*a34);
  if (res[0]!=0) res[0][91]=a37;
  a37=(a11*a35);
  if (res[0]!=0) res[0][92]=a37;
  a37=(a11*a36);
  if (res[0]!=0) res[0][93]=a37;
  a37=(a11*a03);
  if (res[0]!=0) res[0][94]=a37;
  a37=(a12*a04);
  if (res[0]!=0) res[0][95]=a37;
  a37=(a12*a01);
  if (res[0]!=0) res[0][96]=a37;
  a37=(a12*a07);
  if (res[0]!=0) res[0][97]=a37;
  a37=(a12*a21);
  if (res[0]!=0) res[0][98]=a37;
  a37=(a12*a23);
  if (res[0]!=0) res[0][99]=a37;
  a37=(a12*a24);
  if (res[0]!=0) res[0][100]=a37;
  a37=(a12*a25);
  if (res[0]!=0) res[0][101]=a37;
  a37=(a12*a22);
  if (res[0]!=0) res[0][102]=a37;
  a37=(a12*a27);
  if (res[0]!=0) res[0][103]=a37;
  a37=(a12*a29);
  if (res[0]!=0) res[0][104]=a37;
  a37=(a12*a28);
  if (res[0]!=0) res[0][105]=a37;
  a37=(a12*a26);
  if (res[0]!=0) res[0][106]=a37;
  a37=(a12*a31);
  if (res[0]!=0) res[0][107]=a37;
  a37=(a12*a32);
  if (res[0]!=0) res[0][108]=a37;
  a37=(a12*a33);
  if (res[0]!=0) res[0][109]=a37;
  a37=(a12*a34);
  if (res[0]!=0) res[0][110]=a37;
  a37=(a12*a35);
  if (res[0]!=0) res[0][111]=a37;
  a37=(a12*a36);
  if (res[0]!=0) res[0][112]=a37;
  a37=(a12*a03);
  if (res[0]!=0) res[0][113]=a37;
  a37=(a13*a04);
  if (res[0]!=0) res[0][114]=a37;
  a37=(a13*a01);
  if (res[0]!=0) res[0][115]=a37;
  a37=(a13*a07);
  if (res[0]!=0) res[0][116]=a37;
  a37=(a13*a21);
  if (res[0]!=0) res[0][117]=a37;
  a37=(a13*a23);
  if (res[0]!=0) res[0][118]=a37;
  a37=(a13*a24);
  if (res[0]!=0) res[0][119]=a37;
  a37=(a13*a25);
  if (res[0]!=0) res[0][120]=a37;
  a37=(a13*a22);
  if (res[0]!=0) res[0][121]=a37;
  a37=(a13*a27);
  if (res[0]!=0) res[0][122]=a37;
  a37=(a13*a29);
  if (res[0]!=0) res[0][123]=a37;
  a37=(a13*a28);
  if (res[0]!=0) res[0][124]=a37;
  a37=(a13*a26);
  if (res[0]!=0) res[0][125]=a37;
  a37=(a13*a31);
  if (res[0]!=0) res[0][126]=a37;
  a37=(a13*a32);
  if (res[0]!=0) res[0][127]=a37;
  a37=(a13*a33);
  if (res[0]!=0) res[0][128]=a37;
  a37=(a13*a34);
  if (res[0]!=0) res[0][129]=a37;
  a37=(a13*a35);
  if (res[0]!=0) res[0][130]=a37;
  a37=(a13*a36);
  if (res[0]!=0) res[0][131]=a37;
  a37=(a13*a03);
  if (res[0]!=0) res[0][132]=a37;
  a37=(a14*a04);
  if (res[0]!=0) res[0][133]=a37;
  a37=(a14*a01);
  if (res[0]!=0) res[0][134]=a37;
  a37=(a14*a07);
  if (res[0]!=0) res[0][135]=a37;
  a37=(a14*a21);
  if (res[0]!=0) res[0][136]=a37;
  a37=(a14*a23);
  if (res[0]!=0) res[0][137]=a37;
  a37=(a14*a24);
  if (res[0]!=0) res[0][138]=a37;
  a37=(a14*a25);
  if (res[0]!=0) res[0][139]=a37;
  a37=(a14*a22);
  if (res[0]!=0) res[0][140]=a37;
  a37=(a14*a27);
  if (res[0]!=0) res[0][141]=a37;
  a37=(a14*a29);
  if (res[0]!=0) res[0][142]=a37;
  a37=(a14*a28);
  if (res[0]!=0) res[0][143]=a37;
  a37=(a14*a26);
  if (res[0]!=0) res[0][144]=a37;
  a37=(a14*a31);
  if (res[0]!=0) res[0][145]=a37;
  a37=(a14*a32);
  if (res[0]!=0) res[0][146]=a37;
  a37=(a14*a33);
  if (res[0]!=0) res[0][147]=a37;
  a37=(a14*a34);
  if (res[0]!=0) res[0][148]=a37;
  a37=(a14*a35);
  if (res[0]!=0) res[0][149]=a37;
  a37=(a14*a36);
  if (res[0]!=0) res[0][150]=a37;
  a37=(a14*a03);
  if (res[0]!=0) res[0][151]=a37;
  a37=(a15*a04);
  if (res[0]!=0) res[0][152]=a37;
  a37=(a15*a01);
  if (res[0]!=0) res[0][153]=a37;
  a37=(a15*a07);
  if (res[0]!=0) res[0][154]=a37;
  a37=(a15*a21);
  if (res[0]!=0) res[0][155]=a37;
  a37=(a15*a23);
  if (res[0]!=0) res[0][156]=a37;
  a37=(a15*a24);
  if (res[0]!=0) res[0][157]=a37;
  a37=(a15*a25);
  if (res[0]!=0) res[0][158]=a37;
  a37=(a15*a22);
  if (res[0]!=0) res[0][159]=a37;
  a37=(a15*a27);
  if (res[0]!=0) res[0][160]=a37;
  a37=(a15*a29);
  if (res[0]!=0) res[0][161]=a37;
  a37=(a15*a28);
  if (res[0]!=0) res[0][162]=a37;
  a37=(a15*a26);
  if (res[0]!=0) res[0][163]=a37;
  a37=(a15*a31);
  if (res[0]!=0) res[0][164]=a37;
  a37=(a15*a32);
  if (res[0]!=0) res[0][165]=a37;
  a37=(a15*a33);
  if (res[0]!=0) res[0][166]=a37;
  a37=(a15*a34);
  if (res[0]!=0) res[0][167]=a37;
  a37=(a15*a35);
  if (res[0]!=0) res[0][168]=a37;
  a37=(a15*a36);
  if (res[0]!=0) res[0][169]=a37;
  a37=(a15*a03);
  if (res[0]!=0) res[0][170]=a37;
  a37=(a16*a04);
  if (res[0]!=0) res[0][171]=a37;
  a37=(a16*a01);
  if (res[0]!=0) res[0][172]=a37;
  a37=(a16*a07);
  if (res[0]!=0) res[0][173]=a37;
  a37=(a16*a21);
  if (res[0]!=0) res[0][174]=a37;
  a37=(a16*a23);
  if (res[0]!=0) res[0][175]=a37;
  a37=(a16*a24);
  if (res[0]!=0) res[0][176]=a37;
  a37=(a16*a25);
  if (res[0]!=0) res[0][177]=a37;
  a37=(a16*a22);
  if (res[0]!=0) res[0][178]=a37;
  a37=(a16*a27);
  if (res[0]!=0) res[0][179]=a37;
  a37=(a16*a29);
  if (res[0]!=0) res[0][180]=a37;
  a37=(a16*a28);
  if (res[0]!=0) res[0][181]=a37;
  a37=(a16*a26);
  if (res[0]!=0) res[0][182]=a37;
  a37=(a16*a31);
  if (res[0]!=0) res[0][183]=a37;
  a37=(a16*a32);
  if (res[0]!=0) res[0][184]=a37;
  a37=(a16*a33);
  if (res[0]!=0) res[0][185]=a37;
  a37=(a16*a34);
  if (res[0]!=0) res[0][186]=a37;
  a37=(a16*a35);
  if (res[0]!=0) res[0][187]=a37;
  a37=(a16*a36);
  if (res[0]!=0) res[0][188]=a37;
  a37=(a16*a03);
  if (res[0]!=0) res[0][189]=a37;
  a37=(a17*a04);
  if (res[0]!=0) res[0][190]=a37;
  a37=(a17*a01);
  if (res[0]!=0) res[0][191]=a37;
  a37=(a17*a07);
  if (res[0]!=0) res[0][192]=a37;
  a37=(a17*a21);
  if (res[0]!=0) res[0][193]=a37;
  a37=(a17*a23);
  if (res[0]!=0) res[0][194]=a37;
  a37=(a17*a24);
  if (res[0]!=0) res[0][195]=a37;
  a37=(a17*a25);
  if (res[0]!=0) res[0][196]=a37;
  a37=(a17*a22);
  if (res[0]!=0) res[0][197]=a37;
  a37=(a17*a27);
  if (res[0]!=0) res[0][198]=a37;
  a37=(a17*a29);
  if (res[0]!=0) res[0][199]=a37;
  a37=(a17*a28);
  if (res[0]!=0) res[0][200]=a37;
  a37=(a17*a26);
  if (res[0]!=0) res[0][201]=a37;
  a37=(a17*a31);
  if (res[0]!=0) res[0][202]=a37;
  a37=(a17*a32);
  if (res[0]!=0) res[0][203]=a37;
  a37=(a17*a33);
  if (res[0]!=0) res[0][204]=a37;
  a37=(a17*a34);
  if (res[0]!=0) res[0][205]=a37;
  a37=(a17*a35);
  if (res[0]!=0) res[0][206]=a37;
  a37=(a17*a36);
  if (res[0]!=0) res[0][207]=a37;
  a37=(a17*a03);
  if (res[0]!=0) res[0][208]=a37;
  a37=(a18*a04);
  if (res[0]!=0) res[0][209]=a37;
  a37=(a18*a01);
  if (res[0]!=0) res[0][210]=a37;
  a37=(a18*a07);
  if (res[0]!=0) res[0][211]=a37;
  a37=(a18*a21);
  if (res[0]!=0) res[0][212]=a37;
  a37=(a18*a23);
  if (res[0]!=0) res[0][213]=a37;
  a37=(a18*a24);
  if (res[0]!=0) res[0][214]=a37;
  a37=(a18*a25);
  if (res[0]!=0) res[0][215]=a37;
  a37=(a18*a22);
  if (res[0]!=0) res[0][216]=a37;
  a37=(a18*a27);
  if (res[0]!=0) res[0][217]=a37;
  a37=(a18*a29);
  if (res[0]!=0) res[0][218]=a37;
  a37=(a18*a28);
  if (res[0]!=0) res[0][219]=a37;
  a37=(a18*a26);
  if (res[0]!=0) res[0][220]=a37;
  a37=(a18*a31);
  if (res[0]!=0) res[0][221]=a37;
  a37=(a18*a32);
  if (res[0]!=0) res[0][222]=a37;
  a37=(a18*a33);
  if (res[0]!=0) res[0][223]=a37;
  a37=(a18*a34);
  if (res[0]!=0) res[0][224]=a37;
  a37=(a18*a35);
  if (res[0]!=0) res[0][225]=a37;
  a37=(a18*a36);
  if (res[0]!=0) res[0][226]=a37;
  a37=(a18*a03);
  if (res[0]!=0) res[0][227]=a37;
  a37=(a19*a04);
  if (res[0]!=0) res[0][228]=a37;
  a37=(a19*a01);
  if (res[0]!=0) res[0][229]=a37;
  a37=(a19*a07);
  if (res[0]!=0) res[0][230]=a37;
  a37=(a19*a21);
  if (res[0]!=0) res[0][231]=a37;
  a37=(a19*a23);
  if (res[0]!=0) res[0][232]=a37;
  a37=(a19*a24);
  if (res[0]!=0) res[0][233]=a37;
  a37=(a19*a25);
  if (res[0]!=0) res[0][234]=a37;
  a37=(a19*a22);
  if (res[0]!=0) res[0][235]=a37;
  a37=(a19*a27);
  if (res[0]!=0) res[0][236]=a37;
  a37=(a19*a29);
  if (res[0]!=0) res[0][237]=a37;
  a37=(a19*a28);
  if (res[0]!=0) res[0][238]=a37;
  a37=(a19*a26);
  if (res[0]!=0) res[0][239]=a37;
  a37=(a19*a31);
  if (res[0]!=0) res[0][240]=a37;
  a37=(a19*a32);
  if (res[0]!=0) res[0][241]=a37;
  a37=(a19*a33);
  if (res[0]!=0) res[0][242]=a37;
  a37=(a19*a34);
  if (res[0]!=0) res[0][243]=a37;
  a37=(a19*a35);
  if (res[0]!=0) res[0][244]=a37;
  a37=(a19*a36);
  if (res[0]!=0) res[0][245]=a37;
  a37=(a19*a03);
  if (res[0]!=0) res[0][246]=a37;
  a37=(a20*a04);
  if (res[0]!=0) res[0][247]=a37;
  a37=(a20*a01);
  if (res[0]!=0) res[0][248]=a37;
  a37=(a20*a07);
  if (res[0]!=0) res[0][249]=a37;
  a37=(a20*a21);
  if (res[0]!=0) res[0][250]=a37;
  a37=(a20*a23);
  if (res[0]!=0) res[0][251]=a37;
  a37=(a20*a24);
  if (res[0]!=0) res[0][252]=a37;
  a37=(a20*a25);
  if (res[0]!=0) res[0][253]=a37;
  a37=(a20*a22);
  if (res[0]!=0) res[0][254]=a37;
  a37=(a20*a27);
  if (res[0]!=0) res[0][255]=a37;
  a37=(a20*a29);
  if (res[0]!=0) res[0][256]=a37;
  a37=(a20*a28);
  if (res[0]!=0) res[0][257]=a37;
  a37=(a20*a26);
  if (res[0]!=0) res[0][258]=a37;
  a37=(a20*a31);
  if (res[0]!=0) res[0][259]=a37;
  a37=(a20*a32);
  if (res[0]!=0) res[0][260]=a37;
  a37=(a20*a33);
  if (res[0]!=0) res[0][261]=a37;
  a37=(a20*a34);
  if (res[0]!=0) res[0][262]=a37;
  a37=(a20*a35);
  if (res[0]!=0) res[0][263]=a37;
  a37=(a20*a36);
  if (res[0]!=0) res[0][264]=a37;
  a37=(a20*a03);
  if (res[0]!=0) res[0][265]=a37;
  a04=(a00*a04);
  if (res[0]!=0) res[0][266]=a04;
  a01=(a00*a01);
  if (res[0]!=0) res[0][267]=a01;
  a07=(a00*a07);
  if (res[0]!=0) res[0][268]=a07;
  a21=(a00*a21);
  if (res[0]!=0) res[0][269]=a21;
  a23=(a00*a23);
  if (res[0]!=0) res[0][270]=a23;
  a24=(a00*a24);
  if (res[0]!=0) res[0][271]=a24;
  a25=(a00*a25);
  if (res[0]!=0) res[0][272]=a25;
  a22=(a00*a22);
  if (res[0]!=0) res[0][273]=a22;
  a27=(a00*a27);
  if (res[0]!=0) res[0][274]=a27;
  a29=(a00*a29);
  if (res[0]!=0) res[0][275]=a29;
  a28=(a00*a28);
  if (res[0]!=0) res[0][276]=a28;
  a26=(a00*a26);
  if (res[0]!=0) res[0][277]=a26;
  a31=(a00*a31);
  if (res[0]!=0) res[0][278]=a31;
  a32=(a00*a32);
  if (res[0]!=0) res[0][279]=a32;
  a33=(a00*a33);
  if (res[0]!=0) res[0][280]=a33;
  a34=(a00*a34);
  if (res[0]!=0) res[0][281]=a34;
  a35=(a00*a35);
  if (res[0]!=0) res[0][282]=a35;
  a36=(a00*a36);
  if (res[0]!=0) res[0][283]=a36;
  a03=(a00*a03);
  if (res[0]!=0) res[0][284]=a03;
  a03=arg[4]? arg[4][45] : 0;
  a03=(a02*a03);
  a36=arg[4]? arg[4][46] : 0;
  a36=(a08*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][47] : 0;
  a36=(a09*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][48] : 0;
  a36=(a10*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][49] : 0;
  a36=(a11*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][50] : 0;
  a36=(a12*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][51] : 0;
  a36=(a13*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][52] : 0;
  a36=(a14*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][53] : 0;
  a36=(a15*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][54] : 0;
  a36=(a16*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][55] : 0;
  a36=(a17*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][56] : 0;
  a36=(a18*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][57] : 0;
  a36=(a19*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][58] : 0;
  a36=(a20*a36);
  a03=(a03+a36);
  a36=arg[4]? arg[4][59] : 0;
  a36=(a00*a36);
  a03=(a03+a36);
  a03=(a03/a06);
  a36=(-a03);
  a36=(a30?a36:0);
  a03=(a05?a03:0);
  a36=(a36+a03);
  a03=arg[4]? arg[4][359] : 0;
  a35=(a36/a03);
  a34=arg[4]? arg[4][362] : 0;
  a33=arg[4]? arg[4][360] : 0;
  a33=(a33*a36);
  a36=arg[4]? arg[4][361] : 0;
  a33=(a33/a36);
  a32=(a34*a33);
  a35=(a35-a32);
  if (res[0]!=0) res[0][285]=a35;
  a35=arg[4]? arg[4][363] : 0;
  a32=arg[4]? arg[4][65] : 0;
  a32=(a02*a32);
  a31=arg[4]? arg[4][66] : 0;
  a31=(a08*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][67] : 0;
  a31=(a09*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][68] : 0;
  a31=(a10*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][69] : 0;
  a31=(a11*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][70] : 0;
  a31=(a12*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][71] : 0;
  a31=(a13*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][72] : 0;
  a31=(a14*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][73] : 0;
  a31=(a15*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][74] : 0;
  a31=(a16*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][75] : 0;
  a31=(a17*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][76] : 0;
  a31=(a18*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][77] : 0;
  a31=(a19*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][78] : 0;
  a31=(a20*a31);
  a32=(a32+a31);
  a31=arg[4]? arg[4][79] : 0;
  a31=(a00*a31);
  a32=(a32+a31);
  a32=(a32/a06);
  a31=(-a32);
  a31=(a30?a31:0);
  a32=(a05?a32:0);
  a31=(a31+a32);
  a35=(a35*a31);
  a35=(a35/a36);
  a32=(a34*a35);
  a32=(-a32);
  if (res[0]!=0) res[0][286]=a32;
  a32=arg[4]? arg[4][364] : 0;
  a26=arg[4]? arg[4][81] : 0;
  a26=(a02*a26);
  a28=arg[4]? arg[4][82] : 0;
  a28=(a08*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][83] : 0;
  a28=(a09*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][84] : 0;
  a28=(a10*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][85] : 0;
  a28=(a11*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][86] : 0;
  a28=(a12*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][87] : 0;
  a28=(a13*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][88] : 0;
  a28=(a14*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][89] : 0;
  a28=(a15*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][90] : 0;
  a28=(a16*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][91] : 0;
  a28=(a17*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][92] : 0;
  a28=(a18*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][93] : 0;
  a28=(a19*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][94] : 0;
  a28=(a20*a28);
  a26=(a26+a28);
  a28=arg[4]? arg[4][95] : 0;
  a28=(a00*a28);
  a26=(a26+a28);
  a26=(a26/a06);
  a28=(-a26);
  a28=(a30?a28:0);
  a26=(a05?a26:0);
  a28=(a28+a26);
  a32=(a32*a28);
  a32=(a32/a36);
  a26=(a34*a32);
  a26=(-a26);
  if (res[0]!=0) res[0][287]=a26;
  a26=arg[4]? arg[4][365] : 0;
  a29=arg[4]? arg[4][97] : 0;
  a02=(a02*a29);
  a29=arg[4]? arg[4][98] : 0;
  a08=(a08*a29);
  a02=(a02+a08);
  a08=arg[4]? arg[4][99] : 0;
  a09=(a09*a08);
  a02=(a02+a09);
  a09=arg[4]? arg[4][100] : 0;
  a10=(a10*a09);
  a02=(a02+a10);
  a10=arg[4]? arg[4][101] : 0;
  a11=(a11*a10);
  a02=(a02+a11);
  a11=arg[4]? arg[4][102] : 0;
  a12=(a12*a11);
  a02=(a02+a12);
  a12=arg[4]? arg[4][103] : 0;
  a13=(a13*a12);
  a02=(a02+a13);
  a13=arg[4]? arg[4][104] : 0;
  a14=(a14*a13);
  a02=(a02+a14);
  a14=arg[4]? arg[4][105] : 0;
  a15=(a15*a14);
  a02=(a02+a15);
  a15=arg[4]? arg[4][106] : 0;
  a16=(a16*a15);
  a02=(a02+a16);
  a16=arg[4]? arg[4][107] : 0;
  a17=(a17*a16);
  a02=(a02+a17);
  a17=arg[4]? arg[4][108] : 0;
  a18=(a18*a17);
  a02=(a02+a18);
  a18=arg[4]? arg[4][109] : 0;
  a19=(a19*a18);
  a02=(a02+a19);
  a19=arg[4]? arg[4][110] : 0;
  a20=(a20*a19);
  a02=(a02+a20);
  a20=arg[4]? arg[4][111] : 0;
  a00=(a00*a20);
  a02=(a02+a00);
  a02=(a02/a06);
  a06=(-a02);
  a30=(a30?a06:0);
  a05=(a05?a02:0);
  a30=(a30+a05);
  a26=(a26*a30);
  a26=(a26/a36);
  a34=(a34*a26);
  a34=(-a34);
  if (res[0]!=0) res[0][288]=a34;
  a34=arg[4]? arg[4][366] : 0;
  a36=(a34*a33);
  a36=(-a36);
  if (res[0]!=0) res[0][289]=a36;
  a31=(a31/a03);
  a36=(a34*a35);
  a31=(a31-a36);
  if (res[0]!=0) res[0][290]=a31;
  a31=(a34*a32);
  a31=(-a31);
  if (res[0]!=0) res[0][291]=a31;
  a34=(a34*a26);
  a34=(-a34);
  if (res[0]!=0) res[0][292]=a34;
  a34=arg[4]? arg[4][367] : 0;
  a31=(a34*a33);
  a31=(-a31);
  if (res[0]!=0) res[0][293]=a31;
  a31=(a34*a35);
  a31=(-a31);
  if (res[0]!=0) res[0][294]=a31;
  a28=(a28/a03);
  a31=(a34*a32);
  a28=(a28-a31);
  if (res[0]!=0) res[0][295]=a28;
  a34=(a34*a26);
  a34=(-a34);
  if (res[0]!=0) res[0][296]=a34;
  a34=arg[4]? arg[4][368] : 0;
  a33=(a34*a33);
  a33=(-a33);
  if (res[0]!=0) res[0][297]=a33;
  a35=(a34*a35);
  a35=(-a35);
  if (res[0]!=0) res[0][298]=a35;
  a32=(a34*a32);
  a32=(-a32);
  if (res[0]!=0) res[0][299]=a32;
  a30=(a30/a03);
  a34=(a34*a26);
  a30=(a30-a34);
  if (res[0]!=0) res[0][300]=a30;
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_incref(void) {
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_cost_ext_cost_hess_xu_p_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
