/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_mpc_alloc_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {84, 1, 1};
static const casadi_int casadi_s4[93] = 
  {18, 12, 0, 7, 14, 20, 25, 29,
  34, 42, 49, 54, 63, 71, 78, 6,
  9, 10, 11, 12, 13, 14, 7, 9,
  10, 11, 12, 13, 14, 8, 9, 10,
  12, 13, 14, 9, 10, 15, 16, 17,
  9, 10, 16, 17, 9, 10, 11, 16,
  17, 0, 1, 2, 3, 4, 5, 10,
  12, 0, 1, 2, 3, 9, 10, 13,
  4, 5, 9, 10, 14, 0, 1, 2,
  3, 4, 5, 9, 10, 15, 0, 1,
  2, 3, 4, 5, 10, 16, 0, 1,
  2, 3, 4, 5, 17};

/* bluerov_mpc_alloc_dyn_disc_phi_fun_jac:(i0[12],i1[6],i2[0],i3[84])->(o0[12],o1[18x12,78nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  casadi_real a72, a73, a74, a75, a76, a77, a78, a79, a80, a81, a82, a83;
  casadi_real a84, a85, a86, a87, a88, a89;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.6000000000000000e-02;
  a02=arg[0]? arg[0][5] : 0;
  a03=cos(a02);
  a04=arg[0]? arg[0][4] : 0;
  a05=cos(a04);
  a06=(a03*a05);
  a07=arg[0]? arg[0][6] : 0;
  a08=(a06*a07);
  a09=sin(a04);
  a10=(a03*a09);
  a11=arg[0]? arg[0][3] : 0;
  a12=sin(a11);
  a13=(a10*a12);
  a14=sin(a02);
  a15=cos(a11);
  a16=(a14*a15);
  a17=(a13-a16);
  a18=arg[0]? arg[0][7] : 0;
  a19=(a17*a18);
  a08=(a08+a19);
  a19=(a10*a15);
  a20=(a14*a12);
  a19=(a19+a20);
  a20=arg[0]? arg[0][8] : 0;
  a21=(a19*a20);
  a08=(a08+a21);
  a08=(a01*a08);
  a00=(a00-a08);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a08=(a14*a05);
  a21=(a08*a07);
  a22=(a14*a09);
  a23=(a22*a12);
  a24=(a03*a15);
  a23=(a23+a24);
  a24=(a23*a18);
  a21=(a21+a24);
  a24=(a22*a15);
  a25=(a03*a12);
  a24=(a24-a25);
  a25=(a24*a20);
  a21=(a21+a25);
  a21=(a01*a21);
  a00=(a00-a21);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a21=(a05*a12);
  a25=(a21*a18);
  a26=(a09*a07);
  a25=(a25-a26);
  a26=(a05*a15);
  a27=(a26*a20);
  a25=(a25+a27);
  a25=(a01*a25);
  a00=(a00-a25);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][9] : 0;
  a25=0.;
  a25=(a25<=a05);
  a27=1.0000000000000000e-03;
  a28=casadi_fmax(a05,a27);
  a28=(a25?a28:0);
  a29=(!a25);
  a30=-1.0000000000000000e-03;
  a31=casadi_fmin(a05,a30);
  a31=(a29?a31:0);
  a28=(a28+a31);
  a31=(a09/a28);
  a32=(a12*a31);
  a33=arg[0]? arg[0][10] : 0;
  a34=(a32*a33);
  a34=(a00+a34);
  a35=(a15*a31);
  a36=arg[0]? arg[0][11] : 0;
  a37=(a35*a36);
  a34=(a34+a37);
  a34=(a01*a34);
  a11=(a11+a34);
  if (res[0]!=0) res[0][3]=a11;
  a11=(a15*a33);
  a34=(a12*a36);
  a11=(a11-a34);
  a11=(a01*a11);
  a04=(a04+a11);
  if (res[0]!=0) res[0][4]=a04;
  a04=(a12/a28);
  a11=(a04*a33);
  a34=(a15/a28);
  a37=(a34*a36);
  a11=(a11+a37);
  a11=(a01*a11);
  a02=(a02+a11);
  if (res[0]!=0) res[0][5]=a02;
  a02=7.0710670948028564e-01;
  a11=arg[1]? arg[1][0] : 0;
  a37=casadi_sq(a11);
  a38=9.9999999999999995e-07;
  a37=(a37+a38);
  a37=sqrt(a37);
  a39=(a11*a37);
  a40=(a02*a39);
  a41=arg[1]? arg[1][1] : 0;
  a42=casadi_sq(a41);
  a42=(a42+a38);
  a42=sqrt(a42);
  a43=(a41*a42);
  a44=(a02*a43);
  a40=(a40+a44);
  a44=-7.0710688829421997e-01;
  a45=arg[1]? arg[1][2] : 0;
  a46=casadi_sq(a45);
  a46=(a46+a38);
  a46=sqrt(a46);
  a47=(a45*a46);
  a48=(a44*a47);
  a40=(a40+a48);
  a48=arg[1]? arg[1][3] : 0;
  a49=casadi_sq(a48);
  a49=(a49+a38);
  a49=sqrt(a49);
  a50=(a48*a49);
  a51=(a44*a50);
  a40=(a40+a51);
  a51=-5.9604651880817983e-08;
  a52=arg[1]? arg[1][4] : 0;
  a53=casadi_sq(a52);
  a53=(a53+a38);
  a53=sqrt(a53);
  a54=(a52*a53);
  a55=(a51*a54);
  a40=(a40+a55);
  a55=arg[1]? arg[1][5] : 0;
  a56=casadi_sq(a55);
  a56=(a56+a38);
  a56=sqrt(a56);
  a57=(a55*a56);
  a58=(a51*a57);
  a40=(a40+a58);
  a58=4.0300000000000002e+00;
  a59=1.8180000000000000e+01;
  a60=casadi_sq(a07);
  a60=(a60+a38);
  a60=sqrt(a60);
  a61=(a59*a60);
  a58=(a58+a61);
  a61=(a58*a07);
  a40=(a40-a61);
  a61=-1.0973710341090168e+00;
  a62=(a61*a09);
  a40=(a40-a62);
  a62=1.6699999809265137e+01;
  a40=(a40/a62);
  a40=(a01*a40);
  a40=(a07+a40);
  if (res[0]!=0) res[0][6]=a40;
  a40=7.0710682868957520e-01;
  a62=(a40*a39);
  a63=-7.0710682868957520e-01;
  a64=(a63*a43);
  a62=(a62+a64);
  a64=(a02*a47);
  a62=(a62+a64);
  a64=-7.0710670948028564e-01;
  a65=(a64*a50);
  a62=(a62+a65);
  a65=6.2199999999999998e+00;
  a66=2.1660000000000000e+01;
  a67=casadi_sq(a18);
  a67=(a67+a38);
  a67=sqrt(a67);
  a68=(a66*a67);
  a65=(a65+a68);
  a68=(a65*a18);
  a62=(a62-a68);
  a68=1.0973710341090168e+00;
  a69=(a68*a12);
  a70=(a69*a05);
  a62=(a62-a70);
  a70=2.3899999809265136e+01;
  a62=(a62/a70);
  a62=(a01*a62);
  a62=(a18+a62);
  if (res[0]!=0) res[0][7]=a62;
  a62=(a54+a57);
  a70=5.1799999999999997e+00;
  a71=3.6990000000000002e+01;
  a72=casadi_sq(a20);
  a72=(a72+a38);
  a72=sqrt(a72);
  a73=(a71*a72);
  a70=(a70+a73);
  a73=(a70*a20);
  a62=(a62-a73);
  a68=(a68*a15);
  a73=(a68*a05);
  a62=(a62-a73);
  a73=2.5769999809265137e+01;
  a62=(a62/a73);
  a62=(a01*a62);
  a62=(a20+a62);
  if (res[0]!=0) res[0][8]=a62;
  a62=5.3063474595546722e-02;
  a73=(a62*a39);
  a74=-5.3063474595546722e-02;
  a75=(a74*a43);
  a73=(a73+a75);
  a75=5.3063467144966125e-02;
  a76=(a75*a47);
  a73=(a73+a76);
  a76=-5.3063467144966125e-02;
  a77=(a76*a50);
  a73=(a73+a77);
  a77=-1.1050009727478027e-01;
  a78=(a77*a54);
  a73=(a73+a78);
  a78=1.1050009727478027e-01;
  a79=(a78*a57);
  a73=(a73+a79);
  a79=7.0000000000000007e-02;
  a80=1.5500000000000000e+00;
  a81=casadi_sq(a00);
  a81=(a81+a38);
  a81=sqrt(a81);
  a82=(a80*a81);
  a82=(a79+a82);
  a83=(a82*a00);
  a73=(a73-a83);
  a83=-1.1096936916300002e+00;
  a84=(a83*a05);
  a85=(a84*a12);
  a73=(a73-a85);
  a85=4.2375000834465026e-01;
  a73=(a73/a85);
  a73=(a01*a73);
  a73=(a00+a73);
  if (res[0]!=0) res[0][9]=a73;
  a73=(a76*a39);
  a85=(a76*a43);
  a73=(a73+a85);
  a85=5.3063482046127319e-02;
  a86=(a85*a47);
  a73=(a73+a86);
  a86=(a85*a50);
  a73=(a73+a86);
  a86=-2.4995799176394939e-03;
  a87=(a86*a54);
  a73=(a73+a87);
  a87=(a86*a57);
  a73=(a73+a87);
  a87=casadi_sq(a33);
  a87=(a87+a38);
  a87=sqrt(a87);
  a88=(a80*a87);
  a88=(a79+a88);
  a89=(a88*a33);
  a73=(a73-a89);
  a83=(a83*a09);
  a73=(a73-a83);
  a89=7.4599998712539672e-01;
  a73=(a73/a89);
  a73=(a01*a73);
  a73=(a33+a73);
  if (res[0]!=0) res[0][10]=a73;
  a73=1.6652354598045349e-01;
  a39=(a73*a39);
  a89=-1.6652354598045349e-01;
  a43=(a89*a43);
  a39=(a39+a43);
  a43=-1.7500889301300049e-01;
  a47=(a43*a47);
  a39=(a39+a47);
  a47=1.7500889301300049e-01;
  a50=(a47*a50);
  a39=(a39+a50);
  a50=-6.5863199338878076e-09;
  a54=(a50*a54);
  a39=(a39+a54);
  a54=6.5863199338878076e-09;
  a57=(a54*a57);
  a39=(a39+a57);
  a57=casadi_sq(a36);
  a57=(a57+a38);
  a57=sqrt(a57);
  a38=(a80*a57);
  a79=(a79+a38);
  a38=(a79*a36);
  a39=(a39-a38);
  a38=6.9690000534057617e-01;
  a39=(a39/a38);
  a39=(a01*a39);
  a39=(a36+a39);
  if (res[0]!=0) res[0][11]=a39;
  a39=1.;
  if (res[1]!=0) res[1][0]=a39;
  a38=(a18*a19);
  a16=(a16-a13);
  a16=(a20*a16);
  a38=(a38+a16);
  a38=(a01*a38);
  a38=(-a38);
  if (res[1]!=0) res[1][1]=a38;
  a38=(a12*a06);
  a38=(a18*a38);
  a10=(a07*a10);
  a38=(a38-a10);
  a10=(a15*a06);
  a10=(a20*a10);
  a38=(a38+a10);
  a38=(a01*a38);
  a38=(-a38);
  if (res[1]!=0) res[1][2]=a38;
  a38=(a12*a03);
  a10=(a09*a14);
  a16=(a15*a10);
  a38=(a38-a16);
  a38=(a20*a38);
  a16=(a05*a14);
  a16=(a07*a16);
  a10=(a12*a10);
  a13=(a15*a03);
  a10=(a10+a13);
  a10=(a18*a10);
  a16=(a16+a10);
  a38=(a38-a16);
  a38=(a01*a38);
  a38=(-a38);
  if (res[1]!=0) res[1][3]=a38;
  a06=(a01*a06);
  a06=(-a06);
  if (res[1]!=0) res[1][4]=a06;
  a17=(a01*a17);
  a17=(-a17);
  if (res[1]!=0) res[1][5]=a17;
  a19=(a01*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][6]=a19;
  if (res[1]!=0) res[1][7]=a39;
  a19=(a18*a24);
  a17=(a20*a23);
  a19=(a19-a17);
  a19=(a01*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][8]=a19;
  a19=(a12*a08);
  a19=(a18*a19);
  a22=(a07*a22);
  a19=(a19-a22);
  a22=(a15*a08);
  a22=(a20*a22);
  a19=(a19+a22);
  a19=(a01*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][9]=a19;
  a19=(a05*a03);
  a19=(a07*a19);
  a03=(a09*a03);
  a22=(a12*a03);
  a17=(a15*a14);
  a22=(a22-a17);
  a22=(a18*a22);
  a19=(a19+a22);
  a03=(a15*a03);
  a14=(a12*a14);
  a03=(a03+a14);
  a03=(a20*a03);
  a19=(a19+a03);
  a19=(a01*a19);
  a19=(-a19);
  if (res[1]!=0) res[1][10]=a19;
  a08=(a01*a08);
  a08=(-a08);
  if (res[1]!=0) res[1][11]=a08;
  a23=(a01*a23);
  a23=(-a23);
  if (res[1]!=0) res[1][12]=a23;
  a24=(a01*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][13]=a24;
  if (res[1]!=0) res[1][14]=a39;
  a24=(a18*a26);
  a23=(a20*a21);
  a24=(a24-a23);
  a24=(a01*a24);
  a24=(-a24);
  if (res[1]!=0) res[1][15]=a24;
  a24=(a12*a09);
  a24=(a18*a24);
  a23=(a07*a05);
  a24=(a24+a23);
  a23=(a15*a09);
  a23=(a20*a23);
  a24=(a24+a23);
  a24=(a01*a24);
  if (res[1]!=0) res[1][16]=a24;
  a24=(a01*a09);
  if (res[1]!=0) res[1][17]=a24;
  a21=(a01*a21);
  a21=(-a21);
  if (res[1]!=0) res[1][18]=a21;
  a26=(a01*a26);
  a26=(-a26);
  if (res[1]!=0) res[1][19]=a26;
  a26=(a31*a15);
  a26=(a33*a26);
  a21=(a31*a12);
  a21=(a36*a21);
  a26=(a26-a21);
  a26=(a01*a26);
  a26=(a39+a26);
  if (res[1]!=0) res[1][20]=a26;
  a26=(a05/a28);
  a31=(a31/a28);
  a21=(a27<=a05);
  a27=(a05<=a27);
  a27=(a21+a27);
  a21=(a21/a27);
  a21=(a21*a09);
  a21=(-a21);
  a25=(a25?a21:0);
  a21=(a05<=a30);
  a30=(a30<=a05);
  a30=(a21+a30);
  a21=(a21/a30);
  a21=(a21*a09);
  a21=(-a21);
  a29=(a29?a21:0);
  a25=(a25+a29);
  a31=(a31*a25);
  a26=(a26-a31);
  a31=(a12*a26);
  a31=(a33*a31);
  a26=(a15*a26);
  a26=(a36*a26);
  a31=(a31+a26);
  a31=(a01*a31);
  if (res[1]!=0) res[1][21]=a31;
  if (res[1]!=0) res[1][22]=a01;
  a32=(a01*a32);
  if (res[1]!=0) res[1][23]=a32;
  a35=(a01*a35);
  if (res[1]!=0) res[1][24]=a35;
  a35=(a33*a12);
  a32=(a36*a15);
  a35=(a35+a32);
  a35=(a01*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][25]=a35;
  if (res[1]!=0) res[1][26]=a39;
  a35=(a01*a15);
  if (res[1]!=0) res[1][27]=a35;
  a35=(a01*a12);
  a35=(-a35);
  if (res[1]!=0) res[1][28]=a35;
  a35=(a33*a34);
  a32=(a36*a04);
  a35=(a35-a32);
  a35=(a01*a35);
  if (res[1]!=0) res[1][29]=a35;
  a35=(a04/a28);
  a35=(a35*a25);
  a35=(a33*a35);
  a28=(a34/a28);
  a28=(a28*a25);
  a28=(a36*a28);
  a35=(a35+a28);
  a35=(a01*a35);
  a35=(-a35);
  if (res[1]!=0) res[1][30]=a35;
  if (res[1]!=0) res[1][31]=a39;
  a04=(a01*a04);
  if (res[1]!=0) res[1][32]=a04;
  a34=(a01*a34);
  if (res[1]!=0) res[1][33]=a34;
  a34=5.9880240204865237e-02;
  a04=(a11/a37);
  a11=(a11*a04);
  a37=(a37+a11);
  a11=(a02*a37);
  a11=(a34*a11);
  a11=(a01*a11);
  if (res[1]!=0) res[1][34]=a11;
  a11=(a41/a42);
  a41=(a41*a11);
  a42=(a42+a41);
  a41=(a02*a42);
  a41=(a34*a41);
  a41=(a01*a41);
  if (res[1]!=0) res[1][35]=a41;
  a41=(a45/a46);
  a45=(a45*a41);
  a46=(a46+a45);
  a45=(a44*a46);
  a45=(a34*a45);
  a45=(a01*a45);
  if (res[1]!=0) res[1][36]=a45;
  a45=(a48/a49);
  a48=(a48*a45);
  a49=(a49+a48);
  a44=(a44*a49);
  a44=(a34*a44);
  a44=(a01*a44);
  if (res[1]!=0) res[1][37]=a44;
  a44=(a52/a53);
  a52=(a52*a44);
  a53=(a53+a52);
  a52=(a51*a53);
  a52=(a34*a52);
  a52=(a01*a52);
  if (res[1]!=0) res[1][38]=a52;
  a52=(a55/a56);
  a55=(a55*a52);
  a56=(a56+a55);
  a51=(a51*a56);
  a51=(a34*a51);
  a51=(a01*a51);
  if (res[1]!=0) res[1][39]=a51;
  a61=(a61*a05);
  a61=(a34*a61);
  a61=(a01*a61);
  a61=(-a61);
  if (res[1]!=0) res[1][40]=a61;
  a60=(a07/a60);
  a59=(a59*a60);
  a07=(a07*a59);
  a07=(a07+a58);
  a34=(a34*a07);
  a34=(a01*a34);
  a34=(a39-a34);
  if (res[1]!=0) res[1][41]=a34;
  a34=4.1841004518014153e-02;
  a40=(a40*a37);
  a40=(a34*a40);
  a40=(a01*a40);
  if (res[1]!=0) res[1][42]=a40;
  a63=(a63*a42);
  a63=(a34*a63);
  a63=(a01*a63);
  if (res[1]!=0) res[1][43]=a63;
  a02=(a02*a46);
  a02=(a34*a02);
  a02=(a01*a02);
  if (res[1]!=0) res[1][44]=a02;
  a64=(a64*a49);
  a64=(a34*a64);
  a64=(a01*a64);
  if (res[1]!=0) res[1][45]=a64;
  a64=(a05*a68);
  a64=(a34*a64);
  a64=(a01*a64);
  a64=(-a64);
  if (res[1]!=0) res[1][46]=a64;
  a64=(a69*a09);
  a64=(a34*a64);
  a64=(a01*a64);
  if (res[1]!=0) res[1][47]=a64;
  a67=(a18/a67);
  a66=(a66*a67);
  a18=(a18*a66);
  a18=(a18+a65);
  a34=(a34*a18);
  a34=(a01*a34);
  a34=(a39-a34);
  if (res[1]!=0) res[1][48]=a34;
  a34=3.8804812083873902e-02;
  a18=(a34*a53);
  a18=(a01*a18);
  if (res[1]!=0) res[1][49]=a18;
  a18=(a34*a56);
  a18=(a01*a18);
  if (res[1]!=0) res[1][50]=a18;
  a05=(a05*a69);
  a05=(a34*a05);
  a05=(a01*a05);
  if (res[1]!=0) res[1][51]=a05;
  a68=(a68*a09);
  a68=(a34*a68);
  a68=(a01*a68);
  if (res[1]!=0) res[1][52]=a68;
  a72=(a20/a72);
  a71=(a71*a72);
  a20=(a20*a71);
  a20=(a20+a70);
  a34=(a34*a20);
  a34=(a01*a34);
  a34=(a39-a34);
  if (res[1]!=0) res[1][53]=a34;
  a34=2.3598819594279892e+00;
  a62=(a62*a37);
  a62=(a34*a62);
  a62=(a01*a62);
  if (res[1]!=0) res[1][54]=a62;
  a74=(a74*a42);
  a74=(a34*a74);
  a74=(a01*a74);
  if (res[1]!=0) res[1][55]=a74;
  a75=(a75*a46);
  a75=(a34*a75);
  a75=(a01*a75);
  if (res[1]!=0) res[1][56]=a75;
  a75=(a76*a49);
  a75=(a34*a75);
  a75=(a01*a75);
  if (res[1]!=0) res[1][57]=a75;
  a77=(a77*a53);
  a77=(a34*a77);
  a77=(a01*a77);
  if (res[1]!=0) res[1][58]=a77;
  a78=(a78*a56);
  a78=(a34*a78);
  a78=(a01*a78);
  if (res[1]!=0) res[1][59]=a78;
  a15=(a84*a15);
  a15=(a34*a15);
  a15=(a01*a15);
  a15=(-a15);
  if (res[1]!=0) res[1][60]=a15;
  a12=(a12*a83);
  a12=(a34*a12);
  a12=(a01*a12);
  if (res[1]!=0) res[1][61]=a12;
  a81=(a00/a81);
  a81=(a80*a81);
  a00=(a00*a81);
  a00=(a00+a82);
  a34=(a34*a00);
  a34=(a01*a34);
  a34=(a39-a34);
  if (res[1]!=0) res[1][62]=a34;
  a34=1.3404825968608334e+00;
  a00=(a76*a37);
  a00=(a34*a00);
  a00=(a01*a00);
  if (res[1]!=0) res[1][63]=a00;
  a76=(a76*a42);
  a76=(a34*a76);
  a76=(a01*a76);
  if (res[1]!=0) res[1][64]=a76;
  a76=(a85*a46);
  a76=(a34*a76);
  a76=(a01*a76);
  if (res[1]!=0) res[1][65]=a76;
  a85=(a85*a49);
  a85=(a34*a85);
  a85=(a01*a85);
  if (res[1]!=0) res[1][66]=a85;
  a85=(a86*a53);
  a85=(a34*a85);
  a85=(a01*a85);
  if (res[1]!=0) res[1][67]=a85;
  a86=(a86*a56);
  a86=(a34*a86);
  a86=(a01*a86);
  if (res[1]!=0) res[1][68]=a86;
  a84=(a34*a84);
  a84=(a01*a84);
  a84=(-a84);
  if (res[1]!=0) res[1][69]=a84;
  a87=(a33/a87);
  a87=(a80*a87);
  a33=(a33*a87);
  a33=(a33+a88);
  a34=(a34*a33);
  a34=(a01*a34);
  a34=(a39-a34);
  if (res[1]!=0) res[1][70]=a34;
  a34=1.4349260903094676e+00;
  a73=(a73*a37);
  a73=(a34*a73);
  a73=(a01*a73);
  if (res[1]!=0) res[1][71]=a73;
  a89=(a89*a42);
  a89=(a34*a89);
  a89=(a01*a89);
  if (res[1]!=0) res[1][72]=a89;
  a43=(a43*a46);
  a43=(a34*a43);
  a43=(a01*a43);
  if (res[1]!=0) res[1][73]=a43;
  a47=(a47*a49);
  a47=(a34*a47);
  a47=(a01*a47);
  if (res[1]!=0) res[1][74]=a47;
  a50=(a50*a53);
  a50=(a34*a50);
  a50=(a01*a50);
  if (res[1]!=0) res[1][75]=a50;
  a54=(a54*a56);
  a54=(a34*a54);
  a54=(a01*a54);
  if (res[1]!=0) res[1][76]=a54;
  a57=(a36/a57);
  a80=(a80*a57);
  a36=(a36*a80);
  a36=(a36+a79);
  a34=(a34*a36);
  a01=(a01*a34);
  a39=(a39-a01);
  if (res[1]!=0) res[1][77]=a39;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_mpc_alloc_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
