/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_mpc_alloc_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {84, 1, 1};
static const casadi_int casadi_s4[98] = 
  {18, 12, 0, 7, 14, 20, 25, 29,
  34, 42, 51, 59, 68, 76, 83, 6,
  9, 10, 11, 12, 13, 14, 7, 9,
  10, 11, 12, 13, 14, 8, 9, 10,
  12, 13, 14, 9, 10, 15, 16, 17,
  9, 10, 16, 17, 9, 10, 11, 16,
  17, 0, 1, 2, 3, 4, 5, 10,
  12, 0, 1, 2, 3, 4, 5, 9,
  10, 13, 1, 2, 3, 4, 5, 9,
  10, 14, 0, 1, 2, 3, 4, 5,
  9, 10, 15, 0, 1, 2, 3, 4,
  5, 10, 16, 0, 1, 2, 3, 4,
  5, 17};

/* bluerov_mpc_alloc_dyn_disc_phi_fun_jac:(i0[12],i1[6],i2[0],i3[84])->(o0[12],o1[18x12,83nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100;
  a000=arg[0]? arg[0][0] : 0;
  a001=1.6000000000000000e-02;
  a002=arg[0]? arg[0][5] : 0;
  a003=cos(a002);
  a004=arg[0]? arg[0][4] : 0;
  a005=cos(a004);
  a006=(a003*a005);
  a007=arg[0]? arg[0][6] : 0;
  a008=(a006*a007);
  a009=sin(a004);
  a010=(a003*a009);
  a011=arg[0]? arg[0][3] : 0;
  a012=sin(a011);
  a013=(a010*a012);
  a014=sin(a002);
  a015=cos(a011);
  a016=(a014*a015);
  a017=(a013-a016);
  a018=arg[0]? arg[0][7] : 0;
  a019=(a017*a018);
  a008=(a008+a019);
  a019=(a010*a015);
  a020=(a014*a012);
  a019=(a019+a020);
  a020=arg[0]? arg[0][8] : 0;
  a021=(a019*a020);
  a008=(a008+a021);
  a008=(a001*a008);
  a000=(a000-a008);
  if (res[0]!=0) res[0][0]=a000;
  a000=arg[0]? arg[0][1] : 0;
  a008=(a014*a005);
  a021=(a008*a007);
  a022=(a014*a009);
  a023=(a022*a012);
  a024=(a003*a015);
  a023=(a023+a024);
  a024=(a023*a018);
  a021=(a021+a024);
  a024=(a022*a015);
  a025=(a003*a012);
  a024=(a024-a025);
  a025=(a024*a020);
  a021=(a021+a025);
  a021=(a001*a021);
  a000=(a000-a021);
  if (res[0]!=0) res[0][1]=a000;
  a000=arg[0]? arg[0][2] : 0;
  a021=(a005*a012);
  a025=(a021*a018);
  a026=(a009*a007);
  a025=(a025-a026);
  a026=(a005*a015);
  a027=(a026*a020);
  a025=(a025+a027);
  a025=(a001*a025);
  a000=(a000-a025);
  if (res[0]!=0) res[0][2]=a000;
  a000=arg[0]? arg[0][9] : 0;
  a025=0.;
  a025=(a025<=a005);
  a027=1.0000000000000000e-03;
  a028=casadi_fmax(a005,a027);
  a028=(a025?a028:0);
  a029=(!a025);
  a030=-1.0000000000000000e-03;
  a031=casadi_fmin(a005,a030);
  a031=(a029?a031:0);
  a028=(a028+a031);
  a031=(a009/a028);
  a032=(a012*a031);
  a033=arg[0]? arg[0][10] : 0;
  a034=(a032*a033);
  a034=(a000+a034);
  a035=(a015*a031);
  a036=arg[0]? arg[0][11] : 0;
  a037=(a035*a036);
  a034=(a034+a037);
  a034=(a001*a034);
  a011=(a011+a034);
  if (res[0]!=0) res[0][3]=a011;
  a011=(a015*a033);
  a034=(a012*a036);
  a011=(a011-a034);
  a011=(a001*a011);
  a004=(a004+a011);
  if (res[0]!=0) res[0][4]=a004;
  a004=(a012/a028);
  a011=(a004*a033);
  a034=(a015/a028);
  a037=(a034*a036);
  a011=(a011+a037);
  a011=(a001*a011);
  a002=(a002+a011);
  if (res[0]!=0) res[0][5]=a002;
  a002=7.0710647106170654e-01;
  a011=arg[1]? arg[1][0] : 0;
  a037=casadi_sq(a011);
  a038=9.9999999999999995e-07;
  a037=(a037+a038);
  a037=sqrt(a037);
  a039=(a011*a037);
  a040=(a002*a039);
  a041=7.0710653066635132e-01;
  a042=arg[1]? arg[1][1] : 0;
  a043=casadi_sq(a042);
  a043=(a043+a038);
  a043=sqrt(a043);
  a044=(a042*a043);
  a045=(a041*a044);
  a040=(a040+a045);
  a045=-7.0710653066635132e-01;
  a046=arg[1]? arg[1][2] : 0;
  a047=casadi_sq(a046);
  a047=(a047+a038);
  a047=sqrt(a047);
  a048=(a046*a047);
  a049=(a045*a048);
  a040=(a040+a049);
  a049=-7.0710659027099609e-01;
  a050=arg[1]? arg[1][3] : 0;
  a051=casadi_sq(a050);
  a051=(a051+a038);
  a051=sqrt(a051);
  a052=(a050*a051);
  a053=(a049*a052);
  a040=(a040+a053);
  a054=5.9604644775390625e-08;
  a055=arg[1]? arg[1][4] : 0;
  a056=casadi_sq(a055);
  a056=(a056+a038);
  a056=sqrt(a056);
  a057=(a055*a056);
  a058=(a054*a057);
  a040=(a040+a058);
  a058=arg[1]? arg[1][5] : 0;
  a059=casadi_sq(a058);
  a059=(a059+a038);
  a059=sqrt(a059);
  a060=(a058*a059);
  a061=(a054*a060);
  a040=(a040+a061);
  a061=4.0300000000000002e+00;
  a062=1.8180000000000000e+01;
  a063=casadi_sq(a007);
  a063=(a063+a038);
  a063=sqrt(a063);
  a064=(a062*a063);
  a061=(a061+a064);
  a064=(a061*a007);
  a040=(a040-a064);
  a064=-1.2869369163000002e+01;
  a065=(a064*a009);
  a040=(a040-a065);
  a065=1.5500000000000000e+01;
  a040=(a040/a065);
  a040=(a001*a040);
  a040=(a007+a040);
  if (res[0]!=0) res[0][6]=a040;
  a040=7.0710664987564087e-01;
  a065=(a040*a039);
  a066=-7.0710670948028564e-01;
  a067=(a066*a044);
  a065=(a065+a067);
  a067=(a041*a048);
  a065=(a065+a067);
  a065=(a065+a053);
  a053=1.0430812835693359e-07;
  a067=(a053*a057);
  a065=(a065+a067);
  a067=(a053*a060);
  a065=(a065+a067);
  a067=6.2199999999999998e+00;
  a068=2.1660000000000000e+01;
  a069=casadi_sq(a018);
  a069=(a069+a038);
  a069=sqrt(a069);
  a070=(a068*a069);
  a067=(a067+a070);
  a070=(a067*a018);
  a065=(a065-a070);
  a070=1.2869369163000002e+01;
  a071=(a070*a012);
  a072=(a071*a005);
  a065=(a065-a072);
  a072=2.2699999999999999e+01;
  a065=(a065/a072);
  a065=(a001*a065);
  a065=(a018+a065);
  if (res[0]!=0) res[0][7]=a065;
  a065=-1.1175870895385742e-08;
  a072=(a065*a044);
  a073=1.8626451492309570e-08;
  a074=(a073*a048);
  a072=(a072+a074);
  a074=-2.9802322387695312e-08;
  a075=(a074*a052);
  a072=(a072+a075);
  a075=9.9999994039535522e-01;
  a076=(a075*a057);
  a072=(a072+a076);
  a076=(a075*a060);
  a072=(a072+a076);
  a076=5.1799999999999997e+00;
  a077=3.6990000000000002e+01;
  a078=casadi_sq(a020);
  a078=(a078+a038);
  a078=sqrt(a078);
  a079=(a077*a078);
  a076=(a076+a079);
  a079=(a076*a020);
  a072=(a072-a079);
  a070=(a070*a015);
  a079=(a070*a005);
  a072=(a072-a079);
  a079=2.4570000000000000e+01;
  a072=(a072/a079);
  a072=(a001*a072);
  a072=(a020+a072);
  if (res[0]!=0) res[0][8]=a072;
  a072=5.1264833658933640e-02;
  a079=(a072*a039);
  a080=-5.1265541464090347e-02;
  a081=(a080*a044);
  a079=(a079+a081);
  a081=5.1265060901641846e-02;
  a082=(a081*a048);
  a079=(a079+a082);
  a082=-5.1264882087707520e-02;
  a083=(a082*a052);
  a079=(a079+a083);
  a083=-1.1050041019916534e-01;
  a084=(a083*a057);
  a079=(a079+a084);
  a084=1.1049991846084595e-01;
  a085=(a084*a060);
  a079=(a079+a085);
  a085=7.0000000000000007e-02;
  a086=1.5500000000000000e+00;
  a087=casadi_sq(a000);
  a087=(a087+a038);
  a087=sqrt(a087);
  a088=(a086*a087);
  a088=(a085+a088);
  a089=(a088*a000);
  a079=(a079-a089);
  a089=-1.1096936916300002e+00;
  a090=(a089*a005);
  a091=(a090*a012);
  a079=(a079-a091);
  a091=1.1200000000000001e+00;
  a079=(a079/a091);
  a079=(a001*a079);
  a079=(a000+a079);
  if (res[0]!=0) res[0][9]=a079;
  a079=-5.1264822483062744e-02;
  a092=(a079*a039);
  a093=-5.1265526562929153e-02;
  a094=(a093*a044);
  a092=(a092+a094);
  a094=5.1265068352222443e-02;
  a095=(a094*a048);
  a092=(a092+a095);
  a095=5.1264874637126923e-02;
  a096=(a095*a052);
  a092=(a092+a096);
  a096=-2.4997028522193432e-03;
  a097=(a096*a057);
  a092=(a092+a097);
  a097=-2.5010984390974045e-03;
  a098=(a097*a060);
  a092=(a092+a098);
  a098=casadi_sq(a033);
  a098=(a098+a038);
  a098=sqrt(a098);
  a099=(a086*a098);
  a099=(a085+a099);
  a100=(a099*a033);
  a092=(a092-a100);
  a089=(a089*a009);
  a092=(a092-a089);
  a092=(a092/a091);
  a092=(a001*a092);
  a092=(a033+a092);
  if (res[0]!=0) res[0][10]=a092;
  a092=1.6652305424213409e-01;
  a039=(a092*a039);
  a100=-1.6652280092239380e-01;
  a044=(a100*a044);
  a039=(a039+a044);
  a044=-1.7500825226306915e-01;
  a048=(a044*a048);
  a039=(a039+a048);
  a048=1.7500790953636169e-01;
  a052=(a048*a052);
  a039=(a039+a052);
  a052=6.8470775715923082e-09;
  a057=(a052*a057);
  a039=(a039+a057);
  a057=-6.3254237403498337e-09;
  a060=(a057*a060);
  a039=(a039+a060);
  a060=casadi_sq(a036);
  a060=(a060+a038);
  a060=sqrt(a060);
  a038=(a086*a060);
  a085=(a085+a038);
  a038=(a085*a036);
  a039=(a039-a038);
  a039=(a039/a091);
  a039=(a001*a039);
  a039=(a036+a039);
  if (res[0]!=0) res[0][11]=a039;
  a039=1.;
  if (res[1]!=0) res[1][0]=a039;
  a091=(a018*a019);
  a016=(a016-a013);
  a016=(a020*a016);
  a091=(a091+a016);
  a091=(a001*a091);
  a091=(-a091);
  if (res[1]!=0) res[1][1]=a091;
  a091=(a012*a006);
  a091=(a018*a091);
  a010=(a007*a010);
  a091=(a091-a010);
  a010=(a015*a006);
  a010=(a020*a010);
  a091=(a091+a010);
  a091=(a001*a091);
  a091=(-a091);
  if (res[1]!=0) res[1][2]=a091;
  a091=(a012*a003);
  a010=(a009*a014);
  a016=(a015*a010);
  a091=(a091-a016);
  a091=(a020*a091);
  a016=(a005*a014);
  a016=(a007*a016);
  a010=(a012*a010);
  a013=(a015*a003);
  a010=(a010+a013);
  a010=(a018*a010);
  a016=(a016+a010);
  a091=(a091-a016);
  a091=(a001*a091);
  a091=(-a091);
  if (res[1]!=0) res[1][3]=a091;
  a006=(a001*a006);
  a006=(-a006);
  if (res[1]!=0) res[1][4]=a006;
  a017=(a001*a017);
  a017=(-a017);
  if (res[1]!=0) res[1][5]=a017;
  a019=(a001*a019);
  a019=(-a019);
  if (res[1]!=0) res[1][6]=a019;
  if (res[1]!=0) res[1][7]=a039;
  a019=(a018*a024);
  a017=(a020*a023);
  a019=(a019-a017);
  a019=(a001*a019);
  a019=(-a019);
  if (res[1]!=0) res[1][8]=a019;
  a019=(a012*a008);
  a019=(a018*a019);
  a022=(a007*a022);
  a019=(a019-a022);
  a022=(a015*a008);
  a022=(a020*a022);
  a019=(a019+a022);
  a019=(a001*a019);
  a019=(-a019);
  if (res[1]!=0) res[1][9]=a019;
  a019=(a005*a003);
  a019=(a007*a019);
  a003=(a009*a003);
  a022=(a012*a003);
  a017=(a015*a014);
  a022=(a022-a017);
  a022=(a018*a022);
  a019=(a019+a022);
  a003=(a015*a003);
  a014=(a012*a014);
  a003=(a003+a014);
  a003=(a020*a003);
  a019=(a019+a003);
  a019=(a001*a019);
  a019=(-a019);
  if (res[1]!=0) res[1][10]=a019;
  a008=(a001*a008);
  a008=(-a008);
  if (res[1]!=0) res[1][11]=a008;
  a023=(a001*a023);
  a023=(-a023);
  if (res[1]!=0) res[1][12]=a023;
  a024=(a001*a024);
  a024=(-a024);
  if (res[1]!=0) res[1][13]=a024;
  if (res[1]!=0) res[1][14]=a039;
  a024=(a018*a026);
  a023=(a020*a021);
  a024=(a024-a023);
  a024=(a001*a024);
  a024=(-a024);
  if (res[1]!=0) res[1][15]=a024;
  a024=(a012*a009);
  a024=(a018*a024);
  a023=(a007*a005);
  a024=(a024+a023);
  a023=(a015*a009);
  a023=(a020*a023);
  a024=(a024+a023);
  a024=(a001*a024);
  if (res[1]!=0) res[1][16]=a024;
  a024=(a001*a009);
  if (res[1]!=0) res[1][17]=a024;
  a021=(a001*a021);
  a021=(-a021);
  if (res[1]!=0) res[1][18]=a021;
  a026=(a001*a026);
  a026=(-a026);
  if (res[1]!=0) res[1][19]=a026;
  a026=(a031*a015);
  a026=(a033*a026);
  a021=(a031*a012);
  a021=(a036*a021);
  a026=(a026-a021);
  a026=(a001*a026);
  a026=(a039+a026);
  if (res[1]!=0) res[1][20]=a026;
  a026=(a005/a028);
  a031=(a031/a028);
  a021=(a027<=a005);
  a027=(a005<=a027);
  a027=(a021+a027);
  a021=(a021/a027);
  a021=(a021*a009);
  a021=(-a021);
  a025=(a025?a021:0);
  a021=(a005<=a030);
  a030=(a030<=a005);
  a030=(a021+a030);
  a021=(a021/a030);
  a021=(a021*a009);
  a021=(-a021);
  a029=(a029?a021:0);
  a025=(a025+a029);
  a031=(a031*a025);
  a026=(a026-a031);
  a031=(a012*a026);
  a031=(a033*a031);
  a026=(a015*a026);
  a026=(a036*a026);
  a031=(a031+a026);
  a031=(a001*a031);
  if (res[1]!=0) res[1][21]=a031;
  if (res[1]!=0) res[1][22]=a001;
  a032=(a001*a032);
  if (res[1]!=0) res[1][23]=a032;
  a035=(a001*a035);
  if (res[1]!=0) res[1][24]=a035;
  a035=(a033*a012);
  a032=(a036*a015);
  a035=(a035+a032);
  a035=(a001*a035);
  a035=(-a035);
  if (res[1]!=0) res[1][25]=a035;
  if (res[1]!=0) res[1][26]=a039;
  a035=(a001*a015);
  if (res[1]!=0) res[1][27]=a035;
  a035=(a001*a012);
  a035=(-a035);
  if (res[1]!=0) res[1][28]=a035;
  a035=(a033*a034);
  a032=(a036*a004);
  a035=(a035-a032);
  a035=(a001*a035);
  if (res[1]!=0) res[1][29]=a035;
  a035=(a004/a028);
  a035=(a035*a025);
  a035=(a033*a035);
  a028=(a034/a028);
  a028=(a028*a025);
  a028=(a036*a028);
  a035=(a035+a028);
  a035=(a001*a035);
  a035=(-a035);
  if (res[1]!=0) res[1][30]=a035;
  if (res[1]!=0) res[1][31]=a039;
  a004=(a001*a004);
  if (res[1]!=0) res[1][32]=a004;
  a034=(a001*a034);
  if (res[1]!=0) res[1][33]=a034;
  a034=6.4516129032258063e-02;
  a004=(a011/a037);
  a011=(a011*a004);
  a037=(a037+a011);
  a002=(a002*a037);
  a002=(a034*a002);
  a002=(a001*a002);
  if (res[1]!=0) res[1][34]=a002;
  a002=(a042/a043);
  a042=(a042*a002);
  a043=(a043+a042);
  a042=(a041*a043);
  a042=(a034*a042);
  a042=(a001*a042);
  if (res[1]!=0) res[1][35]=a042;
  a042=(a046/a047);
  a046=(a046*a042);
  a047=(a047+a046);
  a045=(a045*a047);
  a045=(a034*a045);
  a045=(a001*a045);
  if (res[1]!=0) res[1][36]=a045;
  a045=(a050/a051);
  a050=(a050*a045);
  a051=(a051+a050);
  a049=(a049*a051);
  a050=(a034*a049);
  a050=(a001*a050);
  if (res[1]!=0) res[1][37]=a050;
  a050=(a055/a056);
  a055=(a055*a050);
  a056=(a056+a055);
  a055=(a054*a056);
  a055=(a034*a055);
  a055=(a001*a055);
  if (res[1]!=0) res[1][38]=a055;
  a055=(a058/a059);
  a058=(a058*a055);
  a059=(a059+a058);
  a054=(a054*a059);
  a054=(a034*a054);
  a054=(a001*a054);
  if (res[1]!=0) res[1][39]=a054;
  a064=(a064*a005);
  a064=(a034*a064);
  a064=(a001*a064);
  a064=(-a064);
  if (res[1]!=0) res[1][40]=a064;
  a063=(a007/a063);
  a062=(a062*a063);
  a007=(a007*a062);
  a007=(a007+a061);
  a034=(a034*a007);
  a034=(a001*a034);
  a034=(a039-a034);
  if (res[1]!=0) res[1][41]=a034;
  a034=4.4052863436123350e-02;
  a040=(a040*a037);
  a040=(a034*a040);
  a040=(a001*a040);
  if (res[1]!=0) res[1][42]=a040;
  a066=(a066*a043);
  a066=(a034*a066);
  a066=(a001*a066);
  if (res[1]!=0) res[1][43]=a066;
  a041=(a041*a047);
  a041=(a034*a041);
  a041=(a001*a041);
  if (res[1]!=0) res[1][44]=a041;
  a049=(a034*a049);
  a049=(a001*a049);
  if (res[1]!=0) res[1][45]=a049;
  a049=(a053*a056);
  a049=(a034*a049);
  a049=(a001*a049);
  if (res[1]!=0) res[1][46]=a049;
  a053=(a053*a059);
  a053=(a034*a053);
  a053=(a001*a053);
  if (res[1]!=0) res[1][47]=a053;
  a053=(a005*a070);
  a053=(a034*a053);
  a053=(a001*a053);
  a053=(-a053);
  if (res[1]!=0) res[1][48]=a053;
  a053=(a071*a009);
  a053=(a034*a053);
  a053=(a001*a053);
  if (res[1]!=0) res[1][49]=a053;
  a069=(a018/a069);
  a068=(a068*a069);
  a018=(a018*a068);
  a018=(a018+a067);
  a034=(a034*a018);
  a034=(a001*a034);
  a034=(a039-a034);
  if (res[1]!=0) res[1][50]=a034;
  a034=4.0700040700040699e-02;
  a065=(a065*a043);
  a065=(a034*a065);
  a065=(a001*a065);
  if (res[1]!=0) res[1][51]=a065;
  a073=(a073*a047);
  a073=(a034*a073);
  a073=(a001*a073);
  if (res[1]!=0) res[1][52]=a073;
  a074=(a074*a051);
  a074=(a034*a074);
  a074=(a001*a074);
  if (res[1]!=0) res[1][53]=a074;
  a074=(a075*a056);
  a074=(a034*a074);
  a074=(a001*a074);
  if (res[1]!=0) res[1][54]=a074;
  a075=(a075*a059);
  a075=(a034*a075);
  a075=(a001*a075);
  if (res[1]!=0) res[1][55]=a075;
  a005=(a005*a071);
  a005=(a034*a005);
  a005=(a001*a005);
  if (res[1]!=0) res[1][56]=a005;
  a070=(a070*a009);
  a070=(a034*a070);
  a070=(a001*a070);
  if (res[1]!=0) res[1][57]=a070;
  a078=(a020/a078);
  a077=(a077*a078);
  a020=(a020*a077);
  a020=(a020+a076);
  a034=(a034*a020);
  a034=(a001*a034);
  a034=(a039-a034);
  if (res[1]!=0) res[1][58]=a034;
  a034=8.9285714285714279e-01;
  a072=(a072*a037);
  a072=(a034*a072);
  a072=(a001*a072);
  if (res[1]!=0) res[1][59]=a072;
  a080=(a080*a043);
  a080=(a034*a080);
  a080=(a001*a080);
  if (res[1]!=0) res[1][60]=a080;
  a081=(a081*a047);
  a081=(a034*a081);
  a081=(a001*a081);
  if (res[1]!=0) res[1][61]=a081;
  a082=(a082*a051);
  a082=(a034*a082);
  a082=(a001*a082);
  if (res[1]!=0) res[1][62]=a082;
  a083=(a083*a056);
  a083=(a034*a083);
  a083=(a001*a083);
  if (res[1]!=0) res[1][63]=a083;
  a084=(a084*a059);
  a084=(a034*a084);
  a084=(a001*a084);
  if (res[1]!=0) res[1][64]=a084;
  a015=(a090*a015);
  a015=(a034*a015);
  a015=(a001*a015);
  a015=(-a015);
  if (res[1]!=0) res[1][65]=a015;
  a012=(a012*a089);
  a012=(a034*a012);
  a012=(a001*a012);
  if (res[1]!=0) res[1][66]=a012;
  a087=(a000/a087);
  a087=(a086*a087);
  a000=(a000*a087);
  a000=(a000+a088);
  a000=(a034*a000);
  a000=(a001*a000);
  a000=(a039-a000);
  if (res[1]!=0) res[1][67]=a000;
  a079=(a079*a037);
  a079=(a034*a079);
  a079=(a001*a079);
  if (res[1]!=0) res[1][68]=a079;
  a093=(a093*a043);
  a093=(a034*a093);
  a093=(a001*a093);
  if (res[1]!=0) res[1][69]=a093;
  a094=(a094*a047);
  a094=(a034*a094);
  a094=(a001*a094);
  if (res[1]!=0) res[1][70]=a094;
  a095=(a095*a051);
  a095=(a034*a095);
  a095=(a001*a095);
  if (res[1]!=0) res[1][71]=a095;
  a096=(a096*a056);
  a096=(a034*a096);
  a096=(a001*a096);
  if (res[1]!=0) res[1][72]=a096;
  a097=(a097*a059);
  a097=(a034*a097);
  a097=(a001*a097);
  if (res[1]!=0) res[1][73]=a097;
  a090=(a034*a090);
  a090=(a001*a090);
  a090=(-a090);
  if (res[1]!=0) res[1][74]=a090;
  a098=(a033/a098);
  a098=(a086*a098);
  a033=(a033*a098);
  a033=(a033+a099);
  a033=(a034*a033);
  a033=(a001*a033);
  a033=(a039-a033);
  if (res[1]!=0) res[1][75]=a033;
  a092=(a092*a037);
  a092=(a034*a092);
  a092=(a001*a092);
  if (res[1]!=0) res[1][76]=a092;
  a100=(a100*a043);
  a100=(a034*a100);
  a100=(a001*a100);
  if (res[1]!=0) res[1][77]=a100;
  a044=(a044*a047);
  a044=(a034*a044);
  a044=(a001*a044);
  if (res[1]!=0) res[1][78]=a044;
  a048=(a048*a051);
  a048=(a034*a048);
  a048=(a001*a048);
  if (res[1]!=0) res[1][79]=a048;
  a052=(a052*a056);
  a052=(a034*a052);
  a052=(a001*a052);
  if (res[1]!=0) res[1][80]=a052;
  a057=(a057*a059);
  a057=(a034*a057);
  a057=(a001*a057);
  if (res[1]!=0) res[1][81]=a057;
  a060=(a036/a060);
  a086=(a086*a060);
  a036=(a036*a086);
  a036=(a036+a085);
  a034=(a034*a036);
  a001=(a001*a034);
  a039=(a039-a001);
  if (res[1]!=0) res[1][82]=a039;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_mpc_alloc_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
