/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_mpc_alloc_dyn_disc_phi_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {84, 1, 1};

/* bluerov_mpc_alloc_dyn_disc_phi_fun:(i0[12],i1[6],i2[0],i3[84])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  a00=arg[0]? arg[0][0] : 0;
  a01=1.6000000000000000e-02;
  a02=arg[0]? arg[0][5] : 0;
  a03=cos(a02);
  a04=arg[0]? arg[0][4] : 0;
  a05=cos(a04);
  a06=(a03*a05);
  a07=arg[0]? arg[0][6] : 0;
  a06=(a06*a07);
  a08=sin(a04);
  a09=(a03*a08);
  a10=arg[0]? arg[0][3] : 0;
  a11=sin(a10);
  a12=(a09*a11);
  a13=sin(a02);
  a14=cos(a10);
  a15=(a13*a14);
  a12=(a12-a15);
  a15=arg[0]? arg[0][7] : 0;
  a12=(a12*a15);
  a06=(a06+a12);
  a09=(a09*a14);
  a12=(a13*a11);
  a09=(a09+a12);
  a12=arg[0]? arg[0][8] : 0;
  a09=(a09*a12);
  a06=(a06+a09);
  a06=(a01*a06);
  a00=(a00-a06);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a06=(a13*a05);
  a06=(a06*a07);
  a13=(a13*a08);
  a09=(a13*a11);
  a16=(a03*a14);
  a09=(a09+a16);
  a09=(a09*a15);
  a06=(a06+a09);
  a13=(a13*a14);
  a03=(a03*a11);
  a13=(a13-a03);
  a13=(a13*a12);
  a06=(a06+a13);
  a06=(a01*a06);
  a00=(a00-a06);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a06=(a05*a11);
  a06=(a06*a15);
  a13=(a08*a07);
  a06=(a06-a13);
  a13=(a05*a14);
  a13=(a13*a12);
  a06=(a06+a13);
  a06=(a01*a06);
  a00=(a00-a06);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][9] : 0;
  a06=0.;
  a06=(a06<=a05);
  a13=1.0000000000000000e-03;
  a13=casadi_fmax(a05,a13);
  a13=(a06?a13:0);
  a06=(!a06);
  a03=-1.0000000000000000e-03;
  a03=casadi_fmin(a05,a03);
  a06=(a06?a03:0);
  a13=(a13+a06);
  a06=(a08/a13);
  a03=(a11*a06);
  a09=arg[0]? arg[0][10] : 0;
  a03=(a03*a09);
  a03=(a00+a03);
  a06=(a14*a06);
  a16=arg[0]? arg[0][11] : 0;
  a06=(a06*a16);
  a03=(a03+a06);
  a03=(a01*a03);
  a10=(a10+a03);
  if (res[0]!=0) res[0][3]=a10;
  a10=(a14*a09);
  a03=(a11*a16);
  a10=(a10-a03);
  a10=(a01*a10);
  a04=(a04+a10);
  if (res[0]!=0) res[0][4]=a04;
  a04=(a11/a13);
  a04=(a04*a09);
  a13=(a14/a13);
  a13=(a13*a16);
  a04=(a04+a13);
  a04=(a01*a04);
  a02=(a02+a04);
  if (res[0]!=0) res[0][5]=a02;
  a02=7.0710647106170654e-01;
  a04=arg[1]? arg[1][0] : 0;
  a13=casadi_sq(a04);
  a10=9.9999999999999995e-07;
  a13=(a13+a10);
  a13=sqrt(a13);
  a04=(a04*a13);
  a02=(a02*a04);
  a13=7.0710653066635132e-01;
  a03=arg[1]? arg[1][1] : 0;
  a06=casadi_sq(a03);
  a06=(a06+a10);
  a06=sqrt(a06);
  a03=(a03*a06);
  a06=(a13*a03);
  a02=(a02+a06);
  a06=-7.0710653066635132e-01;
  a17=arg[1]? arg[1][2] : 0;
  a18=casadi_sq(a17);
  a18=(a18+a10);
  a18=sqrt(a18);
  a17=(a17*a18);
  a06=(a06*a17);
  a02=(a02+a06);
  a06=-7.0710659027099609e-01;
  a18=arg[1]? arg[1][3] : 0;
  a19=casadi_sq(a18);
  a19=(a19+a10);
  a19=sqrt(a19);
  a18=(a18*a19);
  a06=(a06*a18);
  a02=(a02+a06);
  a19=5.9604644775390625e-08;
  a20=arg[1]? arg[1][4] : 0;
  a21=casadi_sq(a20);
  a21=(a21+a10);
  a21=sqrt(a21);
  a20=(a20*a21);
  a21=(a19*a20);
  a02=(a02+a21);
  a21=arg[1]? arg[1][5] : 0;
  a22=casadi_sq(a21);
  a22=(a22+a10);
  a22=sqrt(a22);
  a21=(a21*a22);
  a19=(a19*a21);
  a02=(a02+a19);
  a19=4.0300000000000002e+00;
  a22=1.8180000000000000e+01;
  a23=casadi_sq(a07);
  a23=(a23+a10);
  a23=sqrt(a23);
  a22=(a22*a23);
  a19=(a19+a22);
  a19=(a19*a07);
  a02=(a02-a19);
  a19=-1.2869369163000002e+01;
  a19=(a19*a08);
  a02=(a02-a19);
  a19=1.5500000000000000e+01;
  a02=(a02/a19);
  a02=(a01*a02);
  a07=(a07+a02);
  if (res[0]!=0) res[0][6]=a07;
  a07=7.0710664987564087e-01;
  a07=(a07*a04);
  a02=-7.0710670948028564e-01;
  a02=(a02*a03);
  a07=(a07+a02);
  a13=(a13*a17);
  a07=(a07+a13);
  a07=(a07+a06);
  a06=1.0430812835693359e-07;
  a13=(a06*a20);
  a07=(a07+a13);
  a06=(a06*a21);
  a07=(a07+a06);
  a06=6.2199999999999998e+00;
  a13=2.1660000000000000e+01;
  a02=casadi_sq(a15);
  a02=(a02+a10);
  a02=sqrt(a02);
  a13=(a13*a02);
  a06=(a06+a13);
  a06=(a06*a15);
  a07=(a07-a06);
  a06=1.2869369163000002e+01;
  a13=(a06*a11);
  a13=(a13*a05);
  a07=(a07-a13);
  a13=2.2699999999999999e+01;
  a07=(a07/a13);
  a07=(a01*a07);
  a15=(a15+a07);
  if (res[0]!=0) res[0][7]=a15;
  a15=-1.1175870895385742e-08;
  a15=(a15*a03);
  a07=1.8626451492309570e-08;
  a07=(a07*a17);
  a15=(a15+a07);
  a07=-2.9802322387695312e-08;
  a07=(a07*a18);
  a15=(a15+a07);
  a07=9.9999994039535522e-01;
  a13=(a07*a20);
  a15=(a15+a13);
  a07=(a07*a21);
  a15=(a15+a07);
  a07=5.1799999999999997e+00;
  a13=3.6990000000000002e+01;
  a02=casadi_sq(a12);
  a02=(a02+a10);
  a02=sqrt(a02);
  a13=(a13*a02);
  a07=(a07+a13);
  a07=(a07*a12);
  a15=(a15-a07);
  a06=(a06*a14);
  a06=(a06*a05);
  a15=(a15-a06);
  a06=2.4570000000000000e+01;
  a15=(a15/a06);
  a15=(a01*a15);
  a12=(a12+a15);
  if (res[0]!=0) res[0][8]=a12;
  a12=5.1264833658933640e-02;
  a12=(a12*a04);
  a15=-5.1265541464090347e-02;
  a15=(a15*a03);
  a12=(a12+a15);
  a15=5.1265060901641846e-02;
  a15=(a15*a17);
  a12=(a12+a15);
  a15=-5.1264882087707520e-02;
  a15=(a15*a18);
  a12=(a12+a15);
  a15=-1.1050041019916534e-01;
  a15=(a15*a20);
  a12=(a12+a15);
  a15=1.1049991846084595e-01;
  a15=(a15*a21);
  a12=(a12+a15);
  a15=7.0000000000000007e-02;
  a06=1.5500000000000000e+00;
  a14=casadi_sq(a00);
  a14=(a14+a10);
  a14=sqrt(a14);
  a14=(a06*a14);
  a14=(a15+a14);
  a14=(a14*a00);
  a12=(a12-a14);
  a14=-1.1096936916300002e+00;
  a05=(a14*a05);
  a05=(a05*a11);
  a12=(a12-a05);
  a05=1.1200000000000001e+00;
  a12=(a12/a05);
  a12=(a01*a12);
  a00=(a00+a12);
  if (res[0]!=0) res[0][9]=a00;
  a00=-5.1264822483062744e-02;
  a00=(a00*a04);
  a12=-5.1265526562929153e-02;
  a12=(a12*a03);
  a00=(a00+a12);
  a12=5.1265068352222443e-02;
  a12=(a12*a17);
  a00=(a00+a12);
  a12=5.1264874637126923e-02;
  a12=(a12*a18);
  a00=(a00+a12);
  a12=-2.4997028522193432e-03;
  a12=(a12*a20);
  a00=(a00+a12);
  a12=-2.5010984390974045e-03;
  a12=(a12*a21);
  a00=(a00+a12);
  a12=casadi_sq(a09);
  a12=(a12+a10);
  a12=sqrt(a12);
  a12=(a06*a12);
  a12=(a15+a12);
  a12=(a12*a09);
  a00=(a00-a12);
  a14=(a14*a08);
  a00=(a00-a14);
  a00=(a00/a05);
  a00=(a01*a00);
  a09=(a09+a00);
  if (res[0]!=0) res[0][10]=a09;
  a09=1.6652305424213409e-01;
  a09=(a09*a04);
  a04=-1.6652280092239380e-01;
  a04=(a04*a03);
  a09=(a09+a04);
  a04=-1.7500825226306915e-01;
  a04=(a04*a17);
  a09=(a09+a04);
  a04=1.7500790953636169e-01;
  a04=(a04*a18);
  a09=(a09+a04);
  a04=6.8470775715923082e-09;
  a04=(a04*a20);
  a09=(a09+a04);
  a04=-6.3254237403498337e-09;
  a04=(a04*a21);
  a09=(a09+a04);
  a04=casadi_sq(a16);
  a04=(a04+a10);
  a04=sqrt(a04);
  a06=(a06*a04);
  a15=(a15+a06);
  a15=(a15*a16);
  a09=(a09-a15);
  a09=(a09/a05);
  a01=(a01*a09);
  a16=(a16+a01);
  if (res[0]!=0) res[0][11]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_dyn_disc_phi_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_dyn_disc_phi_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_dyn_disc_phi_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_mpc_alloc_dyn_disc_phi_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_dyn_disc_phi_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_dyn_disc_phi_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_dyn_disc_phi_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_dyn_disc_phi_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_dyn_disc_phi_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
