/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {84, 1, 1};
static const casadi_int casadi_s3[3] = {1, 1, 1};

/* bluerov_mpc_alloc_cost_ext_cost_e_fun_jac:(i0[12],i1[0],i2[0],i3[0],i4[84])->(o0,o1[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38;
  a00=arg[4]? arg[4][0] : 0;
  a01=arg[0]? arg[0][0] : 0;
  a02=casadi_sq(a01);
  a02=(a00*a02);
  a03=arg[4]? arg[4][1] : 0;
  a04=arg[0]? arg[0][1] : 0;
  a05=casadi_sq(a04);
  a05=(a03*a05);
  a02=(a02+a05);
  a05=arg[4]? arg[4][2] : 0;
  a06=arg[0]? arg[0][2] : 0;
  a07=casadi_sq(a06);
  a07=(a05*a07);
  a02=(a02+a07);
  a07=arg[4]? arg[4][3] : 0;
  a08=arg[0]? arg[0][3] : 0;
  a09=casadi_sq(a08);
  a09=(a07*a09);
  a02=(a02+a09);
  a09=arg[4]? arg[4][4] : 0;
  a10=arg[0]? arg[0][4] : 0;
  a11=casadi_sq(a10);
  a11=(a09*a11);
  a02=(a02+a11);
  a11=arg[4]? arg[4][5] : 0;
  a12=arg[0]? arg[0][5] : 0;
  a13=casadi_sq(a12);
  a13=(a11*a13);
  a02=(a02+a13);
  a13=arg[4]? arg[4][6] : 0;
  a14=arg[0]? arg[0][6] : 0;
  a15=casadi_sq(a14);
  a15=(a13*a15);
  a02=(a02+a15);
  a15=arg[4]? arg[4][7] : 0;
  a16=arg[0]? arg[0][7] : 0;
  a17=casadi_sq(a16);
  a17=(a15*a17);
  a02=(a02+a17);
  a17=arg[4]? arg[4][8] : 0;
  a18=arg[0]? arg[0][8] : 0;
  a19=casadi_sq(a18);
  a19=(a17*a19);
  a02=(a02+a19);
  a19=arg[4]? arg[4][9] : 0;
  a20=arg[0]? arg[0][9] : 0;
  a21=casadi_sq(a20);
  a21=(a19*a21);
  a02=(a02+a21);
  a21=arg[4]? arg[4][10] : 0;
  a22=arg[0]? arg[0][10] : 0;
  a23=casadi_sq(a22);
  a23=(a21*a23);
  a02=(a02+a23);
  a23=arg[4]? arg[4][11] : 0;
  a24=arg[0]? arg[0][11] : 0;
  a25=casadi_sq(a24);
  a25=(a23*a25);
  a02=(a02+a25);
  a25=arg[4]? arg[4][18] : 0;
  a26=(a25*a01);
  a27=arg[4]? arg[4][19] : 0;
  a28=(a27*a04);
  a26=(a26+a28);
  a28=arg[4]? arg[4][20] : 0;
  a29=(a28*a06);
  a26=(a26+a29);
  a29=arg[4]? arg[4][21] : 0;
  a30=(a29*a08);
  a26=(a26+a30);
  a30=arg[4]? arg[4][22] : 0;
  a31=(a30*a10);
  a26=(a26+a31);
  a31=arg[4]? arg[4][23] : 0;
  a32=(a31*a12);
  a26=(a26+a32);
  a32=arg[4]? arg[4][24] : 0;
  a33=(a32*a14);
  a26=(a26+a33);
  a33=arg[4]? arg[4][25] : 0;
  a34=(a33*a16);
  a26=(a26+a34);
  a34=arg[4]? arg[4][26] : 0;
  a35=(a34*a18);
  a26=(a26+a35);
  a35=arg[4]? arg[4][27] : 0;
  a36=(a35*a20);
  a26=(a26+a36);
  a36=arg[4]? arg[4][28] : 0;
  a37=(a36*a22);
  a26=(a26+a37);
  a37=arg[4]? arg[4][29] : 0;
  a38=(a37*a24);
  a26=(a26+a38);
  a02=(a02+a26);
  if (res[0]!=0) res[0][0]=a02;
  a01=(a01+a01);
  a01=(a01*a00);
  a25=(a25+a01);
  if (res[1]!=0) res[1][0]=a25;
  a04=(a04+a04);
  a04=(a04*a03);
  a27=(a27+a04);
  if (res[1]!=0) res[1][1]=a27;
  a06=(a06+a06);
  a06=(a06*a05);
  a28=(a28+a06);
  if (res[1]!=0) res[1][2]=a28;
  a08=(a08+a08);
  a08=(a08*a07);
  a29=(a29+a08);
  if (res[1]!=0) res[1][3]=a29;
  a10=(a10+a10);
  a10=(a10*a09);
  a30=(a30+a10);
  if (res[1]!=0) res[1][4]=a30;
  a12=(a12+a12);
  a12=(a12*a11);
  a31=(a31+a12);
  if (res[1]!=0) res[1][5]=a31;
  a14=(a14+a14);
  a14=(a14*a13);
  a32=(a32+a14);
  if (res[1]!=0) res[1][6]=a32;
  a16=(a16+a16);
  a16=(a16*a15);
  a33=(a33+a16);
  if (res[1]!=0) res[1][7]=a33;
  a18=(a18+a18);
  a18=(a18*a17);
  a34=(a34+a18);
  if (res[1]!=0) res[1][8]=a34;
  a20=(a20+a20);
  a20=(a20*a19);
  a35=(a35+a20);
  if (res[1]!=0) res[1][9]=a35;
  a22=(a22+a22);
  a22=(a22*a21);
  a36=(a36+a22);
  if (res[1]!=0) res[1][10]=a36;
  a24=(a24+a24);
  a24=(a24*a23);
  a37=(a37+a24);
  if (res[1]!=0) res[1][11]=a37;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
