/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov_mpc_alloc_p_global_precompute_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {36, 1, 1};
static const casadi_int casadi_s1[3] = {84, 1, 1};

/* bluerov_mpc_alloc_p_global_precompute_fun:(i0[36])->(o0[84]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a04=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a04;
  a05=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a05;
  a06=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][6]=a06;
  a07=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][7]=a07;
  a08=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][8]=a08;
  a09=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][9]=a09;
  a10=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a10;
  a11=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][11]=a11;
  a12=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a12;
  a13=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a13;
  a14=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a14;
  a15=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][15]=a15;
  a16=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][16]=a16;
  a17=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][17]=a17;
  a18=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][18]=a18;
  a18=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a18;
  a18=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][20]=a18;
  a18=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][21]=a18;
  a18=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][22]=a18;
  a18=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][23]=a18;
  a18=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][24]=a18;
  a18=arg[0]? arg[0][25] : 0;
  if (res[0]!=0) res[0][25]=a18;
  a18=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][26]=a18;
  a18=arg[0]? arg[0][27] : 0;
  if (res[0]!=0) res[0][27]=a18;
  a18=arg[0]? arg[0][28] : 0;
  if (res[0]!=0) res[0][28]=a18;
  a18=arg[0]? arg[0][29] : 0;
  if (res[0]!=0) res[0][29]=a18;
  a18=arg[0]? arg[0][30] : 0;
  if (res[0]!=0) res[0][30]=a18;
  a18=arg[0]? arg[0][31] : 0;
  if (res[0]!=0) res[0][31]=a18;
  a18=arg[0]? arg[0][32] : 0;
  if (res[0]!=0) res[0][32]=a18;
  a18=arg[0]? arg[0][33] : 0;
  if (res[0]!=0) res[0][33]=a18;
  a18=arg[0]? arg[0][34] : 0;
  if (res[0]!=0) res[0][34]=a18;
  a18=arg[0]? arg[0][35] : 0;
  if (res[0]!=0) res[0][35]=a18;
  a18=2.;
  a12=(a18*a12);
  if (res[0]!=0) res[0][36]=a12;
  a13=(a18*a13);
  if (res[0]!=0) res[0][37]=a13;
  a14=(a18*a14);
  if (res[0]!=0) res[0][38]=a14;
  a15=(a18*a15);
  if (res[0]!=0) res[0][39]=a15;
  a16=(a18*a16);
  if (res[0]!=0) res[0][40]=a16;
  a17=(a18*a17);
  if (res[0]!=0) res[0][41]=a17;
  a00=(a18*a00);
  if (res[0]!=0) res[0][42]=a00;
  a01=(a18*a01);
  if (res[0]!=0) res[0][43]=a01;
  a02=(a18*a02);
  if (res[0]!=0) res[0][44]=a02;
  a03=(a18*a03);
  if (res[0]!=0) res[0][45]=a03;
  a04=(a18*a04);
  if (res[0]!=0) res[0][46]=a04;
  a05=(a18*a05);
  if (res[0]!=0) res[0][47]=a05;
  a06=(a18*a06);
  if (res[0]!=0) res[0][48]=a06;
  a07=(a18*a07);
  if (res[0]!=0) res[0][49]=a07;
  a08=(a18*a08);
  if (res[0]!=0) res[0][50]=a08;
  a09=(a18*a09);
  if (res[0]!=0) res[0][51]=a09;
  a10=(a18*a10);
  if (res[0]!=0) res[0][52]=a10;
  a18=(a18*a11);
  if (res[0]!=0) res[0][53]=a18;
  if (res[0]!=0) res[0][54]=a12;
  if (res[0]!=0) res[0][55]=a13;
  if (res[0]!=0) res[0][56]=a14;
  if (res[0]!=0) res[0][57]=a15;
  if (res[0]!=0) res[0][58]=a16;
  if (res[0]!=0) res[0][59]=a17;
  if (res[0]!=0) res[0][60]=a00;
  if (res[0]!=0) res[0][61]=a01;
  if (res[0]!=0) res[0][62]=a02;
  if (res[0]!=0) res[0][63]=a03;
  if (res[0]!=0) res[0][64]=a04;
  if (res[0]!=0) res[0][65]=a05;
  if (res[0]!=0) res[0][66]=a06;
  if (res[0]!=0) res[0][67]=a07;
  if (res[0]!=0) res[0][68]=a08;
  if (res[0]!=0) res[0][69]=a09;
  if (res[0]!=0) res[0][70]=a10;
  if (res[0]!=0) res[0][71]=a18;
  if (res[0]!=0) res[0][72]=a00;
  if (res[0]!=0) res[0][73]=a01;
  if (res[0]!=0) res[0][74]=a02;
  if (res[0]!=0) res[0][75]=a03;
  if (res[0]!=0) res[0][76]=a04;
  if (res[0]!=0) res[0][77]=a05;
  if (res[0]!=0) res[0][78]=a06;
  if (res[0]!=0) res[0][79]=a07;
  if (res[0]!=0) res[0][80]=a08;
  if (res[0]!=0) res[0][81]=a09;
  if (res[0]!=0) res[0][82]=a10;
  if (res[0]!=0) res[0][83]=a18;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_p_global_precompute_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_p_global_precompute_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_p_global_precompute_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_p_global_precompute_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_p_global_precompute_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_p_global_precompute_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_p_global_precompute_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov_mpc_alloc_p_global_precompute_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_p_global_precompute_fun_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int bluerov_mpc_alloc_p_global_precompute_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov_mpc_alloc_p_global_precompute_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_p_global_precompute_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov_mpc_alloc_p_global_precompute_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_p_global_precompute_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov_mpc_alloc_p_global_precompute_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_p_global_precompute_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov_mpc_alloc_p_global_precompute_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
