/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hover_mpc_qrdiag_p_global_precompute_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {38, 1, 1};
static const casadi_int casadi_s1[3] = {179, 1, 1};

/* hover_mpc_qrdiag_p_global_precompute_fun:(i0[38])->(o0[179]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a04=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a04;
  a05=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a05;
  a06=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][6]=a06;
  a07=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][7]=a07;
  a08=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][8]=a08;
  a09=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][9]=a09;
  a10=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a10;
  a11=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][11]=a11;
  a12=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a12;
  a13=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a13;
  a14=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a14;
  a15=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][15]=a15;
  a16=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][16]=a16;
  a17=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][17]=a17;
  a18=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][18]=a18;
  a19=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a19;
  a20=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][20]=a20;
  a21=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][21]=a21;
  a22=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][22]=a22;
  a23=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][23]=a23;
  a24=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][24]=a24;
  a25=arg[0]? arg[0][25] : 0;
  if (res[0]!=0) res[0][25]=a25;
  a26=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][26]=a26;
  a27=arg[0]? arg[0][27] : 0;
  if (res[0]!=0) res[0][27]=a27;
  a28=arg[0]? arg[0][28] : 0;
  if (res[0]!=0) res[0][28]=a28;
  a29=arg[0]? arg[0][29] : 0;
  if (res[0]!=0) res[0][29]=a29;
  a30=arg[0]? arg[0][30] : 0;
  if (res[0]!=0) res[0][30]=a30;
  a31=arg[0]? arg[0][31] : 0;
  if (res[0]!=0) res[0][31]=a31;
  a32=arg[0]? arg[0][32] : 0;
  if (res[0]!=0) res[0][32]=a32;
  a32=arg[0]? arg[0][33] : 0;
  if (res[0]!=0) res[0][33]=a32;
  a32=arg[0]? arg[0][34] : 0;
  if (res[0]!=0) res[0][34]=a32;
  a32=arg[0]? arg[0][35] : 0;
  if (res[0]!=0) res[0][35]=a32;
  a32=arg[0]? arg[0][36] : 0;
  if (res[0]!=0) res[0][36]=a32;
  a32=arg[0]? arg[0][37] : 0;
  if (res[0]!=0) res[0][37]=a32;
  a32=5.0000000000000000e-01;
  a13=(a32*a13);
  if (res[0]!=0) res[0][38]=a13;
  a14=(a32*a14);
  if (res[0]!=0) res[0][39]=a14;
  a15=(a32*a15);
  if (res[0]!=0) res[0][40]=a15;
  a16=(a32*a16);
  if (res[0]!=0) res[0][41]=a16;
  a17=(a32*a17);
  if (res[0]!=0) res[0][42]=a17;
  a18=(a32*a18);
  if (res[0]!=0) res[0][43]=a18;
  a33=(a32*a00);
  if (res[0]!=0) res[0][44]=a33;
  a34=(a32*a01);
  if (res[0]!=0) res[0][45]=a34;
  a35=(a32*a02);
  if (res[0]!=0) res[0][46]=a35;
  a36=(a32*a03);
  if (res[0]!=0) res[0][47]=a36;
  a37=(a32*a04);
  if (res[0]!=0) res[0][48]=a37;
  a38=(a32*a05);
  if (res[0]!=0) res[0][49]=a38;
  a39=(a32*a06);
  if (res[0]!=0) res[0][50]=a39;
  a40=(a32*a07);
  if (res[0]!=0) res[0][51]=a40;
  a41=(a32*a08);
  if (res[0]!=0) res[0][52]=a41;
  a42=(a32*a09);
  if (res[0]!=0) res[0][53]=a42;
  a43=(a32*a10);
  if (res[0]!=0) res[0][54]=a43;
  a44=(a32*a11);
  if (res[0]!=0) res[0][55]=a44;
  a32=(a32*a12);
  if (res[0]!=0) res[0][56]=a32;
  if (res[0]!=0) res[0][57]=a13;
  if (res[0]!=0) res[0][58]=a14;
  if (res[0]!=0) res[0][59]=a15;
  if (res[0]!=0) res[0][60]=a16;
  if (res[0]!=0) res[0][61]=a17;
  if (res[0]!=0) res[0][62]=a18;
  if (res[0]!=0) res[0][63]=a33;
  if (res[0]!=0) res[0][64]=a34;
  if (res[0]!=0) res[0][65]=a35;
  if (res[0]!=0) res[0][66]=a36;
  if (res[0]!=0) res[0][67]=a37;
  if (res[0]!=0) res[0][68]=a38;
  if (res[0]!=0) res[0][69]=a39;
  if (res[0]!=0) res[0][70]=a40;
  if (res[0]!=0) res[0][71]=a41;
  if (res[0]!=0) res[0][72]=a42;
  if (res[0]!=0) res[0][73]=a43;
  if (res[0]!=0) res[0][74]=a44;
  if (res[0]!=0) res[0][75]=a32;
  if (res[0]!=0) res[0][76]=a13;
  if (res[0]!=0) res[0][77]=a14;
  if (res[0]!=0) res[0][78]=a15;
  if (res[0]!=0) res[0][79]=a16;
  if (res[0]!=0) res[0][80]=a17;
  if (res[0]!=0) res[0][81]=a18;
  if (res[0]!=0) res[0][82]=a33;
  if (res[0]!=0) res[0][83]=a34;
  if (res[0]!=0) res[0][84]=a35;
  if (res[0]!=0) res[0][85]=a36;
  if (res[0]!=0) res[0][86]=a37;
  if (res[0]!=0) res[0][87]=a38;
  if (res[0]!=0) res[0][88]=a39;
  if (res[0]!=0) res[0][89]=a40;
  if (res[0]!=0) res[0][90]=a41;
  if (res[0]!=0) res[0][91]=a42;
  if (res[0]!=0) res[0][92]=a43;
  if (res[0]!=0) res[0][93]=a44;
  if (res[0]!=0) res[0][94]=a32;
  if (res[0]!=0) res[0][95]=a13;
  if (res[0]!=0) res[0][96]=a14;
  if (res[0]!=0) res[0][97]=a15;
  if (res[0]!=0) res[0][98]=a16;
  if (res[0]!=0) res[0][99]=a17;
  if (res[0]!=0) res[0][100]=a18;
  if (res[0]!=0) res[0][101]=a33;
  if (res[0]!=0) res[0][102]=a34;
  if (res[0]!=0) res[0][103]=a35;
  if (res[0]!=0) res[0][104]=a36;
  if (res[0]!=0) res[0][105]=a37;
  if (res[0]!=0) res[0][106]=a38;
  if (res[0]!=0) res[0][107]=a39;
  if (res[0]!=0) res[0][108]=a40;
  if (res[0]!=0) res[0][109]=a41;
  if (res[0]!=0) res[0][110]=a42;
  if (res[0]!=0) res[0][111]=a43;
  if (res[0]!=0) res[0][112]=a44;
  if (res[0]!=0) res[0][113]=a32;
  a32=5.;
  a00=(a32*a00);
  if (res[0]!=0) res[0][114]=a00;
  a44=10.;
  a19=(a44*a19);
  if (res[0]!=0) res[0][115]=a19;
  a01=(a32*a01);
  if (res[0]!=0) res[0][116]=a01;
  a20=(a44*a20);
  if (res[0]!=0) res[0][117]=a20;
  a02=(a32*a02);
  if (res[0]!=0) res[0][118]=a02;
  a21=(a44*a21);
  if (res[0]!=0) res[0][119]=a21;
  a03=(a32*a03);
  if (res[0]!=0) res[0][120]=a03;
  a22=(a44*a22);
  if (res[0]!=0) res[0][121]=a22;
  a04=(a32*a04);
  if (res[0]!=0) res[0][122]=a04;
  a23=(a44*a23);
  if (res[0]!=0) res[0][123]=a23;
  a05=(a32*a05);
  if (res[0]!=0) res[0][124]=a05;
  a24=(a44*a24);
  if (res[0]!=0) res[0][125]=a24;
  a06=(a32*a06);
  if (res[0]!=0) res[0][126]=a06;
  a25=(a44*a25);
  if (res[0]!=0) res[0][127]=a25;
  a07=(a32*a07);
  if (res[0]!=0) res[0][128]=a07;
  a26=(a44*a26);
  if (res[0]!=0) res[0][129]=a26;
  a08=(a32*a08);
  if (res[0]!=0) res[0][130]=a08;
  a27=(a44*a27);
  if (res[0]!=0) res[0][131]=a27;
  a09=(a32*a09);
  if (res[0]!=0) res[0][132]=a09;
  a28=(a44*a28);
  if (res[0]!=0) res[0][133]=a28;
  a10=(a32*a10);
  if (res[0]!=0) res[0][134]=a10;
  a29=(a44*a29);
  if (res[0]!=0) res[0][135]=a29;
  a11=(a32*a11);
  if (res[0]!=0) res[0][136]=a11;
  a30=(a44*a30);
  if (res[0]!=0) res[0][137]=a30;
  a32=(a32*a12);
  if (res[0]!=0) res[0][138]=a32;
  a44=(a44*a31);
  if (res[0]!=0) res[0][139]=a44;
  a31=2.;
  a12=(a31*a00);
  if (res[0]!=0) res[0][140]=a12;
  a12=(a31*a01);
  if (res[0]!=0) res[0][141]=a12;
  a12=(a31*a02);
  if (res[0]!=0) res[0][142]=a12;
  a12=(a31*a03);
  if (res[0]!=0) res[0][143]=a12;
  a12=(a31*a04);
  if (res[0]!=0) res[0][144]=a12;
  a12=(a31*a05);
  if (res[0]!=0) res[0][145]=a12;
  a12=(a31*a06);
  if (res[0]!=0) res[0][146]=a12;
  a12=(a31*a07);
  if (res[0]!=0) res[0][147]=a12;
  a12=(a31*a08);
  if (res[0]!=0) res[0][148]=a12;
  a12=(a31*a09);
  if (res[0]!=0) res[0][149]=a12;
  a12=(a31*a10);
  if (res[0]!=0) res[0][150]=a12;
  a12=(a31*a11);
  if (res[0]!=0) res[0][151]=a12;
  a31=(a31*a32);
  if (res[0]!=0) res[0][152]=a31;
  if (res[0]!=0) res[0][153]=a00;
  if (res[0]!=0) res[0][154]=a19;
  if (res[0]!=0) res[0][155]=a01;
  if (res[0]!=0) res[0][156]=a20;
  if (res[0]!=0) res[0][157]=a02;
  if (res[0]!=0) res[0][158]=a21;
  if (res[0]!=0) res[0][159]=a03;
  if (res[0]!=0) res[0][160]=a22;
  if (res[0]!=0) res[0][161]=a04;
  if (res[0]!=0) res[0][162]=a23;
  if (res[0]!=0) res[0][163]=a05;
  if (res[0]!=0) res[0][164]=a24;
  if (res[0]!=0) res[0][165]=a06;
  if (res[0]!=0) res[0][166]=a25;
  if (res[0]!=0) res[0][167]=a07;
  if (res[0]!=0) res[0][168]=a26;
  if (res[0]!=0) res[0][169]=a08;
  if (res[0]!=0) res[0][170]=a27;
  if (res[0]!=0) res[0][171]=a09;
  if (res[0]!=0) res[0][172]=a28;
  if (res[0]!=0) res[0][173]=a10;
  if (res[0]!=0) res[0][174]=a29;
  if (res[0]!=0) res[0][175]=a11;
  if (res[0]!=0) res[0][176]=a30;
  if (res[0]!=0) res[0][177]=a32;
  if (res[0]!=0) res[0][178]=a44;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_p_global_precompute_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_p_global_precompute_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_p_global_precompute_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_p_global_precompute_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_p_global_precompute_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_p_global_precompute_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_p_global_precompute_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void hover_mpc_qrdiag_p_global_precompute_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_p_global_precompute_fun_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int hover_mpc_qrdiag_p_global_precompute_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hover_mpc_qrdiag_p_global_precompute_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_p_global_precompute_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hover_mpc_qrdiag_p_global_precompute_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_p_global_precompute_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hover_mpc_qrdiag_p_global_precompute_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_p_global_precompute_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int hover_mpc_qrdiag_p_global_precompute_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
