/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pypose_mpc_alloc_tv_p_global_precompute_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {289, 1, 1};
static const casadi_int casadi_s1[3] = {411, 1, 1};

/* pypose_mpc_alloc_tv_p_global_precompute_fun:(i0[289])->(o0[411]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][38] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][57] : 0;
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[0]? arg[0][76] : 0;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[0]? arg[0][95] : 0;
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][114] : 0;
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[0]? arg[0][133] : 0;
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[0]? arg[0][152] : 0;
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[0]? arg[0][171] : 0;
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[0]? arg[0][190] : 0;
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[0]? arg[0][209] : 0;
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[0]? arg[0][228] : 0;
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[0]? arg[0][247] : 0;
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[0]? arg[0][266] : 0;
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][16]=a00;
  a00=arg[0]? arg[0][39] : 0;
  if (res[0]!=0) res[0][17]=a00;
  a00=arg[0]? arg[0][58] : 0;
  if (res[0]!=0) res[0][18]=a00;
  a00=arg[0]? arg[0][77] : 0;
  if (res[0]!=0) res[0][19]=a00;
  a00=arg[0]? arg[0][96] : 0;
  if (res[0]!=0) res[0][20]=a00;
  a00=arg[0]? arg[0][115] : 0;
  if (res[0]!=0) res[0][21]=a00;
  a00=arg[0]? arg[0][134] : 0;
  if (res[0]!=0) res[0][22]=a00;
  a00=arg[0]? arg[0][153] : 0;
  if (res[0]!=0) res[0][23]=a00;
  a00=arg[0]? arg[0][172] : 0;
  if (res[0]!=0) res[0][24]=a00;
  a00=arg[0]? arg[0][191] : 0;
  if (res[0]!=0) res[0][25]=a00;
  a00=arg[0]? arg[0][210] : 0;
  if (res[0]!=0) res[0][26]=a00;
  a00=arg[0]? arg[0][229] : 0;
  if (res[0]!=0) res[0][27]=a00;
  a00=arg[0]? arg[0][248] : 0;
  if (res[0]!=0) res[0][28]=a00;
  a00=arg[0]? arg[0][267] : 0;
  if (res[0]!=0) res[0][29]=a00;
  a00=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][30]=a00;
  a00=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][31]=a00;
  a00=arg[0]? arg[0][40] : 0;
  if (res[0]!=0) res[0][32]=a00;
  a00=arg[0]? arg[0][59] : 0;
  if (res[0]!=0) res[0][33]=a00;
  a00=arg[0]? arg[0][78] : 0;
  if (res[0]!=0) res[0][34]=a00;
  a00=arg[0]? arg[0][97] : 0;
  if (res[0]!=0) res[0][35]=a00;
  a00=arg[0]? arg[0][116] : 0;
  if (res[0]!=0) res[0][36]=a00;
  a00=arg[0]? arg[0][135] : 0;
  if (res[0]!=0) res[0][37]=a00;
  a00=arg[0]? arg[0][154] : 0;
  if (res[0]!=0) res[0][38]=a00;
  a00=arg[0]? arg[0][173] : 0;
  if (res[0]!=0) res[0][39]=a00;
  a00=arg[0]? arg[0][192] : 0;
  if (res[0]!=0) res[0][40]=a00;
  a00=arg[0]? arg[0][211] : 0;
  if (res[0]!=0) res[0][41]=a00;
  a00=arg[0]? arg[0][230] : 0;
  if (res[0]!=0) res[0][42]=a00;
  a00=arg[0]? arg[0][249] : 0;
  if (res[0]!=0) res[0][43]=a00;
  a00=arg[0]? arg[0][268] : 0;
  if (res[0]!=0) res[0][44]=a00;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][45]=a00;
  a00=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][46]=a00;
  a00=arg[0]? arg[0][41] : 0;
  if (res[0]!=0) res[0][47]=a00;
  a00=arg[0]? arg[0][60] : 0;
  if (res[0]!=0) res[0][48]=a00;
  a00=arg[0]? arg[0][79] : 0;
  if (res[0]!=0) res[0][49]=a00;
  a00=arg[0]? arg[0][98] : 0;
  if (res[0]!=0) res[0][50]=a00;
  a00=arg[0]? arg[0][117] : 0;
  if (res[0]!=0) res[0][51]=a00;
  a00=arg[0]? arg[0][136] : 0;
  if (res[0]!=0) res[0][52]=a00;
  a00=arg[0]? arg[0][155] : 0;
  if (res[0]!=0) res[0][53]=a00;
  a00=arg[0]? arg[0][174] : 0;
  if (res[0]!=0) res[0][54]=a00;
  a00=arg[0]? arg[0][193] : 0;
  if (res[0]!=0) res[0][55]=a00;
  a00=arg[0]? arg[0][212] : 0;
  if (res[0]!=0) res[0][56]=a00;
  a00=arg[0]? arg[0][231] : 0;
  if (res[0]!=0) res[0][57]=a00;
  a00=arg[0]? arg[0][250] : 0;
  if (res[0]!=0) res[0][58]=a00;
  a00=arg[0]? arg[0][269] : 0;
  if (res[0]!=0) res[0][59]=a00;
  a00=arg[0]? arg[0][285] : 0;
  a01=casadi_sq(a00);
  a02=arg[0]? arg[0][286] : 0;
  a03=casadi_sq(a02);
  a01=(a01+a03);
  a03=arg[0]? arg[0][287] : 0;
  a04=casadi_sq(a03);
  a01=(a01+a04);
  a04=arg[0]? arg[0][288] : 0;
  a05=casadi_sq(a04);
  a01=(a01+a05);
  a05=9.9999999999999998e-13;
  a01=(a01+a05);
  a01=sqrt(a01);
  a05=(a00/a01);
  if (res[0]!=0) res[0][60]=a05;
  a06=(a02/a01);
  if (res[0]!=0) res[0][61]=a06;
  a07=(a03/a01);
  if (res[0]!=0) res[0][62]=a07;
  a08=(a04/a01);
  if (res[0]!=0) res[0][63]=a08;
  a09=(-a05);
  if (res[0]!=0) res[0][64]=a09;
  a10=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][65]=a10;
  a10=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][66]=a10;
  a10=arg[0]? arg[0][42] : 0;
  if (res[0]!=0) res[0][67]=a10;
  a10=arg[0]? arg[0][61] : 0;
  if (res[0]!=0) res[0][68]=a10;
  a10=arg[0]? arg[0][80] : 0;
  if (res[0]!=0) res[0][69]=a10;
  a10=arg[0]? arg[0][99] : 0;
  if (res[0]!=0) res[0][70]=a10;
  a10=arg[0]? arg[0][118] : 0;
  if (res[0]!=0) res[0][71]=a10;
  a10=arg[0]? arg[0][137] : 0;
  if (res[0]!=0) res[0][72]=a10;
  a10=arg[0]? arg[0][156] : 0;
  if (res[0]!=0) res[0][73]=a10;
  a10=arg[0]? arg[0][175] : 0;
  if (res[0]!=0) res[0][74]=a10;
  a10=arg[0]? arg[0][194] : 0;
  if (res[0]!=0) res[0][75]=a10;
  a10=arg[0]? arg[0][213] : 0;
  if (res[0]!=0) res[0][76]=a10;
  a10=arg[0]? arg[0][232] : 0;
  if (res[0]!=0) res[0][77]=a10;
  a10=arg[0]? arg[0][251] : 0;
  if (res[0]!=0) res[0][78]=a10;
  a10=arg[0]? arg[0][270] : 0;
  if (res[0]!=0) res[0][79]=a10;
  a10=(-a06);
  if (res[0]!=0) res[0][80]=a10;
  a11=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][81]=a11;
  a11=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][82]=a11;
  a11=arg[0]? arg[0][43] : 0;
  if (res[0]!=0) res[0][83]=a11;
  a11=arg[0]? arg[0][62] : 0;
  if (res[0]!=0) res[0][84]=a11;
  a11=arg[0]? arg[0][81] : 0;
  if (res[0]!=0) res[0][85]=a11;
  a11=arg[0]? arg[0][100] : 0;
  if (res[0]!=0) res[0][86]=a11;
  a11=arg[0]? arg[0][119] : 0;
  if (res[0]!=0) res[0][87]=a11;
  a11=arg[0]? arg[0][138] : 0;
  if (res[0]!=0) res[0][88]=a11;
  a11=arg[0]? arg[0][157] : 0;
  if (res[0]!=0) res[0][89]=a11;
  a11=arg[0]? arg[0][176] : 0;
  if (res[0]!=0) res[0][90]=a11;
  a11=arg[0]? arg[0][195] : 0;
  if (res[0]!=0) res[0][91]=a11;
  a11=arg[0]? arg[0][214] : 0;
  if (res[0]!=0) res[0][92]=a11;
  a11=arg[0]? arg[0][233] : 0;
  if (res[0]!=0) res[0][93]=a11;
  a11=arg[0]? arg[0][252] : 0;
  if (res[0]!=0) res[0][94]=a11;
  a11=arg[0]? arg[0][271] : 0;
  if (res[0]!=0) res[0][95]=a11;
  a11=(-a07);
  if (res[0]!=0) res[0][96]=a11;
  a12=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][97]=a12;
  a12=arg[0]? arg[0][25] : 0;
  if (res[0]!=0) res[0][98]=a12;
  a12=arg[0]? arg[0][44] : 0;
  if (res[0]!=0) res[0][99]=a12;
  a12=arg[0]? arg[0][63] : 0;
  if (res[0]!=0) res[0][100]=a12;
  a12=arg[0]? arg[0][82] : 0;
  if (res[0]!=0) res[0][101]=a12;
  a12=arg[0]? arg[0][101] : 0;
  if (res[0]!=0) res[0][102]=a12;
  a12=arg[0]? arg[0][120] : 0;
  if (res[0]!=0) res[0][103]=a12;
  a12=arg[0]? arg[0][139] : 0;
  if (res[0]!=0) res[0][104]=a12;
  a12=arg[0]? arg[0][158] : 0;
  if (res[0]!=0) res[0][105]=a12;
  a12=arg[0]? arg[0][177] : 0;
  if (res[0]!=0) res[0][106]=a12;
  a12=arg[0]? arg[0][196] : 0;
  if (res[0]!=0) res[0][107]=a12;
  a12=arg[0]? arg[0][215] : 0;
  if (res[0]!=0) res[0][108]=a12;
  a12=arg[0]? arg[0][234] : 0;
  if (res[0]!=0) res[0][109]=a12;
  a12=arg[0]? arg[0][253] : 0;
  if (res[0]!=0) res[0][110]=a12;
  a12=arg[0]? arg[0][272] : 0;
  if (res[0]!=0) res[0][111]=a12;
  a12=(-a08);
  if (res[0]!=0) res[0][112]=a12;
  a13=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][113]=a13;
  a13=arg[0]? arg[0][26] : 0;
  if (res[0]!=0) res[0][114]=a13;
  a13=arg[0]? arg[0][45] : 0;
  if (res[0]!=0) res[0][115]=a13;
  a13=arg[0]? arg[0][64] : 0;
  if (res[0]!=0) res[0][116]=a13;
  a13=arg[0]? arg[0][83] : 0;
  if (res[0]!=0) res[0][117]=a13;
  a13=arg[0]? arg[0][102] : 0;
  if (res[0]!=0) res[0][118]=a13;
  a13=arg[0]? arg[0][121] : 0;
  if (res[0]!=0) res[0][119]=a13;
  a13=arg[0]? arg[0][140] : 0;
  if (res[0]!=0) res[0][120]=a13;
  a13=arg[0]? arg[0][159] : 0;
  if (res[0]!=0) res[0][121]=a13;
  a13=arg[0]? arg[0][178] : 0;
  if (res[0]!=0) res[0][122]=a13;
  a13=arg[0]? arg[0][197] : 0;
  if (res[0]!=0) res[0][123]=a13;
  a13=arg[0]? arg[0][216] : 0;
  if (res[0]!=0) res[0][124]=a13;
  a13=arg[0]? arg[0][235] : 0;
  if (res[0]!=0) res[0][125]=a13;
  a13=arg[0]? arg[0][254] : 0;
  if (res[0]!=0) res[0][126]=a13;
  a13=arg[0]? arg[0][273] : 0;
  if (res[0]!=0) res[0][127]=a13;
  a13=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][128]=a13;
  a13=arg[0]? arg[0][27] : 0;
  if (res[0]!=0) res[0][129]=a13;
  a13=arg[0]? arg[0][46] : 0;
  if (res[0]!=0) res[0][130]=a13;
  a13=arg[0]? arg[0][65] : 0;
  if (res[0]!=0) res[0][131]=a13;
  a13=arg[0]? arg[0][84] : 0;
  if (res[0]!=0) res[0][132]=a13;
  a13=arg[0]? arg[0][103] : 0;
  if (res[0]!=0) res[0][133]=a13;
  a13=arg[0]? arg[0][122] : 0;
  if (res[0]!=0) res[0][134]=a13;
  a13=arg[0]? arg[0][141] : 0;
  if (res[0]!=0) res[0][135]=a13;
  a13=arg[0]? arg[0][160] : 0;
  if (res[0]!=0) res[0][136]=a13;
  a13=arg[0]? arg[0][179] : 0;
  if (res[0]!=0) res[0][137]=a13;
  a13=arg[0]? arg[0][198] : 0;
  if (res[0]!=0) res[0][138]=a13;
  a13=arg[0]? arg[0][217] : 0;
  if (res[0]!=0) res[0][139]=a13;
  a13=arg[0]? arg[0][236] : 0;
  if (res[0]!=0) res[0][140]=a13;
  a13=arg[0]? arg[0][255] : 0;
  if (res[0]!=0) res[0][141]=a13;
  a13=arg[0]? arg[0][274] : 0;
  if (res[0]!=0) res[0][142]=a13;
  a13=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][143]=a13;
  a13=arg[0]? arg[0][28] : 0;
  if (res[0]!=0) res[0][144]=a13;
  a13=arg[0]? arg[0][47] : 0;
  if (res[0]!=0) res[0][145]=a13;
  a13=arg[0]? arg[0][66] : 0;
  if (res[0]!=0) res[0][146]=a13;
  a13=arg[0]? arg[0][85] : 0;
  if (res[0]!=0) res[0][147]=a13;
  a13=arg[0]? arg[0][104] : 0;
  if (res[0]!=0) res[0][148]=a13;
  a13=arg[0]? arg[0][123] : 0;
  if (res[0]!=0) res[0][149]=a13;
  a13=arg[0]? arg[0][142] : 0;
  if (res[0]!=0) res[0][150]=a13;
  a13=arg[0]? arg[0][161] : 0;
  if (res[0]!=0) res[0][151]=a13;
  a13=arg[0]? arg[0][180] : 0;
  if (res[0]!=0) res[0][152]=a13;
  a13=arg[0]? arg[0][199] : 0;
  if (res[0]!=0) res[0][153]=a13;
  a13=arg[0]? arg[0][218] : 0;
  if (res[0]!=0) res[0][154]=a13;
  a13=arg[0]? arg[0][237] : 0;
  if (res[0]!=0) res[0][155]=a13;
  a13=arg[0]? arg[0][256] : 0;
  if (res[0]!=0) res[0][156]=a13;
  a13=arg[0]? arg[0][275] : 0;
  if (res[0]!=0) res[0][157]=a13;
  a13=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][158]=a13;
  a13=arg[0]? arg[0][29] : 0;
  if (res[0]!=0) res[0][159]=a13;
  a13=arg[0]? arg[0][48] : 0;
  if (res[0]!=0) res[0][160]=a13;
  a13=arg[0]? arg[0][67] : 0;
  if (res[0]!=0) res[0][161]=a13;
  a13=arg[0]? arg[0][86] : 0;
  if (res[0]!=0) res[0][162]=a13;
  a13=arg[0]? arg[0][105] : 0;
  if (res[0]!=0) res[0][163]=a13;
  a13=arg[0]? arg[0][124] : 0;
  if (res[0]!=0) res[0][164]=a13;
  a13=arg[0]? arg[0][143] : 0;
  if (res[0]!=0) res[0][165]=a13;
  a13=arg[0]? arg[0][162] : 0;
  if (res[0]!=0) res[0][166]=a13;
  a13=arg[0]? arg[0][181] : 0;
  if (res[0]!=0) res[0][167]=a13;
  a13=arg[0]? arg[0][200] : 0;
  if (res[0]!=0) res[0][168]=a13;
  a13=arg[0]? arg[0][219] : 0;
  if (res[0]!=0) res[0][169]=a13;
  a13=arg[0]? arg[0][238] : 0;
  if (res[0]!=0) res[0][170]=a13;
  a13=arg[0]? arg[0][257] : 0;
  if (res[0]!=0) res[0][171]=a13;
  a13=arg[0]? arg[0][276] : 0;
  if (res[0]!=0) res[0][172]=a13;
  a13=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][173]=a13;
  a13=arg[0]? arg[0][30] : 0;
  if (res[0]!=0) res[0][174]=a13;
  a13=arg[0]? arg[0][49] : 0;
  if (res[0]!=0) res[0][175]=a13;
  a13=arg[0]? arg[0][68] : 0;
  if (res[0]!=0) res[0][176]=a13;
  a13=arg[0]? arg[0][87] : 0;
  if (res[0]!=0) res[0][177]=a13;
  a13=arg[0]? arg[0][106] : 0;
  if (res[0]!=0) res[0][178]=a13;
  a13=arg[0]? arg[0][125] : 0;
  if (res[0]!=0) res[0][179]=a13;
  a13=arg[0]? arg[0][144] : 0;
  if (res[0]!=0) res[0][180]=a13;
  a13=arg[0]? arg[0][163] : 0;
  if (res[0]!=0) res[0][181]=a13;
  a13=arg[0]? arg[0][182] : 0;
  if (res[0]!=0) res[0][182]=a13;
  a13=arg[0]? arg[0][201] : 0;
  if (res[0]!=0) res[0][183]=a13;
  a13=arg[0]? arg[0][220] : 0;
  if (res[0]!=0) res[0][184]=a13;
  a13=arg[0]? arg[0][239] : 0;
  if (res[0]!=0) res[0][185]=a13;
  a13=arg[0]? arg[0][258] : 0;
  if (res[0]!=0) res[0][186]=a13;
  a13=arg[0]? arg[0][277] : 0;
  if (res[0]!=0) res[0][187]=a13;
  a13=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][188]=a13;
  a13=arg[0]? arg[0][31] : 0;
  if (res[0]!=0) res[0][189]=a13;
  a13=arg[0]? arg[0][50] : 0;
  if (res[0]!=0) res[0][190]=a13;
  a13=arg[0]? arg[0][69] : 0;
  if (res[0]!=0) res[0][191]=a13;
  a13=arg[0]? arg[0][88] : 0;
  if (res[0]!=0) res[0][192]=a13;
  a13=arg[0]? arg[0][107] : 0;
  if (res[0]!=0) res[0][193]=a13;
  a13=arg[0]? arg[0][126] : 0;
  if (res[0]!=0) res[0][194]=a13;
  a13=arg[0]? arg[0][145] : 0;
  if (res[0]!=0) res[0][195]=a13;
  a13=arg[0]? arg[0][164] : 0;
  if (res[0]!=0) res[0][196]=a13;
  a13=arg[0]? arg[0][183] : 0;
  if (res[0]!=0) res[0][197]=a13;
  a13=arg[0]? arg[0][202] : 0;
  if (res[0]!=0) res[0][198]=a13;
  a13=arg[0]? arg[0][221] : 0;
  if (res[0]!=0) res[0][199]=a13;
  a13=arg[0]? arg[0][240] : 0;
  if (res[0]!=0) res[0][200]=a13;
  a13=arg[0]? arg[0][259] : 0;
  if (res[0]!=0) res[0][201]=a13;
  a13=arg[0]? arg[0][278] : 0;
  if (res[0]!=0) res[0][202]=a13;
  a13=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][203]=a13;
  a13=arg[0]? arg[0][32] : 0;
  if (res[0]!=0) res[0][204]=a13;
  a13=arg[0]? arg[0][51] : 0;
  if (res[0]!=0) res[0][205]=a13;
  a13=arg[0]? arg[0][70] : 0;
  if (res[0]!=0) res[0][206]=a13;
  a13=arg[0]? arg[0][89] : 0;
  if (res[0]!=0) res[0][207]=a13;
  a13=arg[0]? arg[0][108] : 0;
  if (res[0]!=0) res[0][208]=a13;
  a13=arg[0]? arg[0][127] : 0;
  if (res[0]!=0) res[0][209]=a13;
  a13=arg[0]? arg[0][146] : 0;
  if (res[0]!=0) res[0][210]=a13;
  a13=arg[0]? arg[0][165] : 0;
  if (res[0]!=0) res[0][211]=a13;
  a13=arg[0]? arg[0][184] : 0;
  if (res[0]!=0) res[0][212]=a13;
  a13=arg[0]? arg[0][203] : 0;
  if (res[0]!=0) res[0][213]=a13;
  a13=arg[0]? arg[0][222] : 0;
  if (res[0]!=0) res[0][214]=a13;
  a13=arg[0]? arg[0][241] : 0;
  if (res[0]!=0) res[0][215]=a13;
  a13=arg[0]? arg[0][260] : 0;
  if (res[0]!=0) res[0][216]=a13;
  a13=arg[0]? arg[0][279] : 0;
  if (res[0]!=0) res[0][217]=a13;
  a13=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][218]=a13;
  a13=arg[0]? arg[0][33] : 0;
  if (res[0]!=0) res[0][219]=a13;
  a13=arg[0]? arg[0][52] : 0;
  if (res[0]!=0) res[0][220]=a13;
  a13=arg[0]? arg[0][71] : 0;
  if (res[0]!=0) res[0][221]=a13;
  a13=arg[0]? arg[0][90] : 0;
  if (res[0]!=0) res[0][222]=a13;
  a13=arg[0]? arg[0][109] : 0;
  if (res[0]!=0) res[0][223]=a13;
  a13=arg[0]? arg[0][128] : 0;
  if (res[0]!=0) res[0][224]=a13;
  a13=arg[0]? arg[0][147] : 0;
  if (res[0]!=0) res[0][225]=a13;
  a13=arg[0]? arg[0][166] : 0;
  if (res[0]!=0) res[0][226]=a13;
  a13=arg[0]? arg[0][185] : 0;
  if (res[0]!=0) res[0][227]=a13;
  a13=arg[0]? arg[0][204] : 0;
  if (res[0]!=0) res[0][228]=a13;
  a13=arg[0]? arg[0][223] : 0;
  if (res[0]!=0) res[0][229]=a13;
  a13=arg[0]? arg[0][242] : 0;
  if (res[0]!=0) res[0][230]=a13;
  a13=arg[0]? arg[0][261] : 0;
  if (res[0]!=0) res[0][231]=a13;
  a13=arg[0]? arg[0][280] : 0;
  if (res[0]!=0) res[0][232]=a13;
  a13=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][233]=a13;
  a13=arg[0]? arg[0][34] : 0;
  if (res[0]!=0) res[0][234]=a13;
  a13=arg[0]? arg[0][53] : 0;
  if (res[0]!=0) res[0][235]=a13;
  a13=arg[0]? arg[0][72] : 0;
  if (res[0]!=0) res[0][236]=a13;
  a13=arg[0]? arg[0][91] : 0;
  if (res[0]!=0) res[0][237]=a13;
  a13=arg[0]? arg[0][110] : 0;
  if (res[0]!=0) res[0][238]=a13;
  a13=arg[0]? arg[0][129] : 0;
  if (res[0]!=0) res[0][239]=a13;
  a13=arg[0]? arg[0][148] : 0;
  if (res[0]!=0) res[0][240]=a13;
  a13=arg[0]? arg[0][167] : 0;
  if (res[0]!=0) res[0][241]=a13;
  a13=arg[0]? arg[0][186] : 0;
  if (res[0]!=0) res[0][242]=a13;
  a13=arg[0]? arg[0][205] : 0;
  if (res[0]!=0) res[0][243]=a13;
  a13=arg[0]? arg[0][224] : 0;
  if (res[0]!=0) res[0][244]=a13;
  a13=arg[0]? arg[0][243] : 0;
  if (res[0]!=0) res[0][245]=a13;
  a13=arg[0]? arg[0][262] : 0;
  if (res[0]!=0) res[0][246]=a13;
  a13=arg[0]? arg[0][281] : 0;
  if (res[0]!=0) res[0][247]=a13;
  a13=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][248]=a13;
  a13=arg[0]? arg[0][35] : 0;
  if (res[0]!=0) res[0][249]=a13;
  a13=arg[0]? arg[0][54] : 0;
  if (res[0]!=0) res[0][250]=a13;
  a13=arg[0]? arg[0][73] : 0;
  if (res[0]!=0) res[0][251]=a13;
  a13=arg[0]? arg[0][92] : 0;
  if (res[0]!=0) res[0][252]=a13;
  a13=arg[0]? arg[0][111] : 0;
  if (res[0]!=0) res[0][253]=a13;
  a13=arg[0]? arg[0][130] : 0;
  if (res[0]!=0) res[0][254]=a13;
  a13=arg[0]? arg[0][149] : 0;
  if (res[0]!=0) res[0][255]=a13;
  a13=arg[0]? arg[0][168] : 0;
  if (res[0]!=0) res[0][256]=a13;
  a13=arg[0]? arg[0][187] : 0;
  if (res[0]!=0) res[0][257]=a13;
  a13=arg[0]? arg[0][206] : 0;
  if (res[0]!=0) res[0][258]=a13;
  a13=arg[0]? arg[0][225] : 0;
  if (res[0]!=0) res[0][259]=a13;
  a13=arg[0]? arg[0][244] : 0;
  if (res[0]!=0) res[0][260]=a13;
  a13=arg[0]? arg[0][263] : 0;
  if (res[0]!=0) res[0][261]=a13;
  a13=arg[0]? arg[0][282] : 0;
  if (res[0]!=0) res[0][262]=a13;
  a13=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][263]=a13;
  a13=arg[0]? arg[0][36] : 0;
  if (res[0]!=0) res[0][264]=a13;
  a13=arg[0]? arg[0][55] : 0;
  if (res[0]!=0) res[0][265]=a13;
  a13=arg[0]? arg[0][74] : 0;
  if (res[0]!=0) res[0][266]=a13;
  a13=arg[0]? arg[0][93] : 0;
  if (res[0]!=0) res[0][267]=a13;
  a13=arg[0]? arg[0][112] : 0;
  if (res[0]!=0) res[0][268]=a13;
  a13=arg[0]? arg[0][131] : 0;
  if (res[0]!=0) res[0][269]=a13;
  a13=arg[0]? arg[0][150] : 0;
  if (res[0]!=0) res[0][270]=a13;
  a13=arg[0]? arg[0][169] : 0;
  if (res[0]!=0) res[0][271]=a13;
  a13=arg[0]? arg[0][188] : 0;
  if (res[0]!=0) res[0][272]=a13;
  a13=arg[0]? arg[0][207] : 0;
  if (res[0]!=0) res[0][273]=a13;
  a13=arg[0]? arg[0][226] : 0;
  if (res[0]!=0) res[0][274]=a13;
  a13=arg[0]? arg[0][245] : 0;
  if (res[0]!=0) res[0][275]=a13;
  a13=arg[0]? arg[0][264] : 0;
  if (res[0]!=0) res[0][276]=a13;
  a13=arg[0]? arg[0][283] : 0;
  if (res[0]!=0) res[0][277]=a13;
  a13=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][278]=a13;
  a13=arg[0]? arg[0][37] : 0;
  if (res[0]!=0) res[0][279]=a13;
  a13=arg[0]? arg[0][56] : 0;
  if (res[0]!=0) res[0][280]=a13;
  a13=arg[0]? arg[0][75] : 0;
  if (res[0]!=0) res[0][281]=a13;
  a13=arg[0]? arg[0][94] : 0;
  if (res[0]!=0) res[0][282]=a13;
  a13=arg[0]? arg[0][113] : 0;
  if (res[0]!=0) res[0][283]=a13;
  a13=arg[0]? arg[0][132] : 0;
  if (res[0]!=0) res[0][284]=a13;
  a13=arg[0]? arg[0][151] : 0;
  if (res[0]!=0) res[0][285]=a13;
  a13=arg[0]? arg[0][170] : 0;
  if (res[0]!=0) res[0][286]=a13;
  a13=arg[0]? arg[0][189] : 0;
  if (res[0]!=0) res[0][287]=a13;
  a13=arg[0]? arg[0][208] : 0;
  if (res[0]!=0) res[0][288]=a13;
  a13=arg[0]? arg[0][227] : 0;
  if (res[0]!=0) res[0][289]=a13;
  a13=arg[0]? arg[0][246] : 0;
  if (res[0]!=0) res[0][290]=a13;
  a13=arg[0]? arg[0][265] : 0;
  if (res[0]!=0) res[0][291]=a13;
  a13=arg[0]? arg[0][284] : 0;
  if (res[0]!=0) res[0][292]=a13;
  if (res[0]!=0) res[0][293]=a05;
  if (res[0]!=0) res[0][294]=a06;
  if (res[0]!=0) res[0][295]=a07;
  if (res[0]!=0) res[0][296]=a08;
  if (res[0]!=0) res[0][297]=a09;
  if (res[0]!=0) res[0][298]=a10;
  if (res[0]!=0) res[0][299]=a11;
  if (res[0]!=0) res[0][300]=a12;
  if (res[0]!=0) res[0][301]=a05;
  if (res[0]!=0) res[0][302]=a06;
  if (res[0]!=0) res[0][303]=a07;
  if (res[0]!=0) res[0][304]=a08;
  if (res[0]!=0) res[0][305]=a09;
  if (res[0]!=0) res[0][306]=a10;
  if (res[0]!=0) res[0][307]=a11;
  if (res[0]!=0) res[0][308]=a12;
  if (res[0]!=0) res[0][309]=a05;
  if (res[0]!=0) res[0][310]=a06;
  if (res[0]!=0) res[0][311]=a07;
  if (res[0]!=0) res[0][312]=a08;
  if (res[0]!=0) res[0][313]=a09;
  if (res[0]!=0) res[0][314]=a10;
  if (res[0]!=0) res[0][315]=a11;
  if (res[0]!=0) res[0][316]=a12;
  if (res[0]!=0) res[0][317]=a01;
  a13=(a05/a01);
  if (res[0]!=0) res[0][318]=a13;
  a14=(a01+a01);
  if (res[0]!=0) res[0][319]=a14;
  a00=(a00+a00);
  if (res[0]!=0) res[0][320]=a00;
  a15=(a06/a01);
  if (res[0]!=0) res[0][321]=a15;
  a16=(a07/a01);
  if (res[0]!=0) res[0][322]=a16;
  a17=(a08/a01);
  if (res[0]!=0) res[0][323]=a17;
  a02=(a02+a02);
  if (res[0]!=0) res[0][324]=a02;
  a03=(a03+a03);
  if (res[0]!=0) res[0][325]=a03;
  a04=(a04+a04);
  if (res[0]!=0) res[0][326]=a04;
  if (res[0]!=0) res[0][327]=a05;
  if (res[0]!=0) res[0][328]=a06;
  if (res[0]!=0) res[0][329]=a07;
  if (res[0]!=0) res[0][330]=a08;
  if (res[0]!=0) res[0][331]=a09;
  if (res[0]!=0) res[0][332]=a10;
  if (res[0]!=0) res[0][333]=a11;
  if (res[0]!=0) res[0][334]=a12;
  if (res[0]!=0) res[0][335]=a05;
  if (res[0]!=0) res[0][336]=a06;
  if (res[0]!=0) res[0][337]=a07;
  if (res[0]!=0) res[0][338]=a08;
  if (res[0]!=0) res[0][339]=a09;
  if (res[0]!=0) res[0][340]=a10;
  if (res[0]!=0) res[0][341]=a11;
  if (res[0]!=0) res[0][342]=a12;
  if (res[0]!=0) res[0][343]=a05;
  if (res[0]!=0) res[0][344]=a06;
  if (res[0]!=0) res[0][345]=a07;
  if (res[0]!=0) res[0][346]=a08;
  if (res[0]!=0) res[0][347]=a09;
  if (res[0]!=0) res[0][348]=a10;
  if (res[0]!=0) res[0][349]=a11;
  if (res[0]!=0) res[0][350]=a12;
  if (res[0]!=0) res[0][351]=a05;
  if (res[0]!=0) res[0][352]=a06;
  if (res[0]!=0) res[0][353]=a07;
  if (res[0]!=0) res[0][354]=a08;
  if (res[0]!=0) res[0][355]=a09;
  if (res[0]!=0) res[0][356]=a10;
  if (res[0]!=0) res[0][357]=a11;
  if (res[0]!=0) res[0][358]=a12;
  if (res[0]!=0) res[0][359]=a01;
  if (res[0]!=0) res[0][360]=a13;
  if (res[0]!=0) res[0][361]=a14;
  if (res[0]!=0) res[0][362]=a00;
  if (res[0]!=0) res[0][363]=a15;
  if (res[0]!=0) res[0][364]=a16;
  if (res[0]!=0) res[0][365]=a17;
  if (res[0]!=0) res[0][366]=a02;
  if (res[0]!=0) res[0][367]=a03;
  if (res[0]!=0) res[0][368]=a04;
  if (res[0]!=0) res[0][369]=a05;
  if (res[0]!=0) res[0][370]=a06;
  if (res[0]!=0) res[0][371]=a07;
  if (res[0]!=0) res[0][372]=a08;
  if (res[0]!=0) res[0][373]=a09;
  if (res[0]!=0) res[0][374]=a10;
  if (res[0]!=0) res[0][375]=a11;
  if (res[0]!=0) res[0][376]=a12;
  if (res[0]!=0) res[0][377]=a05;
  if (res[0]!=0) res[0][378]=a06;
  if (res[0]!=0) res[0][379]=a07;
  if (res[0]!=0) res[0][380]=a08;
  if (res[0]!=0) res[0][381]=a09;
  if (res[0]!=0) res[0][382]=a10;
  if (res[0]!=0) res[0][383]=a11;
  if (res[0]!=0) res[0][384]=a12;
  if (res[0]!=0) res[0][385]=a05;
  if (res[0]!=0) res[0][386]=a06;
  if (res[0]!=0) res[0][387]=a07;
  if (res[0]!=0) res[0][388]=a08;
  if (res[0]!=0) res[0][389]=a09;
  if (res[0]!=0) res[0][390]=a10;
  if (res[0]!=0) res[0][391]=a11;
  if (res[0]!=0) res[0][392]=a12;
  if (res[0]!=0) res[0][393]=a05;
  if (res[0]!=0) res[0][394]=a06;
  if (res[0]!=0) res[0][395]=a07;
  if (res[0]!=0) res[0][396]=a08;
  if (res[0]!=0) res[0][397]=a09;
  if (res[0]!=0) res[0][398]=a10;
  if (res[0]!=0) res[0][399]=a11;
  if (res[0]!=0) res[0][400]=a12;
  if (res[0]!=0) res[0][401]=a01;
  if (res[0]!=0) res[0][402]=a13;
  if (res[0]!=0) res[0][403]=a14;
  if (res[0]!=0) res[0][404]=a00;
  if (res[0]!=0) res[0][405]=a15;
  if (res[0]!=0) res[0][406]=a16;
  if (res[0]!=0) res[0][407]=a17;
  if (res[0]!=0) res[0][408]=a02;
  if (res[0]!=0) res[0][409]=a03;
  if (res[0]!=0) res[0][410]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_p_global_precompute_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_p_global_precompute_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_p_global_precompute_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_p_global_precompute_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_p_global_precompute_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_p_global_precompute_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_p_global_precompute_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void pypose_mpc_alloc_tv_p_global_precompute_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pypose_mpc_alloc_tv_p_global_precompute_fun_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int pypose_mpc_alloc_tv_p_global_precompute_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pypose_mpc_alloc_tv_p_global_precompute_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pypose_mpc_alloc_tv_p_global_precompute_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pypose_mpc_alloc_tv_p_global_precompute_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pypose_mpc_alloc_tv_p_global_precompute_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pypose_mpc_alloc_tv_p_global_precompute_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_p_global_precompute_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int pypose_mpc_alloc_tv_p_global_precompute_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
